#Zsmart的版本V7,V8,V9
ZsmartVersion: V8
operator:
    '1': '>'
    '2': '=='
    '3': '<'
    '4': '!='
    '5': 'in'
    '6': 'not in'
    '7': '>='
    '8': '<='
    '9': 'ONE OF'
    'L': 'LIKE'
    'A': 'IS NULL'
    'M': 'NOT LIKE'

WorkFlowType:
    Online Pre-processing Workflow[A]: A
    Online Post-processing Workflow[B]: B
    Recurring Pre-processing Workflow[C]: C
    Credit Control Workflow[D]: D
    Recurring Post-processing Workflow[E]: E
    Acm PricePlan Workflow[F]: F
    Emergency Fee Workflow[G]: G
    Recurring Public Pre-workflow[H]: H
    Price Plan Prerequisite Workflow[P]: P
    Reserve Policy Workflow[R]: R
    Trigger Pre-processing Workflow[T]: T

#如何显示workflow中配置的属性的名字，是取re_attr表，还是reserve_re_attr，还是EA.h文件中的名字，枚举值 RA: re_attr; RRA: reserve_re_attr; EA:EA.h，默认为RA
EventAttrName: RA
#输出文件名后缀，支持py、txt
FileNamePostfix: py

BackupTableList:
    - bwf_cond
    - bwf_cond_group
    - bwf_action
    - bwf_sys_action
    - bwf_step
    - bwf_node
    - bwf_workflow