selectSql:
    bwf_node:
        "select a.node_id, a.workflow_id from bwf_node a where a.first_node = 'Y'"
    bwfNodeName:
        "select a.node_id, a.workflow_id, a.node_name, a.first_node from bwf_node a"
    bwf_step_mysql:
        "select a.step_id,a.node_id,a.output_node_id,a.sort_rule_name,a.exec_order from bwf_step a where (a.exp_date > now() or a.exp_date is null) order by a.node_id, a.exec_order"
    bwf_step_oracle:
        "select a.step_id,a.node_id,a.output_node_id,a.sort_rule_name,a.exec_order from bwf_step a where (a.exp_date > sysdate or a.exp_date is null) order by a.node_id, a.exec_order"
    bwf_cond_group:
        "select a.cond_group_id, a.step_id from bwf_cond_group a order by a.step_id, a.cond_group_id"
    bwf_cond:
        "select a.cond_group_id,a.seq,a.sort_operator,a.function,a.re_attr,a.param1,a.param2,a.is_const,a.r_re_attr,a.r_function,a.r_param1,a.r_param2,a.operand,a.zone_id,a.function_script,a.r_function_script from bwf_cond a order by a.cond_group_id, a.seq"
    bwf_action:
        "select a.step_id,a.seq,a.function,a.src_re_attr,a.obj_re_attr,a.param1,a.param2,a.function_script from bwf_action a order by a.step_id, a.seq"
    bwf_sys_action:
        "select a.sys_action_id,a.step_id,a.sys_action_name,a.ext_script from bwf_sys_action a order by a.step_id, a.sys_action_id"
    sort_function:
        "select a.function,a.function_type_flag,a.comments,a.param_num,a.param1_name,a.param1_value_type,a.param1_value_script,a.param2_name,a.param2_value_type,a.param2_desc,a.param2_value_script,a.usage_flag from sort_function a"
    sys_action_function:
        "select sys_action_name from sys_action_function"
    reAttr:
        "select a.re_attr, a.re_attr_name, a.measurable from re_attr a"
    reserveReAttr:
        "select a.re_attr, a.def_re_attr, b.re_attr_name, b.measurable, b.mask, 'A' src_type from def_re_attr a, reserve_re_attr b where a.def_re_attr = b.re_attr
        union
        select a.re_attr, a.re_attr, a.re_attr_name, a.measurable, a.re_attr_name, a.re_attr_src_type from re_attr a where a.re_attr_src_type != 'A'"
    bwf_workflow:
        "select a.workflow_id, a.workflow_name, a.workflow_type from bwf_workflow a"
    re:
        "select a.re_id, a.re_name from re a where a.re_type = '1'"
    zone:
        "select a.zone_id, a.zone_map_id, a.zone_name from zone a"
    node_id_seq:
        "select nvl(max(node_id), 0) from bwf_node"
    step_id_seq:
        "select nvl(max(step_id), 0) from bwf_step"
    cond_group_id_seq:
        "select nvl(max(cond_group_id), 0) from bwf_cond_group"
    sys_action_id_seq:
        "select nvl(max(sys_action_id), 0) from bwf_sys_action"

updateSql:
    DELETE:
        bwf_cond:
            "delete from t_bwf_cond d
                 where exists (select 1
                          from t_bwf_node a, t_bwf_step b, t_bwf_cond_group c
                         where a.workflow_id = :workflow_id
                           and a.node_id = b.node_id
                           and b.step_id = c.step_id
                           and c.cond_group_id = d.cond_group_id)"
        bwf_cond_group:
            "delete from t_bwf_cond_group c
             where exists (select 1
                      from t_bwf_node a, t_bwf_step b
                     where a.workflow_id = :workflow_id
                       and a.node_id = b.node_id
                       and b.step_id = c.step_id)"
        bwf_action:
            "delete from t_bwf_action c
             where exists (select 1
                      from t_bwf_node a, t_bwf_step b
                     where a.workflow_id = :workflow_id
                       and a.node_id = b.node_id
                       and b.step_id = c.step_id)"
        bwf_sys_action:
            "delete from t_bwf_sys_action c
             where exists (select 1
                      from t_bwf_node a, t_bwf_step b
                     where a.workflow_id = :workflow_id
                       and a.node_id = b.node_id
                       and b.step_id = c.step_id)"
        bwf_step:
            "delete from t_bwf_step b
             where exists (select 1
                      from t_bwf_node a
                     where a.workflow_id = :workflow_id
                       and a.node_id = b.node_id)"
        bwf_node:
            "delete from t_bwf_node a where a.workflow_id = :workflow_id"
        bwf_workflow:
            "delete from t_bwf_workflow a where a.workflow_id = :workflow_id"
    INSERT:
        bwf_workflow:
            "insert into t_bwf_workflow(workflow_id, workflow_name, workflow_type, sp_id)
             values(:workflow_id, :workflow_name, :workflow_type, :sp_id)"
        bwf_node:
            "insert into t_bwf_node(node_id, workflow_id,node_name, first_node, sp_id)
             values(:node_id, :workflow_id, :node_name, :first_node, :sp_id)"
        bwf_step:
            "insert into t_bwf_step(step_id, node_id, output_node_id, sort_rule_name, exec_order, eff_date, sp_id)
             values(:step_id, :node_id, :output_node_id, :sort_rule_name, :exec_order, now()-31, :sp_id)"
        bwf_cond:
            "insert into t_bwf_cond(cond_group_id, seq, sort_operator, function, re_attr, param1, param2, is_const, r_re_attr,r_function, r_param1, r_param2, operand, zone_id,sp_id)
             values(:cond_group_id, :seq, :sort_operator, :function, :re_attr, :param1, :param2, :is_const, :r_re_attr, :r_function, :r_param1, :r_param2, :operand, :zone_id, :sp_id)"
        bwf_cond_group:
            "insert into t_bwf_cond_group(cond_group_id, step_id, sp_id)
             values(:cond_group_id, :step_id, :sp_id)"
        bwf_action:
            "insert into t_bwf_action(step_id, seq, function, src_re_attr, obj_re_attr, param1, param2, sp_id)
             values(:step_id, :seq, :function, :src_re_attr, :obj_re_attr, :param1, :param2, :sp_id)"
        bwf_sys_action:
            "insert into t_bwf_sys_action(sys_action_id, step_id, sys_action_name, sp_id)
             values(:sys_action_id, :step_id, :sys_action_name, :sp_id)"