BadData:
 Balance_records_repeat_check:
   select acct_res_name from DC_CONFIG_BASIC_BALANCE_INFO group by acct_res_name having count(1) > 1
 Offer_records_repeat_check:
   select offer_name,Seq from DC_CONFIG_OFFER_OTC_RENT where seq=1 group by acct_res_name ,seq having count(1) > 1
 Offer_price_plan_repeat_check:
   select offer_name,Seq,price_plan_id from DC_CONFIG_OFFER_OTC_RENT where seq=1 group by offer_name,seq,price_plan_id having count(1) > 1
ErrorData:
 Acct_res_name_check:
   select * from DC_CONFIG_BASIC_BALANCE_INFO where acct_res_name is null

 Bal_Type_check:
   select * from DC_CONFIG_BASIC_BALANCE_INFO where bal_type not in(select  LOOKUP_NAME from CBEC_DOMAIN_DATA where DOMAIN_TYPE_CODE='BAL_TYPE')

 Bonus_Type_check:
   select * from DC_CONFIG_BASIC_BALANCE_INFO where is_currency='N' and unit_type not in ('Second' ,'Byte', 'Occurrence')

 OFFER_INST_VALID_UNIT_CHECK:
   select * from DC_CONFIG_OFFER_OTC_RENT where   OFFER_INST_VALID_UNIT  not in ('day','week','month','year','Billing Cycle')
