create:
    DC_CIC_TRIGGER:
      - |
          create table DC_CIC_TRIGGER
            (
             TEMPLATE_NAME   VARCHAR2(150 CHAR)  NOT NULL,
             OFFER_PRICE_PLAN_NAME VARCHAR2(120) NOT NULL,
             ACCT_RES_NAME   VARCHAR2(60)  NOT NULL,
             TRIGGER_MODE    VARCHAR2(20),
             EFF_DATE        DATE,
             EXP_DATE        DATE,
             TRIGGER_TYPE_NAME    VARCHAR2(20),
             IS_RATIO        CHAR(1) NOT NULL,
             THRESHOLD       NUMBER NOT NULL,
             IS_PCRF         CHAR(1),
             THRESHOLD_INTERVAL NUMBER(12),
             EVENT_CODE      VARCHAR2(120),
             REDIRECT_FLAG     CHAR(1)
            )
      - comment on table DC_CIC_TRIGGER is  'ACCOUNT TRIGGER'
      - comment on column DC_CIC_TRIGGER.TEMPLATE_NAME is  'Advice template name and is the only one'
      - comment on column DC_CIC_TRIGGER.OFFER_PRICE_PLAN_NAME is  'OFFER OR PRICE_PLAN_NAME'
      - comment on column DC_CIC_TRIGGER.ACCT_RES_NAME is  'ACCT_RES_NAME domain:cbec_acct_res'
      - comment on column DC_CIC_TRIGGER.TRIGGER_MODE is  '0 ABS,1 Cross Trigger,2 Precise Trigger,3 Beforehand Trigger'
      - comment on column DC_CIC_TRIGGER.EFF_DATE is 'if EFFECT_DATE is null,it will insert default sysdate '
      - comment on column DC_CIC_TRIGGER.EXP_DATE is 'EXPIRED DATE AND CAN KEEP NULL'
      - comment on column DC_CIC_TRIGGER.TRIGGER_TYPE_NAME is  'TRIGGER_TYPE_NAME. domain:trigger_type'
      - comment on column DC_CIC_TRIGGER.IS_RATIO is  'Trigger is by ratio or By Threshold'
      - comment on column DC_CIC_TRIGGER.TRIGGER_TYPE_NAME is  'TRIGGER_TYPE_NAME'
      - comment on column DC_CIC_TRIGGER.Threshold is  'Less than threshold to trigger. for example radio:20% fill with 200'
      - comment on column DC_CIC_TRIGGER.IS_PCRF is  'If trigger is by PCRF'
      - comment on column DC_CIC_TRIGGER.THRESHOLD_INTERVAL is  'THRESHOLD INTERVAL'
      - comment on column DC_CIC_TRIGGER.EVENT_CODE is  'If trigger mode is Beforehand Trigger,must be config EVENT_CODE'
      - comment on column DC_CIC_TRIGGER.REDIRECT_FLAG is  'If trigger mode is Beforehand Trigger,must be config REDIRECT_FLAG'

create_list:
    DC_CIC_TRIGGER:
        - CIC
        - V20190627
        - table
        - VALUE_LIST:
            TRIGGER_MODE:
              TYPE: list
              SOURCE: ABS,Cross Trigger,Precise Trigger,Beforehand Trigger
            IS_RATIO:
              TYPE: list
              SOURCE: Y,N
            TRIGGER_TYPE_NAME:
              TYPE: sql
              SOURCE: SELECT trigger_type_name FROM cpc.trigger_type
            IS_PCRF:
              TYPE: list
              SOURCE: Y,N
            REDIRECT_FLAG:
              TYPE: list
              SOURCE: Y,N
            EVENT_CODE:
              TYPE: sql
              SOURCE: SELECT event_code FROM cpc.CBEC_INTER_EVENT

