UserList:
  cc

BadData:
  Offer have multiple same addition offer:
    des: 检查一个Offer下是否挂有相同的additonal offer
    area: comm
    sql:
      "SELECT
              a.offer_ver_id,
              c.offer_id
          FROM
              subs_plan_offer_select a,
              offer_group            b,
              offer_group_mem        c
          WHERE
                  a.offer_group_id = b.offer_group_id
              AND b.offer_group_id = c.offer_group_id
          GROUP BY
              a.offer_ver_id,
              c.offer_id
          HAVING
              COUNT(1) > 1"

  Offer and channel rela ITR and UCC follow CRM:
    des: Offer 可以受理的渠道， ITR和UCC需要和CRM渠道的约束一样
    area: A016
    sql:
      "SELECT T.OFFER_ID,COUNT(1) FROM OFFER_APPLY_CHANNEL T WHERE T.CONTACT_CHANNEL_ID IN('1','56','57')
                    AND T.OFFER_ID>100000 GROUP BY T.OFFER_ID HAVING COUNT(1)<3"
