UserList:
  cic

BadData:
  cic flow status is draft:
    des: 检查CIC中的flow的状态，是否有未发布状态的
    area: comm
    sql:
      "select * from
       cic.cic_event_flow cef,cic.cic_flow_version cfv
       where cef.event_flow_id = cfv.event_flow_id
       and cef.state = 'A'
       and cfv.state = 'D' "

  Check_cic_flow_name_special_characters:
    des: 检查CIC中的flow的名字中是否有特殊字符，如果有会导致WSO2有问题（来自TM常钟瑞）
    area: A028
    sql:
      "SELECT * FROM CIC_MSG_TEMPLATE 
       WHERE 
       TEMPLATE_NAME LIKE 'evSMSOutTaaS%' 
       AND (
        TEMPLATE_NAME LIKE '%/%' 
        OR TEMPLATE_NAME LIKE '%&%' 
        OR TEMPLATE_NAME LIKE '%#%'
        OR TEMPLATE_NAME LIKE '%/%')"

