UserList:
  ftf

ErrorData:
  bfm_staff_cc_minus_crm:
    des: 查看cc库的bfm_staff比crm库的数据是否有异常
    area: comm
    sql:
      "select staff_id,staff_name,staff_code from cc.bfm_staff
        minus
        select staff_id,staff_name,staff_code from crm.bfm_staff"

  bfm_staff_crm_minus_cc:
    des: 查看crm库的bfm_staff比cc库的数据是否有异常
    area: comm
    sql:
      "select staff_id,staff_name,staff_code from crm.bfm_staff
        minus
        select staff_id,staff_name,staff_code from cc.bfm_staff"

  bfm_staff_no_job:
    des: 查看staff没有job的数据
    area: comm
    sql:
      "SELECT * FROM bfm_staff where staff_id not in (SELECT staff_id from bfm_staff_job )"

  Missing some priv in role:
    des: 查找出来2个Role，有没有权限缺失的情况
    area: A016
    sql:
      "SELECT * FROM bfm_priv where priv_id not in (SELECT priv_id from bfm_role_priv where ROLE_ID in (1,7037)) and state ='A'"

  bfm_staff_ftf_minus_cc:
    des: 查看ftf库的bfm_staff比cc库的数据是否有异常
    area: A016
    sql:
      "select staff_id,staff_name,staff_code from bfm_staff where STAFF_ID>1000 and staff_id <100000
        minus
        select staff_id,staff_name,staff_code from cc.bfm_staff where STAFF_ID>1000 and staff_id <100000"

  bfm_user_no_role:
    des: 查看ftf库中的user是否有role异常
    area: A016
    sql:
      "SELECT * FROM ftf.bfm_user where user_id not in (SELECT user_id from ftf.bfm_user_role ) and user_id >1000 and user_id <100000 and state='A'"

BadData:
  Individual price plan do not relate to tariff plan:
    des: 个性化资费计划没有关联tariff plan
    area: comm
    sql:
      "select *
            from cpc.price_plan d
            where state='B'  and d.price_plan_type='3'
            and not exists (select b.price_plan_id
                from
                    cpc.tariff_plan a,
                    cpc.tariff_plan_rela b
                where a.tariff_plan_id=b.tariff_plan_id
                        and b.price_plan_id=d.price_plan_id
                        and a.state='B'
                        and b.state='B'
                )
            and d.price_plan_id not in (-10,11000,12300,12500,12600,15000,17200,18200,16105)"

