UserList:
  pcc

param_list:
  WarningData:
    cpc_user_name:
      pcc
  BadData:
    cpc_user_name:
      pcc
  ErrorData:
    cpc_user_name:
      pcc

#pcrf check sql
WarningData:

BadData:

ErrorData:
    Check the attribute used in PCRF workflow condition are not defined on the PCRF side:
      #检查PCRF workflow的条件中引用的属性是否在PCRF侧已经定义
      des: 检查PCRF workflow的条件中引用的属性是否在PCRF侧已经定义
      area: A011
      sql:
        "select t.work_group_id,t.work_group_name,t1.work_node_id,t1.work_node_name,t3.re_attr,t3.r_re_attr 
         from pcc.pcc_work_group t,pcc.pcc_work_node t1,pcc.pcc_work_condition_group t2,pcc.pcc_work_condition t3
         where t.work_group_id=t1.work_group_id
         and t1.work_node_id=t2.work_node_id
         and t2.work_cond_group_id=t3.work_cond_group_id
         and (t3.re_attr not in (select a.re_attr from pcc.pcc_re_attr a) or t3.r_re_attr not in (select a1.re_attr from pcc.pcc_re_attr a1))"

    Check the attribute used in PCRF workflow action are not defined on the PCRF side:
      #检查PCRF workflow的action中引用的属性是否在PCRF侧已经定义
      des: 检查PCRF workflow的action中引用的属性是否在PCRF侧已经定义
      area: A011
      sql:
        "select t.work_group_id,t.work_group_name,t1.work_node_id,t1.work_node_name,t2.src_re_attr,t2.obj_re_attr
         from pcc.pcc_work_group t,pcc.pcc_work_node t1,pcc.pcc_work_action t2
         where t.work_group_id=t1.work_group_id
         and t1.work_node_id=t2.work_node_id
         and (t2.src_re_attr not in (select a.re_attr from pcc.pcc_re_attr a) or t2.obj_re_attr not in (select a1.re_attr from pcc.pcc_re_attr a1))"

NOUSE:
