ParameterTable:
  dst_table:
    - cpc.param_define
    - cpc.table_param
    - cpc.table_param_column
    - cpc.table_param_cell

  mid_table:
    - DC_CONFIG_PP_TABLE_PARAMETER
    - DC_CONFIG_PP_TABLE_PARAMETER_TARIFF

  insert_parameter_table:
    - |
      exec:DC_PROC_PARAM_TABLE