ParameterTableUsage:
  dst_table:
    - cpc.REF_VALUE
    - cpc.PRICE_WORK_NODE
    - cpc.PRICE
    - cpc.ACTION_PRICE
    - cpc.WORK_ACTION
    - cpc.WORK_NODE
    - cpc.PRICE_VER
    - cpc.MAPPING
    - cpc.RATE_PLAN_ZONE
    - cpc.RATE_PLAN
    - cpc.RE_PRICE_SET
    - DC_CONFIG_PP_USAGE_PARAMETER_LOG

  mid_table:
    - DC_CONFIG_PP_USAGE_PARAMETER

  insert_parameter_table:
    - |
      exec:DC_PROC_TABLE_PARAM_PRICE