SICGOODS:
  dst_table:
    - sic.ic_gm_spu
    - sic.ic_gm_spu_mvno
    - sic.IC_GM_SPU_ATTR_VALUE
    - sic.IC_GM_MODEL
    - cpc.ATTR_VALUE
    - sic.IC_GM_CATG_ATTR_GROUP
    - sic.IC_GM_CATG_ATTR
    - sic.IC_GM_CATG_SPEC
    - sic.IC_GM_MODEL_ATTR_VALUE
    - sic.IC_GM_GOODS_CATG
    - sic.IC_GM_BRAND
    - sic.IC_GM_VENDOR
    - sic.IC_GM_GOODS_CATG_MVNO

  mid_table:
    - DC_IC_GM_SPU
    - DC_IC_GM_SPU_ATTR_VALUE
    - DC_IC_GM_MODEL
    - DC_ATTR_VALUE
    - DC_IC_GM_CATG_ATTR_GROUP
    - IC_GM_GOODS_CATG
    - DC_IC_GM_BRAND
    - DC_IC_GM_VENDOR
    - DC_IC_GM_CATG_ATTR
    - DC_IC_GM_CATG_SPEC
    - DC_IC_GM_MODEL_ATTR_VALUE

  insert_DC_IC_GM_SPU:
    - |
        insert into sic.ic_gm_spu
          (SPU_ID,
           SPU_NAME,
           STOCK_TYPE,
           SPU_CODE,
           GOODS_CATG_ID,
           INTRO,
           COMMENTS,
           BRAND_ID,
           CREATED_DATE,
           CREATED_STAFF,
           UPDATE_DATE,
           UPDATE_STAFF,
           STATE,
           STATE_DATE,
           GOODS_MAIN_CLASS,
           GOODS_SUBCLASS)
          select sic.spu_id_seq.nextval,
                 d.spu_name,
                 case upper(d.STOCK_TYPE) when 'INSTANCE' then 'I' when 'QUANTITY' then 'N' else 'I' end,
                 d.spu_code,
                 ig.goods_catg_id,
                 '',
                 '',
                 b.brand_id,
                 sysdate,
                 '',
                 '',
                 '',
                 'A',
                 sysdate,
                 nvl(ig.parent_goods_catg_id,ig.goods_catg_id),
                 null
            from cpc.DC_IC_GM_SPU d
            left join sic.ic_gm_brand b
              on d.brand_name = b.brand_name
            left join sic.ic_gm_goods_catg ig
              on ig.goods_catg_name = d.spu_group_name
            left join sic.IC_GM_SPU u on d.spu_code = u.spu_code where u.spu_code is null
    - |
        insert into sic.ic_gm_spu_mvno
          (spu_id, sp_id)
          select spu_id, 0
            from cpc.DC_IC_GM_SPU d1
            inner join sic.ic_gm_spu u on u.SPU_NAME = d1.SPU_NAME
            inner join sic.ic_gm_goods_catg c on c.GOODS_CATG_NAME = d1.SPU_GROUP_NAME and u.GOODS_CATG_ID = c.GOODS_CATG_ID
            left join sic.ic_gm_spu_mvno m on m.SPU_ID = u.SPU_ID
             where m.SP_ID is null;

  insert_DC_IC_GM_SPU_ATTR_VALUE:
    - |
        insert into sic.IC_GM_SPU_ATTR_VALUE
          (SPU_ID,
           FEATURE_ID,
           GROUP_ID,
           ATTR_ID,
           DEFAULT_VALUE,
           UNIT_ID,
           DISPLAY_ORDER)
          select i.spu_id,
                           null,
                           pa.group_id,
                           a.attr_id,
                           t.attr_value,
                           null,
                           ca.display_order
                      from DC_IC_GM_SPU_ATTR_VALUE t
                      inner join sic.ic_gm_spu i
                        on t.spu_name = i.spu_name
                      inner join cpc.attr_spec a
                        on t.ATTR_NBR = a.attr_nbr
                      inner join sic.IC_GM_CATG_ATTR_GROUP pa
                        on pa.group_name = t.group_name and i.GOODS_CATG_ID = pa.GOODS_CATG_ID
                      inner join sic.IC_GM_CATG_ATTR ca on ca.ATTR_ID = a.ATTR_ID and ca.GROUP_ID = pa.GROUP_ID
                      left join sic.IC_GM_SPU_ATTR_VALUE ia
                      on ia.spu_id = i.spu_id and a.attr_id = ia.attr_id and ia.DISPLAY_ORDER = t.DISPLAY_ORDER and t.attr_value = ia.default_value
                      where ia.spu_id is null ;

  insert_DC_IC_GM_MODEL:
    - |
        insert into sic.IC_GM_MODEL
          (MODEL_ID,
           MODEL_NAME,
           SPU_ID,
           MODEL_CODE,
           MODEL_UNIT_ID,
           IS_DUMMY_ESN,
           META_KEYWORDS,
           META_DESCRIPTION,
           WARRANTY_LIMIT,
           WARRANTY_PERIOD,
           MIN_SALE_PRICE,
           MAX_SALE_PRICE,
           COST,
           THUMBNAIL,
           WEIGHT,
           BRIEF,
           CREATED_DATE,
           CREATED_STAFF,
           UPDATE_DATE,
           UPDATE_STAFF,
           STATE,
           STATE_DATE,
           PACKAGE_INFO,
           SP_ID,
           CURRENCY_TYPE_ID,
           LIST_PRICE)
          select sic.model_id_seq.nextval,
                 d.sku_name,
                 i.spu_id,
                 d.sKu_code,
                 1,
                 'N',
                 null,
                 null,
                 null,
                 null,
                 null,
                 null,
                 null,
                 null,
                 null,
                 null,
                 sysdate,
                 null,
                 sysdate,
                 null,
                 'A',
                 sysdate,
                 null,
                 0,
                 10020,
                 null
            from cpc.DC_IC_GM_MODEL d
            left join sic.IC_GM_SPU i
              on i.spu_name = d.spu_name
             left join sic.IC_GM_MODEL m on m.MODEL_CODE = d.sku_code where m.MODEL_CODE is null;

  insert_DC_ATTR_VALUE:
    - |
      insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, ATTR_DESC, ATTR_VALUE_CD, ATTR_VALUE_CODE, EXT_ATTR_VALUE_ID, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, VALUE_NUMBER, GRP_ATTR_VALUE_NBR)
      select  cpc.seq_attr_value.nextval,
             a.ATTR_ID, t.ATTR_VALUE_NAME, t.ATTR_VALUE_NAME, sysdate, null, t.ATTR_VALUE, '1000', sysdate, 1965868, null, t.ATTR_VALUE_SORT, null, null, null, t.ATTR_VALUE_CODE, null, null, null, null, null, null, null, null
      from DC_ATTR_VALUE t inner join cpc.attr_spec a on t.ATTR_NBR = a.ATTR_NBR
      left join cpc.attr_value v on v.ATTR_VALUE = t.ATTR_VALUE and v.ATTR_ID = a.ATTR_ID where v.ATTR_VALUE is null;

  insert_DC_IC_GM_CATG_ATTR_GROUP:
      - |
          INSERT INTO sic.IC_GM_CATG_ATTR_GROUP (GROUP_ID, GOODS_CATG_ID, GROUP_NAME, CREATED_DATE, DISPLAY_ORDER)
          select t.GROUP_ID,c.GOODS_CATG_ID,t.GROUP_NAME,sysdate,t.DISPLAY_ORDER from DC_IC_GM_CATG_ATTR_GROUP t
              inner join sic.IC_GM_GOODS_CATG c on c.GOODS_CATG_NAME = t.GOODS_CATG_NAME
              left join sic.IC_GM_CATG_ATTR_GROUP g on c.GOODS_CATG_ID = g.GOODS_CATG_ID and g.GROUP_NAME = t.GROUP_NAME
          where g.GROUP_ID is null;

  insert_DC_IC_GM_CATG_ATTR:
      - |
          INSERT INTO SIC.IC_GM_CATG_ATTR (GROUP_ID, ATTR_ID, ATTR_NAME, FEATURE_ID, FEATURE_NAME, ATTR_INPUT_TYPE, DISPLAY_ORDER, CREATED_DATE)
          select g.GROUP_ID,s.ATTR_ID,s.ATTR_NAME,null,null,s.ATTR_VALUE_TYPE,t.DISPLAY_ORDER,sysdate from DC_IC_GM_CATG_ATTR t
              inner join cpc.ATTR_SPEC s on s.ATTR_NBR = t.ATTR_NBR
              inner join sic.IC_GM_GOODS_CATG c on t.GOODS_CATG_NAME = c.GOODS_CATG_NAME
              inner join sic.IC_GM_CATG_ATTR_GROUP g on g.GOODS_CATG_ID = c.GOODS_CATG_ID and g.GROUP_NAME = t.GROUP_NAME
          left join sic.IC_GM_CATG_ATTR a on a.GROUP_ID = g.GROUP_ID and a.ATTR_ID = s.ATTR_ID where a.ATTR_ID is null;

  insert_DC_IC_GM_CATG_SPEC:
      - |
          INSERT INTO SIC.IC_GM_CATG_SPEC (GOODS_CATG_ID, ATTR_ID, ATTR_NAME, FEATURE_ID, FEATURE_NAME, ATTR_INPUT_TYPE, DISPLAY_ORDER, CREATED_DATE)
          select c.GOODS_CATG_ID,s.ATTR_ID,s.ATTR_NAME,null,null,s.ATTR_VALUE_TYPE,t.DISPLAY_ORDER,sysdate from DC_IC_GM_CATG_SPEC t
                        inner join cpc.ATTR_SPEC s on s.ATTR_NBR = t.ATTR_NBR
                        inner join sic.IC_GM_GOODS_CATG c on t.GOODS_CATG_NAME = c.GOODS_CATG_NAME
                    left join sic.IC_GM_CATG_SPEC a on a.GOODS_CATG_ID = c.GOODS_CATG_ID and a.ATTR_ID = s.ATTR_ID where a.ATTR_ID is null;

  insert_DC_IC_GM_MODEL_ATTR_VALUE:
      - |
          INSERT INTO SIC.IC_GM_MODEL_SPEC_VALUE (MODEL_ID, FEATURE_ID, ATTR_ID, ATTR_VALUE_ID, SPEC_VALUE, SPEC_VALUE_MARK, DISPLAY_ORDER, UNIT_ID)
          select gm.MODEL_ID,null, s.ATTR_ID, v.ATTR_VALUE_ID,v.ATTR_VALUE_NAME,v.ATTR_VALUE_DESC, cs.DISPLAY_ORDER,null
              from DC_IC_GM_MODEL_ATTR_VALUE t
                  inner join sic.IC_GM_MODEL gm on gm.MODEL_NAME = t.SKU_NAME
                  inner join sic.IC_GM_SPU u on gm.SPU_ID = u.SPU_ID
                  inner join cpc.ATTR_SPEC s on s.ATTR_NBR = t.ATTR_NBR
                       inner join cpc.ATTR_VALUE v on v.ATTR_VALUE = t.ATTR_VALUE and v.ATTR_ID = s.ATTR_ID
                  inner join sic.IC_GM_CATG_SPEC cs on cs.GOODS_CATG_ID = u.GOODS_CATG_ID and cs.ATTR_ID = s.ATTR_ID
                       left join sic.IC_GM_MODEL_SPEC_VALUE m
                                 on gm.MODEL_ID = m.MODEL_ID and m.ATTR_ID = s.ATTR_ID and m.ATTR_VALUE_ID = v.ATTR_VALUE_ID
              where m.ATTR_VALUE_ID is not null

  insert_DC_IC_GM_GOODS_CATG:
      - |
          insert into sic.IC_GM_GOODS_CATG(goods_catg_id, goods_catg_name, parent_goods_catg_id, goods_count, image, cat_order, created_date, created_staff, update_date, update_staff, state, state_date)
          select sic.GOODS_CATG_ID_SEQ.nextval,
                 t.GOODS_CATG_NAME,pa.GOODS_CATG_ID,null,null,t.CAT_ORDER,sysdate,'3044336',sysdate,null,'A',sysdate
                 from DC_IC_GM_GOODS_CATG t inner join sic.IC_GM_GOODS_CATG pa on pa.GOODS_CATG_NAME = t.PARENT_GOODS_CATG_NAME
          left join sic.IC_GM_GOODS_CATG ca on ca.GOODS_CATG_NAME = t.GOODS_CATG_NAME
          where ca.GOODS_CATG_NAME is null;

      - |
          insert into sic.IC_GM_GOODS_CATG_MVNO (GOODS_CATG_ID,sp_id)
          select c.GOODS_CATG_ID, 0
                      from sic.IC_GM_GOODS_CATG c
                      left join sic.IC_GM_GOODS_CATG_MVNO m on c.GOODS_CATG_ID = m.GOODS_CATG_ID and c.GOODS_CATG_ID > 0
                       where m.GOODS_CATG_ID is null;

  insert_DC_IC_GM_VENDOR:
      - |
          insert into sic.IC_GM_VENDOR(VENDOR_ID, VENDOR_NAME, VENDOR_CODE) SELECT t.VENDOR_ID,t.VENDOR_NAME,t.VENDOR_CODE from DC_IC_GM_VENDOR t
          left join sic.IC_GM_VENDOR v on v.VENDOR_NAME = t.VENDOR_NAME where v.VENDOR_CODE is null;


  insert_DC_IC_GM_BRAND:
      - |
          insert into sic.IC_GM_BRAND(BRAND_ID, LOGO, URL, BRIEF, VENDOR_ID, BRAND_NAME, COMMENTS, BRAND_CODE)
          SELECT t.BRAND_ID,null,null,null,v.VENDOR_ID,t.BRAND_NAME,null,t.BRAND_CODE from DC_IC_GM_BRAND t inner join sic.IC_GM_VENDOR v on v.VENDOR_CODE = t.VENDOR_CODE
          left join sic.IC_GM_BRAND b on b.BRAND_NAME = t.BRAND_NAME where b.BRAND_NAME is null;