delete:
    DC_price_check_result_selftab:
        delete from DC_price_check_result_selftab


#insert into middle table
insert_result_tab:
    insert into DC_PRICE_CHECK_RESULT_SELFTAB (check_file_name,check_group,check_item,check_sql,check_result,check_topic)
    values (:1,:2,:item,:sql,:result,:check_topic)

export_result:
    DC_PRICE_CHECK_RESULT_SELFTAB:
        select check_file_name as file_name,
        check_group as topic_name,
        check_item as title_name,
        check_sql as sql_content,
        case when check_result = 0 then 'success' else 'fail' end as result,
        check_result as error_count,
        to_char(create_date,'yyyy/mm/dd hh24:mi:ss') as check_time
        from DC_PRICE_CHECK_RESULT_SELFTAB
        where check_topic = %(check_type)s
        and check_file_name = %(file_name)s
        and check_group = %(topic)s
        and check_item = %(title)s
        and check_result <> %(only_failed)s

check_title_all_list:
    AcctItem_No_Define:
        des: AcctItem_No_Define
        topic: BadData
        area: comm

    AcctItem_No_Define_ErrorData:
        des: AcctItem_No_Define_ErrorData
        topic: ErrorData
        area: comm

    AcmAcctItem_RefValue_Error:
        des: AcmAcctItem_RefValue_Error
        topic: BadData
        area: comm

    AcmAcctItem_RefValueId_NotExists:
        des: AcmAcctItem_RefValueId_NotExists
        topic: ErrorData
        area: comm

    AcmTemplet_No_Catalog:
        des: AcmTemplet_No_Catalog
        topic: BadData
        area: comm

    AcmValue_RefValue_Error:
        des: AcmValue_RefValue_Error
        topic: BadData
        area: comm

    AcmValue_RefValueId_NotExists:
        des: AcmValue_RefValueId_NotExists
        topic: ErrorData
        area: comm

    BenefitTemplet_No_Catalog:
        des: BenefitTemplet_No_Catalog
        topic: BadData
        area: comm

    BenefitValue_RefValueId_NotExists:
        des: BenefitValue_RefValueId_NotExists
        topic: ErrorData
        area: comm

    EventBenefit_RefValue_Error:
        des: EventBenefit_RefValue_Error
        topic: BadData
        area: comm

    IndepProdSpec_No_Migration:
        des: IndepProdSpec_No_Migration
        topic: ErrorData
        area: comm

    IndepProdSpec_No_Migration_Zone:
        des: IndepProdSpec_No_Migration_Zone
        topic: ErrorData
        area: comm

    Offer_No_Offer_Ver:
        des: Offer_No_Offer_Ver
        topic: BadData
        area: comm

    OneACMPriceTemplet_Mapping_Muti_Re:
        des: OneACMPriceTemplet_Mapping_Muti_Re
        topic: ErrorData
        area: comm

    OneBenefitPriceTemplet_Mapping_Muti_Re:
        des: OneBenefitPriceTemplet_Mapping_Muti_Re
        topic: ErrorData
        area: comm

    OneRatePlan_Mapping_Muti_Re:
        des: OneRatePlan_Mapping_Muti_Re
        topic: ErrorData
        area: comm

    OneScriptTemplet_Mapping_Muti_ReType:
        des: OneScriptTemplet_Mapping_Muti_ReType
        topic: ErrorData
        area: comm

    Price_and_RatePlan_Re_NotMatch:
        des: 检查资费模板和真正的资费的对应的事件是否一致
        topic: BadData
        area: comm

    PricePlan_No_Offer:
        des: PricePlan_No_Offer
        topic: BadData
        area: comm

    PricePlan_Offer_No_Price_Plan:
        des: PricePlan_Offer_No_Price_Plan
        topic: BadData
        area: comm

    PricePlan_Re_No_Reserve:
        des: PricePlan_Re_No_Reserve
        topic: BadData
        area: comm

    PriceTemplate_No_Catalog:
        des: PriceTemplate_No_Catalog
        topic: BadData
        area: comm

    PriceTemplate_One_Mapping_Multi_Re:
        des: 一个模板被多个Rate_plan所引用，但是Re_id不一样
        topic: BadData
        area: comm

    PriceValue_RefValue_Error:
        des: PriceValue_RefValue_Error
        topic: BadData
        area: comm

    PriceValue_RefValueId_NotExists:
        des: PriceValue_RefValueId_NotExists
        topic: ErrorData
        area: comm

    ProdSpec_No_Migration:
        des: ProdSpec_No_Migration
        topic: ErrorData
        area: comm

    PriceVer_No_Use:
        des: PriceVer_No_Use
        topic: BadData
        area: comm

    RatePlan_No_PriceVer:
        des: RatePlan_No_PriceVer
        topic: BadData
        area: comm

    RatePlan_OfferVer_Re_Err:
        des: RatePlan_OfferVer_Re_Err
        topic: ErrorData
        area: comm

    RatePlanTemplet_No_Catalog:
        des: RatePlanTemplet_No_Catalog
        topic: BadData
        area: comm

    RefValue_No_OfferVerId:
        des: RefValue_No_OfferVerId
        topic: BadData
        area: comm

    RefValue_No_PriceId:
        des: RefValue_No_PriceId
        topic: BadData
        area: comm

    RefValue_No_RatePlanId:
        des: RefValue_No_RatePlanId
        topic: BadData
        area: comm

    RefValueToOfferVer_No_OfferVerId:
        des: RefValueToOfferVer_No_OfferVerId
        topic: BadData
        area: comm

    RefValueToOfferVer_NoUse_RefValue:
        des: RefValueToOfferVer_NoUse_RefValue
        topic: BadData
        area: comm

    RefValueToOfferVer_MissSomeData:
        des: RefValueToOfferVer_MissSomeData
        topic: BadData
        area: comm

    RePricePlan_No_RatePlanMapping:
        des: RePricePlan_No_RatePlanMapping
        topic: BadData
        area: comm

    ReReserve_Policy_No_Limit:
        des: ReReserve_Policy_No_Limit
        topic: ErrorData
        area: comm

    ScriptTemplet_No_Catalog:
        des: ScriptTemplet_No_Catalog
        topic: BadData
        area: comm

    SortRule_Not_Output_Re_Have_Tariff:
        des: 检查配置了资费，但是没有分拣的
        topic: BadData
        area: comm

    SortRule_OutputRe_No_Reserve:
        des: 分拣分拣出了事件，但是在预留规则中没有配置预留
        topic: BadData
        area: comm

    SortRule_OutputRe_No_Tariff:
        des: SortRule_OutputRe_No_Tariff
        topic: ErrorData
        area: comm

    TempletAcm_No_Use:
        des: TempletAcm_No_Use
        topic: BadData
        area: comm

    TempletAcmAcctItem_RefValue_Error:
        des: TempletAcmAcctItem_RefValue_Error
        topic: BadData
        area: comm

    TempletAcmValue_RefValue_Error:
        des: TempletAcmValue_RefValue_Error
        topic: BadData
        area: comm

    TempletEventBenefit_No_Use:
        des: TempletEventBenefit_No_Use
        topic: BadData
        area: comm

    TempletEventBenefit_RefValue_Error:
        des: TempletEventBenefit_RefValue_Error
        topic: BadData
        area: comm

    TemplateRatePlan_No_RatePlanMapping:
        des: TemplateRatePlan_No_RatePlanMapping
        topic: ErrorData
        area: comm

    TemplateRatePlan_No_Use:
        des: TemplateRatePlan_No_Use
        topic: BadData
        area: comm

    TemplateRatePlan_OfferVerId_Error:
        des: TemplateRatePlan_OfferVerId_Error
        topic: ErrorData
        area: comm

    TempletPrice_No_Use:
        des: TempletPrice_No_Use
        topic: BadData
        area: comm

    TempletPriceValue_RefValue_Error:
        des: TempletPriceValue_RefValue_Error
        topic: BadData
        area: comm


    The re_attr of reservation rule is different with the re_attr configured in price plan:
        des: 事件配置的预留规则与资费里配置的扣费单位不一致，比如预留配置的是秒，但是扣费是按次扣费
        topic: BadData
        area: comm

    Zone_same_zone_id_multiple_value:
        des: 一个zone map下，同一个zone里存在多条相同的value值
        topic: BadData
        area: comm

    Zone Same zone value exists in different zone:
        des: 检查一个zone map下一个zone value同时存在不同的zone里
        topic: ErrorData
        area: comm

    ZoneId_No_Migration:
        des: ZoneId_No_Migration
        topic: ErrorData
        area: comm