Oracle:
  get_seq: |
    select sequence_owner,
           sequence_name,
           min_value,
           max_value,
           increment_by,
           cycle_flag,
           order_flag,
           cache_size,
           last_number,
           scale_flag,
           extend_flag,
           session_flag,
           keep_value
      from dba_sequences
     where sequence_owner = upper(:DB_USER)
       and sequence_name = upper(:SEQ_NAME)

  check_table_exists:
    select count(1) from all_tables where owner = upper(:DB_USER) and table_name = upper(:TABLE_NAME)

  drop_seq: drop sequence %(DB_USER)s.%(SEQ_NAME)s

  create_seq: |
    create sequence %(SEQUENCE_OWNER)s.%(SEQUENCE_NAME)s
    minvalue %(MIN_VALUE)s
    maxvalue %(MAX_VALUE)s
    start with %(NEW_VALUE)s
    increment by %(INCREMENT_BY)s
    cache %(CACHE_SIZE)s
