UserList:
  cpc

CPC Topic:
  7. OTC:
    "select a.offer_id,'benfit' as 'type','' as 'acct_item_type_id','' as 'acct_item_type', b.ACCT_RES_ID, c.acct_res_name, b.VALUE
     from CPC_OTC_PRICE a, CPC_OTC_PRICE_BENEFIT b, cbec_acct_res c
     where a.price_id = b.PRICE_ID
     and b.acct_res_id = c.acct_res_id
     union all
     select a.offer_id, 'Rate' as 'type',b.acct_item_type_id as 'acct_item_type_id',c.acct_item_type_name,c.acct_res_id, d.acct_res_name,b.VALUE
     from cpc_otc_price a, CPC_OTC_PRICE_RATE b, cbec_acct_item_type c, cbec_acct_res d
     where a.PRICE_ID = b.price_id
     and b.ACCT_ITEM_TYPE_ID = c.ACCT_ITEM_TYPE_ID
     and c.acct_res_id = d.acct_res_id"

  19. Offer And Tarriff Plan:
    "select * from offer_price"

  20. Tarriff Plan:
    "SELECT
         a.TARIFF_PLAN_ID,a.tariff_plan_name,a.Active_date,
         d.param_id,d.label_name,d.PARAM_VALUE,c.price_plan_id,c.price_plan_name
     FROM
         TARIFF_PLAN a,
         TARIFF_PLAN_RELA b,
         price_plan c,
         TARIFF_PLAN_PARAM d
     WHERE
         a.tariff_plan_id >= 10000
             AND a.TARIFF_PLAN_ID = b.TARIFF_PLAN_ID
             AND b.price_plan_id = c.price_plan_id
             AND a.TARIFF_PLAN_ID = d.TARIFF_PLAN_ID
             AND c.price_plan_id = d.price_plan_id
     ORDER BY a.tariff_plan_name , c.price_plan_name , d.LABEL_NAME"

  30. Globel Price Plan:
    "select a.price_plan_id, a.price_plan_name,a. priority,a.Active_date, e.re_id,e.re_name, f.rate_plan_id,f.rate_plan_name, g.mapping_id, g.mapping_name,i.price_id, i.price_name, j.con_res_id,j.con_res_name
     from price_plan a, price_plan_ver b, price_plan_member c , re_price_set d, re e, rate_plan f, mapping g, price_ver h, price i , con_res j, ref_value k
     where a.price_plan_id >10000
     and a.state ='B'
     and a.price_plan_type = 1
     and a.price_plan_id = b.PRICE_PLAN_ID
     and b.price_plan_ver_id = c.price_plan_ver_id
     and c.price_set_id = d.price_set_id
     and d.re_id = e.re_id
     and d.re_price_set_id = f.re_price_set_id
     and f.rate_plan_type = 1
     and f.rate_plan_id = g.rate_plan_id
     and g.mapping_id = h.mapping_id
     and h.price_ver_id = i.price_ver_id
     and i.price_id = k.price_id
     and k.ref_value_type = 9
     and k.value_string = j.con_res_id
     order by a.priority"

  31. Indivual Price Plan:
    "select pp.PRICE_PLAN_ID,
      pp.price_plan_name,
      pp.priority,
      ppv.PRICE_PLAN_VER_ID,
      ppm.PRICE_SET_ID,
      r.re_id,
      r.RE_NAME,
      rps.RE_PRICE_SET_ID,
      rp.RATE_PLAN_ID,
      rp.RATE_PLAN_NAME,
      m.MAPPING_ID,
      pv.PRICE_VER_ID,
      p.PRICE_ID,
      p.PRICE_NAME,
      eb.PRICE_ID event_benefit_price_id,
      eb.PRICE_NAME event_benefit_name,
      ber.RULE_NAME,
      cr.con_res_id,
      cr.con_res_name
      from price_plan pp,
      price_plan_ver ppv,
      price_plan_member ppm,
      re_price_set rps,
      re r,
      rate_plan rp,
      mapping m,
      con_res cr,
      price_ver pv
      left join price p on pv.PRICE_VER_ID = p.PRICE_VER_ID
      left join ref_value rv  on p.price_id= rv.price_id and rv.ref_value_type = 9
      left join bal_event_rule ber on pv.PRICE_VER_ID = ber.PRICE_VER_ID
      left join event_benefit eb on eb.PRICE_VER_ID = pv.PRICE_VER_ID
      where  pp.price_plan_id >=10000
      and pp.state = 'B'
      and pp.PRICE_PLAN_ID = ppv.PRICE_PLAN_ID
      and ppv.PRICE_PLAN_VER_ID = ppm.PRICE_PLAN_VER_ID
      and ppm.PRICE_SET_ID = rps.PRICE_SET_ID
      and rps.RE_ID = r.re_id
      and rps.RE_PRICE_SET_ID = rp.RE_PRICE_SET_ID
      and rp.RATE_PLAN_ID = m.RATE_PLAN_ID
      and m.MAPPING_ID = pv.MAPPING_ID
      and rv.value_string = cr.con_res_id
      order by r.re_id,rp.RATE_PLAN_ID"

  33. Usage Event:
    "select a.re_id, a.re_name, a.re_code, b.parent_re_id,a.comments
     from re a, re_usage b
     where a.re_id=b.re_id
     and a.re_type=1"

  37.Account Balance Type:
    "SELECT
    acct_res_id,
    acct_res_name,
    std_code,
    CASE bal_type
    WHEN '1' THEN 'Basic Balance'
    WHEN '2' THEN 'Limited Balance'
    WHEN '3' THEN 'Given Balance'
    WHEN '4' THEN 'Non Currency Balance'
    WHEN '5' THEN 'Bonus Balance'
    WHEN '6' THEN 'Credit Balance'
    ELSE 'other'
    END Balance_catalog,
    priority
    FROM
    CBEC_ACCT_RES
    WHERE
    acct_res_id >= 10000"

  39. Account Item Type:
    "select a.acct_item_type_id, a.acct_item_type_name, a.acct_item_type_code, b.acct_res_id, b.acct_res_name
     from CBEC_ACCT_ITEM_TYPE a, cbec_acct_res b
     where a.acct_res_id = b.ACCT_RES_ID
     and acct_item_type_id >10000"

  41. Consume Type:
    "select con_res_id Consume_Type_ID , con_res_name Consume_Type_Name, case bal_source_type when 4 then 'Non Currency' when 1  then 'Currency' end 'bal_type' from CON_RES where con_res_id>=10000"

  43. Consume& Account Item Type:
    "select a.con_res_id, a.con_res_name Consume_Type_Name, c.ACCT_ITEM_TYPE_NAME , d.acct_res_name, b.con_res_id, b.ACCT_ITEM_TYPE_ID,b.ACCT_RES_ID,b.PRIORITY
      from CON_RES a, CON_RES_DETAIL b, CBEC_ACCT_ITEM_TYPE c, cbec_acct_res d
      where a.CON_RES_ID = b.CON_RES_ID
      and b.acct_item_type_id = c.ACCT_ITEM_TYPE_ID
      and b.ACCT_RES_ID = d.ACCT_RES_ID
      and b.CON_RES_DETAIL_ID>10000"

  45. Reservation Rule:
    "select a.re_id,b.re_name,d.re_attr_name,a.value
     from reserve_policy a , re b, def_re_attr c, reserve_re_attr d
     where a.re_id = b.re_id
     and a.re_id >= 10000
     and a.re_attr=c.re_attr
     and c.def_re_attr = d.re_attr"

  93. Balance Event Rule:
    "select a.price_plan_id,a.price_plan_name, e.re_id,e.re_name, f.rate_plan_id,f.rate_plan_name, g.mapping_id, g.mapping_name, i.rule_name, i.rule
      from price_plan a, price_plan_ver b, price_plan_member c, re_price_set d, re e,rate_plan f, mapping g, price_ver h,bal_event_rule i
      where a.price_plan_id = b.price_plan_id
      and b.price_plan_ver_id = c.price_plan_ver_id
      and c.price_set_id = d.price_set_id
      and d.re_id = e.re_id
      and d.re_price_set_id = f.re_price_set_id
      and f.rate_plan_id = g.rate_plan_id
      and g.mapping_id = h.mapping_id
      and h.price_ver_id = i.price_ver_id"

  101. acct_item Tax:
    "select b.tax_code_map_rule_name,a.tax_std_code,a.tax_rate, c.tax_fact_val_grp_name,c.reverse_flag, d.tax_factor_name, f.acct_item_type_id, f.acct_item_type_name, g.tax_factor_name, b.tax_fact1_val
    from cbec_tax_code a, cbec_tax_code_map_rule b, cbec_tax_fact_val_grp c,cbec_tax_factor d, cbec_tax_fact_val_grp_map e, cbec_acct_item_type f, (select * from cbec_tax_factor where project_code=4141 ) as g
    where b.tax_code=a.tax_code
    and b.tax_fact2_val_grp_id = c.tax_fact_val_grp_id
    and c.tax_factor_id = d.tax_factor_id
    and c.tax_fact_val_grp_id=e.tax_fact_val_grp_id
    and e.tax_fact_value = f.acct_item_type_id
    and b.rule_priority = g.factor_priority
    order by b.tax_code_map_rule_id, c.tax_fact_val_grp_name"

  124. GL and AccoutItemType:
    "SELECT DISTINCT g.GL_ID, g.GL_CODE, g.GL_NAME, gt.GL_TYPE_NAME, ait.ACCT_ITEM_TYPE_ID, ait.ACCT_ITEM_TYPE_CODE, ait.ACCT_ITEM_TYPE_NAME
                FROM cbec_gl g, cbec_gl_acct_item_type gait, cbec_acct_item_type ait, cbec_gl_type gt
               WHERE g.GL_ID = gait.GL_ID
                 AND gait.ACCT_ITEM_TYPE_ID = ait.ACCT_ITEM_TYPE_ID
                 AND g.GL_TYPE_ID = gt.GL_TYPE_ID"

JournalExport:
  02. Account Item Type:
    "select a.acct_item_type_id, a.acct_item_type_name, a.acct_item_type_code, b.acct_res_id, b.acct_res_name
          from CBEC_ACCT_ITEM_TYPE a, cbec_acct_res b
          where a.acct_res_id = b.ACCT_RES_ID
          and acct_item_type_id >10000"

BoBNeed:
  06_CPC.CBEC_ACCT_ITEM_TYPE:
    "select * from cbec_ACCT_ITEM_TYPE"

  07_CPC.CBEC_BILLING_CYCLE:
    "select * from CBEC_BILLING_CYCLE"

  08_CPC.CBEC_BILLING_CYCLE_TYPE:
    "select * from CBEC_BILLING_CYCLE_TYPE"

  09_CPC.CBEC_ACCT_RES:
    "select * from CBEC_ACCT_RES"

  10_CPC.CBEC_CONTACT_CHANNEL:
    "select * from CBEC_CONTACT_CHANNEL"

  11_CPC.CBEC_DEPOSIT_TYPE:
    "select * from CBEC_DEPOSIT_TYPE"

  12_CPC.CBEC_PAYMENT_METHOD:
    "select * from CBEC_PAYMENT_METHOD"

  13_CPC.RE:
    "select * from RE"

  14_CPC.RE_TYPE:
    "select * from RE_TYPE"



