UserList:
  crm

CPC Topic:
  1.Independ Product:
    "SELECT
    a.offer_id,
    a.offer_name,
    a.offer_code,
    CASE b.paid_flag
    WHEN 'N' THEN 'Pre-paid'
    WHEN 'Y' THEN 'Post-paid'
    END Paid_flag
    FROM
    offer a,
    indep_prod_spec b
    WHERE
    a.offer_type = 2 AND a.offer_id > 100000
    AND a.offer_id = b.indep_prod_spec_id
    and a.state='A'"

  2. Depend Product:
    "select a.offer_id, a.offer_name, a.offer_code, c.SERV_TYPE, c.SERV_TYPE_NAME
    from offer a
    left join DEPEND_PROD_SPEC b on a.offer_id = b.DEPEND_PROD_SPEC_ID
    left join ALL_SERV_TYPE c on b.SERV_TYPE = c.serv_type
    where a.offer_type = 3
    and a.state='A'
    and a.offer_id > 100000
    and a.offer_id = b.DEPEND_PROD_SPEC_ID
    order by offer_Id"

  3. Offer:
    "SELECT
    a.offer_id,
    'Main Offer' AS 'offer_type',
    a.offer_name,
    a.Offer_code,
    a.eff_date,
    c.offer_name AS 'Independ Product'
    FROM
    offer a,
    subs_plan b,
    offer c
    WHERE
    a.offer_id >= 100000
    AND a.offer_type = 7
    AND a.offer_id = b.subs_plan_id
    AND b.indep_prod_spec_id = c.offer_id
    AND c.offer_id >= 100000
    AND c.offer_type = 2
    UNION ALL
    SELECT
    a.offer_id,
    'Additional Offer' AS 'offer_type',
    a.offer_name,
    a.Offer_code,
    a.eff_date,
    '' AS 'Independ Product'
    FROM
    offer a
    WHERE
    a.offer_id >= 100000 AND a.offer_type = 4"

  4. Offer And Addition Offer:
    "select a.offer_id,a.offer_name,'addition offer' as 'offer_type', f.offer_group_name,d.necessary,case f.Group_type when 'A' then 'Select All' when 'B' then 'Single Choice' when 'C' then 'Muti-Choice' end group_type,b.offer_id,b.offer_name
     from offer a, offer b, offer_ver c, SUBS_PLAN_OFFER_SELECT d, offer_group_mem e, offer_group f
     where a.offer_type=7
     and a.state='A'
     and b.state='A'
     and b.offer_type =4
     and a.offer_id = c.offer_id
     and c.offer_ver_id = d.offer_ver_id
     and d.offer_group_id = e.offer_group_id
     and e.offer_id = b.offer_id
     and e.offer_group_id = f. offer_group_id
     and a.offer_id >=100000"

  5. Offer&Product Relationship:
    "select a.ori_offer_id, b.offer_name, a.dest_offer_id, c.offer_name
     from offer_rela a, offer b, offer c
     where a.ori_offer_id=b.offer_id
     and a.dest_offer_id=c.offer_id
     and a.rela_type='H'
     and ori_offer_id >0
     order by ori_offer_id"

  8. Attribute:
    "select a.offer_id, b.offer_name, a.attr_id,c.attr_name, a.default_value
     from offer_attr a, offer b, attr c
     where a.offer_id>0
     and a.offer_id=b.offer_id
     and a.attr_id = c.attr_id"

BoBNeed:
  26_CRM.CSC_SERVICE_TYPE:
    "select * from CSC_SERVICE_TYPE"

  27_CRM.CSC_SOURCE:
    "select * from CSC_SOURCE"

  28_CRM.DEPEND_PROD_SPEC:
    "select * from DEPEND_PROD_SPEC"

  29_CRM.INDEP_PROD_SPEC:
    "select * from INDEP_PROD_SPEC"

  30_CRM.OFFER:
    "select * from OFFER"

  31_CRM.ATTACH_TYPE:
    "select * from ATTACH_TYPE"
  32_CRM.NP_OPERATOR:
    "select * from NP_OPERATOR"
  33_CRM.NP_ORDER_TYPE:
    "select * from NP_ORDER_TYPE"