# critical   >   error   >  warning  >   info     >   debug
#    debug     不限制
#    info      输出的全是带数据的内容
#    warning   表示风险，警告

version : 1
disable_existing_loggers : False
formatters :
    simple :
        format: "%(asctime)s [%(levelname)s] file:%(filename)s line:%(lineno)d: %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'
    verbose :
        format: "%(asctime)s [%(levelname)s] file:%(filename)s funcName:%(funcName)s line:%(lineno)d: %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers :
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: verbose
        filename: dctools.log
        maxBytes: 5242880
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: dctools_error.log
        maxBytes: 5242880
        backupCount: 20
        encoding: utf8

loggers :
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root :
    level: DEBUG
    handlers: [console, debug_file_handler,error_file_handler]
    propagate: true

#logPath: D:/iwhalecloud/pythonDevelop/DCTools/output/logs/