eventAttr:
    3: EVENT_TIME
    6: VPN_ID_KEY
    21: RE_ID
    22: BILLING_CYCLE_ID
    42: CHARGE1
    43: CHARGE2
    44: CHARGE3
    45: CHARGE4
    46: PRICE_ID
    47: PRICE_VER_ID
    66: BAL_ID1
    67: BAL_ID2
    68: BAL_ID3
    69: BAL_ID4
    72: OVERDUE_DAY
    73: CHARGE_AMOUNT
    75: OVERDUE_PLAN_ID
    81: RECHARGE_CARD_TYPE
    102: BILLING_CYCLE_BEGIN_DATE
    103: BILLING_CYCLE_END_DATE
    107: INDEP_PROD_SPEC_ID
    136: WVPN_SUBS_ID
    201: SUBS_ID
    203: AREA_ID
    204: PRICE_PLAN_CODE
    208: OLD_PROD_STATE
    209: BLOCK_REASON
    210: CONTACT_CHANNEL_ID
    211: OWE_EVENT_CHARGE_ACCT_ID
    212: EVENT_INST_ID
    213: RATING_SUBS_PRICE_PLAN_ID
    214: INSTALMENT_TYPE_ID
    215: RATING_SUBS_PRICE_PLAN_VER_ID
    228: ZONE_CODE
    242: OWE_EVENT_CHARGE_EVENT_TIME
    253: IS_SUPPORT_MULTI_BAL_DEDUCT
    255: EXTERNAL_PROLONG_DAYS
    260: DELAY_PERIOD_PROLONG_DAYS
    261: PROLONG_DAYS_KEY
    294: RECHARGE_CARD_IS_USED
    303: TRANSFER_PARNTER
    413: POSTPAID_OR_PREPAID_FLAG
    506: BENEFIT_REVENUE
    801: FELLOW_NBR_TYPE_IDS
    874: PRICE_PLAN_ID_LIST
    880: INDEP_PROD_ATTR
    881: SUBS_PRICE_PLAN_ID_LIST
    882: ACCT_PRICE_PLAN_ID_LIST
    883: OFFER_ID
    887: ABS_EFF_DATE_KEY
    888: ABS_EXP_DATE_KEY
    897: PRICE_PLAN_ID
    904: PRICE_ID_LIST
    905: BAL_ID_LIST
    906: CHARGE_LIST
    907: ACCT_RES_ID_LIST
    908: ACCT_ITEM_TYPE_ID_LIST
    915: EXT_CAL_FEE_PARAM
    916: EXT_CAL_FEE_PARAM_916
    950: ACCT_ITEM_TYPE_ID
    971: OWE_EVENT_CHARGE_ACCT_BOOK_ID
    978: ACTION_CODE
    987: SUBS_UPP_INST_ID
    990: IS_AGENT_RECHARGE
    991: ACM_RESOURCE_ID
    992: ACM_INCREMENT
    993: RECHARGE_CNT
    994: ACTIVE_DATE
    995: BILL_ID
    996: REMAIN_BAL
    998: INIT_BAL
    1000: ROUTING_ID
    1101: IS_PRE_RECHARGE
    1104: ACCT_RES_ID_KEY
    1105: TO_SUBS_TRANSFER_PERMIT
    1106: TRANSFER_TYPE_FLAG
    1115: VOUCHER_SEQ
    1119: LOAN_AMOUNT
    1120: LOAN_DATE
    1121: EXP_D2E_DATE
    1122: EXP_E2B_DATE
    1124: LOAN_FLAG
    1125: RECURRING_SERV_STD_CODE
    1126: TRANSFER_OUT_WITH_CREDIT_LIMIT_CONTROL
    1127: ACCT_PRICE_OR_SUBS_PRICE
    1128: DISCOUNT_CHARGE
    1129: DISCOUNT_RATE
    1130: NUMBER_GRADE
    1131: OLD_NUMBER_GRADE
    1133: INIT_BAL
    1134: TOTAL_SEQ
    1135: CONSUME_BAL_CHARGE
    1140: IS_RECORD_NULL_BENEFIT
    1200: FEE_ADVICE_TYPE
    1201: FEE_ADVICE_PARAM
    1218: PRESENT_INTERVAL_UNIT
    1219: PRESENT_INTERVAL_TIME
    1228: BAL_SHARE_ID1
    1229: BAL_SHARE_ID2
    1230: BAL_SHARE_ID3
    1231: BAL_SHARE_ID4
    1232: SHARE_MONTH_LIMIT
    1233: SHARE_DAY_LIMIT
    1234: ACCT_MONTH_LIMIT
    1235: ACCT_DAY_LIMIT
    1236: ABS_EFF_DATE_FOR_PRICE_PLAN
    1237: ABS_EXP_DATE_FOR_PRICE_PLAN
    1238: RECORD_KEY
    1239: RETURN_DISCOUNT_RATE
    1240: SUBS_PLAN_ID
    1316: ACM_OR_OVERWRITE
    1362: MATCHED_GEO_HOME_ZONE_CODE_LIST
    1363: MATCHED_GEO_HOME_ZONE_CATG_CODE_LIST
    1436: BAL_ABS_EXP_OFFSET
    1679: RESERVE_RE_PP_ID
    1680: RESERVE_RE_PP_CODE
    2000: PYTHON_RAISE_ERROR_CODE
    2222: EXT_PARAN_2222
    5000: DEPOSIT_TYPE_ID
    9999: RATE_PLAN_TYPE



attrValue:
    RATE_PLAN_TYPE: "1: BENEFIT, 2: RATING, 3: ACM, 4: DEPOSIT"