AVPMasterFileName: "avpfile-master.ini"

#将配置文件中配置的数据类型映射成代码内部的标准数据类型
DataTypeMap:
    #格式：配置文件中的DataType: 标准的DataType. 标准的DataType不能修改，依据配置文件中的DataType修改标签
    OctStr: OctetString
    INT32: Integer32
    INT64: Integer64
    UINT32: Unsigned32
    UINT64: Unsigned64
    Float32: Float32
    Float64: Float64
    Grouped: Grouped
    Address: Address
    Time: Time
    UTF8Str: UTF8String
    DccID: DiameterIdentity
    Enum: Enumerated

ResultCode:
    1001: "DIAMETER_MULTI_ROUND_AUTH     用于通知接入设备鉴权机制需要多轮往返，并且需要一个后续的请求来批准接入"
    2001: "DIAMETER_SUCCESS     请求被成功执行 "
    2002: "DIAMETER_LIMITED_SUCCESS    请求被成功执行，但是为了向用户提供服务，还需要额外的过程"
    2201: "FIRST_TIME_CALLING    第一次作主叫（激活储值卡）"
    2202: "BALANCE_HAVE_LITTLE_MONEY     主叫余额小于最小提醒额 "
    2203: "INDIVIDUAL_PAYMENT    您拨的电话号码需要个人付费,本次呼叫费用将计入您的个人帐户"
    2204: "MEMBER_ACCOUNT_FROZEN_CHARGED_TO_INDIVIDUAL_ACCOUNT      您的成员帐户被冻结，本次呼叫费用将计入您的个人帐户"
    2205: "MEMBERACCOUNT_REACHED_MONTHLY_LIMIT_CHARGED_TO_INDIVIDUAL_ACCOUNT      您的成员帐户月限额已到达，本次呼叫费用将计入您的个人帐户，但可以享受虚拟专网的优惠费率"
    2206: "FAV_CELLID_FLAG    优惠小区标志, 给 SCP 返回优惠小区标志，SCP 可放音通知用户"
    3001: "DIAMETER_COMMAND_UNSUPPORTED      无法识别或者不支持此命令码"
    3002: "DIAMETER_UNABLE_TO_DELIVER     消息无法发送到目的地，可能因为在域(realm)中找不到主机，或者是没有给出目的域(Destination-Realm)"
    3003: "DIAMETER_REALM_NOT_SERVED     请求的域(realm)无法识别 "
    3004: "DIAMETER_TOO_BUSY     指定的服务器无法提供指定的服务，Diameter 节点应该试图向备选端发送消息 "
    3005: "DIAMETER_LOOP_DETECTED     代理检测到环路 "
    3006: "DIAMETER_REDIRECT_INDICATION     发起者应该将请求直接发送到 Redirect-Host 中指定的服务器 "
    3007: "DIAMETER_APPLICATION_UNSUPPORTED    无法支持所要求的应用"
    3008: "DIAMETER_INVALID_HDR_BITS  消息头中的比特位组合无效，或者其值与命令码中的定义不一致"
    3009: "DIAMETER_INVALID_AVP_BITS    无法识别AVP 标志位，或者定义不一致"
    3010: "DIAMETER_UNKNOWN_PEER     从一个未知端收到CER 请求"
    4001: "DIAMETER_AUTHENTICATION_REJECTED     鉴权失败，极有可能由于无效密码"
    4002: "DIAMETER_OUT_OF_SPACE     由于暂时没有空间，无法确保稳定的存储"
    4003: "ELECTION_LOST    该端在选择过程中失败，因此断开了传输连接 "
    4010: "DIAMETER_END_USER_SERVICE_DENIED    OCF 根据业务相关限制或约束条件拒绝了业务请求，比如：终端用户帐户余额无法支付业务费用"
    4011: "DIAMETER_CREDIT_CONTROL_NOT_APPLICABLE    业务被允许但是无需进一步的信用控制（比如：免费业务）"
    4012: "DIAMETER_CREDIT_LIMIT_REACHED     由于终端用户的账户无法支付业务费用，其请求的业务被拒绝"
    5001: "DIAMETER_AVP_UNSUPPORTED    标有 M 比特位标记的AVP 无法被识别或支持，同时必须在 Failed-AVP 中携带导致失败的AVP"
    5002: "DIAMETER_UNKNOWN_SESSION_ID    未知的会话标识(Session-Id) "
    5003: "DIAMETER_AUTHORIZATION_REJECTED    用户未授权，或者业务不允许给用户使用"
    5004: "DIAMETER_INVALID_AVP_VALUE   AVP 包含无效数据，必须在 Failed-AVP 中携带违规的AVP "
    5005: "DIAMETER_MISSING_AVP   没有包含命令码定义中需要的AVP，应该在Failed-AVP 中携带缺失的AVP 和Vendor-ID "
    5006: "DIAMETER_RESOURCES_EXCEEDED     由于用户占用资源达到限制而无法为请求授权，比如：用户被限制最多使用一个拨号 PPP 端口，而用户却试图建立第二个PPP 连接"
    5007: "DIAMETER_CONTRADICTING_AVPS    AVP 相互矛盾，必须在 Failed-AVP 中携带相互矛盾的AVP "
    5008: "DIAMETER_AVP_NOT_ALLOWED    消息中包含不可出现的AVP，必须在Failed-AVP 中携带不被允许的AVP "
    5009: "DIAMETER_AVP_OCCURS_TOO_MANY_TIMES    在消息中AVP 重复的次数超过消息所定义的最大次数，必须在 Failed-AVP 中携带第一个超过允许次数的AVP"
    5010: "DIAMETER_NO_COMMON_APPLICATION    当CER 消息被接收到时，对等端之间没有支持的公共应用"
    5011: "DIAMETER_UNSUPPORTED_VERSION    版本号不被支持 "
    5012: "DIAMETER_UNABLE_TO_COMPLY    请求由于无法表示的原因被拒绝"
    5013: "DIAMETER_INVALID_BIT_IN_HEADER   在消息头中无法识别的比特位被置 1"
    5014: "DIAMETER_INVALID_AVP_LENGTH   AVP 长度无效，必须在 Failed-AVP 中携带违规的AVP "
    5015: "DIAMETER_INVALID_MESSAGE_LENGTH   消息长度无效 "
    5016: "DIAMETER_INVALID_AVP_BIT_COMBO   给出的AVP 标志值不被允许，必须在 Failed-AVP 中携带违规的AVP "
    5017: "DIAMETER_NO_COMMON_SECURITY     当CER 消息被接收到时，对等端之间没有公共的安全机制 "
    5030: "DIAMETER_USER_UNKNOWN     指定的用户无法在 OCF 中找到 "
    5031: "DIAMETER_RATING_FAILED    由于输入的批价信息不足、错误的AVP 组合、AVP 的值无法识别或支持，请求的业务无法批价(rating)，必须在Failed-AVP 中携带无法成功处理的AVP 或者包含供应商标识(Vender-Id)的缺失AVP"
    4202: "NEVER_USED        储值卡未头次使用 "
    4203: "USER_FROZEN       储值卡进入冷冻期 "
    4204: "USER_MISSING_CLAIM     储值卡已挂失 "
    4205: "USER_LOCKED       储值卡被封锁 "
    4207: "USER_ EXPIRED     储值卡超过有效期，进入保留期"
    4208: "VOICE_SERVICE_STOPED    语音业务已经停止 "
    4211: "NOT_PPS           用户使用的是非预付费电话 "
    4212: "BALANCE_IS_ZERO    主叫余额为零或小于零"
    4214: "NO_INDIVIDUAL_PAYMENT    对不起，您拨的电话号码需要个人付费，请查询"
    4216: "MEMBER_ACCOUNT_FROZEN      对不起，您的成员帐户被冻结"
    4218: "MEMBERACCOUNT_REACHED_MONTHLY_LIMIT      对不起，您的成员帐户月限额已到达"
    4220: "CALLED_MEMBER_ACCOUNT_FROZEN      对不起，您所拨的用户成员帐户被冻结，无法接听您的电话"
    4221: "CALLED_MEMBER_ACCOUNT_REACHED_MONTHLY_LIMIT      对不起，您所拨的用户成员帐户月限额到达，无法接听您的电话"
    4206: "USER_INVALID    储值卡已失效(包括挂失、被封锁等)"
    4301: "USER_ONE_BLOCK"
    4302: "USER_TWO_BLOCK"
    4303: "USER_TEMPORARY_BLOCK"
    4304: "NO_AUTHORIZED"