RunSeq:
  - "configCPCExt.yaml"
  - "configDefault.yaml"
  - "configPPUsageEvent.yaml"
  - "configPPTimeSpan.yaml"
  - "configZoneMap.yaml"
  - "configProject.yaml"
  - "configPPUsageTariff.yaml"
  - "configCICTrigger.yaml"
  - "configCIC.yaml"
  - "configLifecycle.yaml"
  - "configPPReAttr.yaml"
  - "configPPConsumeTypeBenefit.yaml"
  - "configPPParameterTable.yaml"
  - "configPPTariffRela.yaml"
  - "configCICService.yaml"