DefaultUser:
  abc

param_list:
  WarningData:
    abc_user_name:
      abc
  BadData:
    abc_user_name:
      abc
  ErrorData:
    abc_user_name:
      abc

WarningData:
  Multi values may using 'in' operator:
    sql: " select rule_id from jl_account_mapping_rule
    where factor_value like '%%,%%' and operator in (1,2)"