UserList:
  abc

param_list:
  WarningData:
    abc_user_name:
      abc
  BadData:
    abc_user_name:
      abc
  ErrorData:
    abc_user_name:
      abc

ErrorData:
  Duplicated Action for Process Rule:
    sql: "
    SELECT
    m.*,
    c.GPR_ACTION_DEF_ID,
    c.TFM_SERIVCE_NAME
    FROM
    (SELECT
    a.GPR_ID,
    a.GPR_NAME,
    b.GPR_INST_ID,
    m.GPR_NODE_ID,
    m.GPR_NODE_NAME
    FROM
    coll_gpr a,
    COLL_GPR_INST b,
    coll_gpr_node m
    WHERE a.GPR_ID = b.GPR_ID
    AND b.GPR_INST_ID = m.GPR_INST_ID) m,
    (SELECT
    a.GPR_ACTION_DEF_ID,
    a.GPR_NODE_ID
    FROM
    coll_gpr_action a,
    coll_gpr_action b
    WHERE a.gpr_node_id = b.gpr_node_id
    AND a.gpr_action_def_id = b.gpr_action_def_id
    AND a.SEQ <> b.SEQ) n,
    coll_gpr_action_def c
    WHERE m.GPR_NODE_ID = n.GPR_NODE_ID
    AND n.GPR_ACTION_DEF_ID = c.GPR_ACTION_DEF_ID
    AND m.GPR_NAME NOT LIKE '%%preprocess'"

  Process Rule Eff Exp Date Error:
    sql: "
    select m.* from coll_GPR m ,(select a.GPR_ID from COLL_GPR_INST a where
    a.EFF_DATE>SYSDATE() or a.EXP_DATE<SYSDATE() or a.EFF_DATE>a.EXP_DATE)n
    where m.GPR_ID=n.GPR_ID"


