DefaultUser:
    cpc

delete:
    DC_PRICE_CHECK_RESULT_SELFTAB: delete from DC_PRICE_CHECK_RESULT_SELFTAB where check_topic='after_check'

#insert into result table
insert_result_tab:
    insert into DC_PRICE_CHECK_RESULT_SELFTAB (check_file_name,check_group,check_item,check_sql,check_result,check_topic)
    values (%s,%s,%s,%s,%s,%s)


export_result:
    DC_PRICE_CHECK_RESULT_SELFTAB:
        select check_file_name as file_name,
        check_group as topic_name,
        check_item as title_name,
        check_sql as sql_content,
        case when check_result = 0 then 'success' else 'fail' end as result,
        check_result as error_count,
        create_date as check_time
        from DC_PRICE_CHECK_RESULT_SELFTAB
        where check_topic = %(check_type)s
        and check_file_name = %(file_name)s
        and check_group = %(topic)s
        and check_item = %(title)s
        and check_result <> %(only_failed)s

check_title_all_list:
    A009 BALANCE TYPE NOT RELATED TO CONSUME TYPE:
        des: 帐本没有与消费类型关联，说明没有使用到,SQL中帐本的范围可以修改
        topic: BadData
        area: A009

    A009 Event exists in price but not in sort rule:
        des: 检查正常配置的资费中的使用费事件，但是分拣中没有输出对应的事件，SQL中资费计划的范围可以相应修改
        topic: BadData
        area: A009

    A009 Tariff plan not relate offer:
        des: tariff plan没有与 OFFER 关联，注意可以更新 tariff plan id 的范围
        topic: BadData
        area: A009

    Balance Type not related to consume type:
        des: 帐本没有与消费类型关联，说明没有使用到,SQL中帐本的范围可以修改
        topic: BadData
        area: A009

    Precision not correct:
        des: 精度问题
        topic: ErrorData
        area: comm

    Tariff plan not relate offer:
        des: tariff plan没有与 OFFER 关联，注意可以更新 tariff plan id 的范围
        topic: BadData
        area: A009

    The account item not releated tax:
        des: 账目类型没有配置税
        topic: BadData
        area: A009
