A002:
  Topic001:
    UserList:
      cpc
    BadData:

    ErrorData:

A009:
  Topic001:
    UserList:
      cpc

    WarningData:

    BadData:
      A009 Balance Type not related to consume type:
        #帐本没有与消费类型关联，说明没有使用到,SQL中帐本的范围可以修改
        "SELECT * FROM
                 cbec_acct_res a
                 WHERE
                    (
                        a.acct_res_id > 10000 OR a.ACCT_RES_ID = 1
                    )
                    AND NOT EXISTS (
                    SELECT * FROM
                        con_res_detail b
                    WHERE
                        a.ACCT_RES_ID = b.acct_res_id
                    )"

      A009 Event exists in price but not in sort rule:
        #检查正常配置的资费中的使用费事件，但是分拣中没有输出对应的事件，SQL中资费计划的范围可以相应修改
        "SELECT * FROM
                        price_plan pp,
                        price_plan_ver ppv,
                        price_plan_member ppm,
                        re_price_set rps,
                        re r
                     WHERE
                        pp.PRICE_PLAN_ID > 70000000
                        AND pp.STATE = 'B'
                        AND pp.PRICE_PLAN_ID = ppv.PRICE_PLAN_ID
                        AND ppv.EFF_DATE < now()
                        AND (ppv.EXP_DATE IS NULL OR ppv.EXP_DATE > now())
                        AND ppv.PRICE_PLAN_VER_ID = ppm.PRICE_PLAN_VER_ID
                        AND ppm.PRICE_SET_ID = rps.PRICE_SET_ID
                        AND rps.RE_ID = r.RE_ID
                        AND r.RE_TYPE = 1
                        AND rps.RE_ID NOT IN (
                        SELECT c.re_id FROM
                            bwf_action a,
                            re_attr b,
                            re c,
                            def_re_attr d,
                            reserve_re_attr e
                        WHERE
                            a.src_re_attr = b.re_attr
                            AND b.re_attr = d.re_attr
                            AND d.def_re_attr = e.re_attr
                            AND e.re_attr = 21
                        AND a.param1 = c.re_id)"

      A009 Tariff plan not relate offer:
        #tariff plan没有与 OFFER 关联，注意可以更新 tariff plan id 的范围
        "SELECT * FROM
               tariff_plan tp
               WHERE
                NOT EXISTS (
                SELECT
                    1
                FROM
                    offer_price op
                WHERE
                    tp.TARIFF_PLAN_ID = op.TARIFF_PLAN_ID
                )
                AND tp.STATE = 'B'
                AND tp.TARIFF_PLAN_ID > 70000000"

      The account item not releated tax:
        #帐目未配置税
       "select *
        from cbec_acct_item_type a
        where a.ACCT_ITEM_TYPE_ID > 10000
          and a.ACCT_RES_ID = 1
          and a.ACCT_ITEM_TYPE_ID != 10061
          and not exists(select 1 from cbec_acct_item_type_tax_rate b where a.ACCT_ITEM_TYPE_ID = b.ACCT_ITEM_TYPE_ID)"

    ErrorData:
