A001:
  create:
    DC_Test003:
      create table DC_Test003 (
      check_item varchar2(200),
      check_sql varchar2(4000),
      check_result varchar2(20)
      )

  create_list:
    DC_Test003:
      - A018
      - V20200928
      - database link

A002:
  create:
    DC_CPC:
      CREATE DATABASE LINK "DC_CPC"
      CONNECT TO "CC2" IDENTIFIED BY "1jian8Shu!"
      USING '(DESCRIPTION =
      (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 10.10.177.31)(PORT = 1522))
      )
      (CONNECT_DATA =
      (SERVICE_NAME = cc)
      )
      )'

  create_list:
    DC_CPC:
      - A018
      - V20200928
      - database link

A003:
  create:
    DC_TEST004:
      create table DC_Test004 (
      check_item varchar2(200),
      check_sql varchar2(4000),
      check_result varchar2(20)
      )

  create_list:
    DC_TEST004:
      - A018
      - V20210928
      - table
      - VALUE_LIST:
          CHECK_ITEM:
            TYPE: list
            SOURCE: 1,2,3,4
          CHECK_SQL:
            TYPE: list
            SOURCE: a,b,c
      - COMMENTS:
          - CHECK_ITEM: 12312312