create:
    DC_CONFIG_PP_BILL_DISCT:
        - |
            CREATE  TABLE DC_CONFIG_PP_BILL_DISCT
            (
                OLD_OFFER_ID  NUMBER(15),
                PRICE_PLAN_ID  NUMBER(15),
                PRICE_PLAN_NAME VARCHAR2(255),
                BILLING_PLAN_TYPE VARCHAR2(120),
                DP_NAME               VARCHAR2(120),
                DP_SEQ             NUMBER(10),
                DISCOUNT_METHOD    VARCHAR2(120),
                DISTRIBUTE_OBJ     VARCHAR2(120),
                DISTRIBUTE_METHOD VARCHAR2(120),
                NEGATIVE_FLAG   VARCHAR2(120),
                REF_DISCT_OBJ_NAME        VARCHAR2(120),
                REF_DISCT_ACCT_ITEM_GNP   VARCHAR2(120),
                CALC_DISCT_OBJ_NAME        VARCHAR2(120),
                CALC_DISCT_ACCT_ITEM_GNP   VARCHAR2(120),
                APPLY_DISCT_OBJ_NAME       VARCHAR2(120),
                APPLY_DISCT_ACCT_ITEM_GNP  VARCHAR2(120),
                DISCT_CALC_METHOD          VARCHAR2(120),
                CALC_VAL                   VARCHAR2(120),
                S_VAL                       VARCHAR2(120),
                E_VAL                       VARCHAR2(120),
                SEQ_NBR                    NUMBER(10),
                COMMENTS                    VARCHAR2(500),
                OPER_TYPE CHAR(1)
            )
        - comment on table DC_CONFIG_PP_BILL_DISCT is  'Bill Discount Price Plan Information'
        - comment on column DC_CONFIG_PP_BILL_DISCT.BILLING_PLAN_TYPE is 'billing_plan_type  1,Discount;2,Tax/Addition Fee'
        - comment on column DC_CONFIG_PP_BILL_DISCT.DISTRIBUTE_OBJ is '1 Acct Item, 2 Subscriber, 3 Account'
        - comment on column DC_CONFIG_PP_BILL_DISCT.DISTRIBUTE_METHOD is 'A.Distribute by Contribution of GLID,B.Distribute Averagely,C.Deduct one by one order by priority'
        - comment on column DC_CONFIG_PP_BILL_DISCT.DISCOUNT_METHOD is 'TAB_DP_TYPE > R Rank, S Segmentation'
        - comment on column DC_CONFIG_PP_BILL_DISCT.REF_DISCT_ACCT_ITEM_GNP is 'Define Reference Acct Item Group Name-Custom, not stored in the database'
        - comment on column DC_CONFIG_PP_BILL_DISCT.CALC_DISCT_ACCT_ITEM_GNP is 'Define Calculate Acct Item Group Name-Custom, not stored in the database'
        - comment on column DC_CONFIG_PP_BILL_DISCT.APPLY_DISCT_ACCT_ITEM_GNP is 'Define Discount Acct Item Group Name-Custom, not stored in the database'
        - comment on column DC_CONFIG_PP_BILL_DISCT.DISCT_CALC_METHOD is '1,Percent  2,Fixed Amount  3,Summation  4,Ceil and Floor 5,Rating on Usage Value '
        - comment on column DC_CONFIG_PP_BILL_DISCT.CALC_VAL is 'Discount Value'
        - comment on column DC_CONFIG_PP_BILL_DISCT.S_VAL is 'Start Value'
        - comment on column DC_CONFIG_PP_BILL_DISCT.E_VAL is 'End Value'
        - comment on column DC_CONFIG_PP_BILL_DISCT.OPER_TYPE is 'Operation Type:A means add, D means delete'


        - |
            CREATE  TABLE DC_CONFIG_PP_BILL_ACCTITEM
            (   PRICE_PLAN_ID  NUMBER(15),
                PRICE_PLAN_NAME VARCHAR2(255),
                DP_NAME               VARCHAR2(120),
                DISCT_OBJ_NAME    VARCHAR2(120),
                ACCT_ITEM_GNP_NAME   VARCHAR2(255),
                ACCT_ITEM_TYPE_NAME  VARCHAR2(255),
                SEQ             NUMBER(10)
            )

        - comment on table DC_CONFIG_PP_BILL_ACCTITEM is  'Bill discount Price plan used Acct item list'

        - |
            CREATE  TABLE DC_CONFIG_PP_DISCT_COND
            (
                OLD_OFFER_ID  NUMBER(15),
                PRICE_PLAN_ID  NUMBER(15),
                PRICE_PLAN_NAME VARCHAR2(255),
                DP_NAME               VARCHAR2(120),
                CONDITION       VARCHAR2(255),
                DP_REF_COND_NAME      VARCHAR2(255),
                CON_GRP_SEQ     VARCHAR2(10),
                COND_SEQ       VARCHAR2(10),
                COND_PARAM       VARCHAR2(255),
                OPERATOR           VARCHAR2(60),
                Value       VARCHAR2(120),
                COMMENTS      VARCHAR2(120)
            )
        - comment on table DC_CONFIG_PP_DISCT_COND is  'Bill Discount Condtion list'
        - comment on column DC_CONFIG_PP_DISCT_COND.DP_REF_COND_NAME is 'Condtion Name'
        - comment on column DC_CONFIG_PP_DISCT_COND.COND_PARAM is 'condition parameter'
        - comment on column DC_CONFIG_PP_DISCT_COND.CON_GRP_SEQ is 'condition SEQ '
        - comment on column DC_CONFIG_PP_DISCT_COND.COND_SEQ is 'in one "and" condition have more than one consdition SEQ, normally  use opertor "or" will have this condition'
        - comment on column DC_CONFIG_PP_DISCT_COND.CONDITION is 'Condition Type:Discount Condtion,Reference Object Condition,Applying Object Condition,Calculation Object Condition'



        - |
            CREATE  TABLE DC_CONFIG_PP_BILL_VAL_Prorate
            (   PRICE_PLAN_ID  NUMBER(15),
                PRICE_PLAN_NAME VARCHAR2(255),
                DP_id   NUMBER(9),
                DP_NAME               VARCHAR2(120),
                SEQ_NO                VARCHAR2(10),
                DISCT_CALC_METHOD    VARCHAR2(120),
                CALC_VAL    VARCHAR2(255),
                Prorate           VARCHAR2(1)
            )
        - comment on table DC_CONFIG_PP_BILL_VAL_Prorate is  'Bill discount update calc value to prorate'


create_list:
    DC_CONFIG_PP_BILL_DISCT:
        - PP_BILL_DISCT
        - V20211028
        - table
        - VALUE_LIST:
            STOP_USER_FLAG:
                TYPE: list
                SOURCE: 0,1
            REMOVE_USER_FLAG:
                TYPE: list
                SOURCE: 0,1
            ARREAR_FLAG:
                TYPE: list
                SOURCE: 0,1
            BILLING_PLAN_TYPE:
                TYPE: sql
                SOURCE: SELECT BILLING_PLAN_TYPE_NAME from CPC.BILLING_PLAN_TYPE
            DISTRIBUTE_OBJ:
                TYPE: list
                SOURCE: Acct Item,Subscriber,Account
            DISTRIBUTE_METHOD:
                TYPE: list
                SOURCE: Distribute by Contribution of GLID,Distribute Averagely,Deduct one by one order by priority
            DISCT_CALC_METHOD:
                TYPE: sql
                SOURCE: select DISCT_CALC_METHOD_NAME  from  CPC.DISCT_CALC_METHOD
            DISCOUNT_METHOD:
                TYPE: sql
                SOURCE:  SELECT TAB_DP_TYPE_NAME FROM TAB_DP_TYPE
            OPER_TYPE:
                TYPE: list
                SOURCE: A,D
    DC_CONFIG_PP_BILL_ACCTITEM:
        - PP_BILL_DISCT
        - V20211102
        - table

    DC_CONFIG_PP_DISCT_COND:
        - PP_BILL_DISCT
        - V20211103
        - table
        - VALUE_LIST:
            DP_REF_COND_NAME:
                TYPE: sql
                SOURCE: select DP_REF_COND_NAME  from  CPC.DP_REF_COND
            OPERATOR:
                TYPE: sql
                SOURCE: select SORT_OPERATOR_NAME  from  CPC.SORT_OPERATOR
            CONDITION:
                TYPE: list
                SOURCE: Discount Condtion,Reference Object Condition,Applying Object Condition,Calculation Object Condition
    DC_CONFIG_PP_BILL_VAL_PRORATE:
        - PP_BILL_DISCT
        - V20220520
        - table
        - VALUE_LIST:
            Prorate:
                TYPE: list
                SOURCE: Y,N