create:
    DC_CONFIG_ZONE_MAP:
        - |
            CREATE TABLE DC_CONFIG_ZONE_MAP
              (
                  M_ZONE_MAP_NAME VARCHAR2(120) NOT NULL,
                  O_ZONE_MAP_CODE VARCHAR2(30),
                  M_ZONE_MAP_COMMENT VARCHAR2(1000) not null,
                  M_MATCH_MODE CHAR(1) NOT NULL,
                  O_ZONE_MAP_TYPE NUMBER(3),
                  M_ZONE_NAME VARCHAR2(200) NOT NULL,
                  O_ZONE_CODE VARCHAR2(200),
                  M_ZONE_VALUE VARCHAR2(65) NOT NULL,
                  O_ZONE_COMMENT  VARCHAR2(1000)
               )
        - comment on table DC_CONFIG_ZONE_MAP is  'zone map table'
        - comment on column DC_CONFIG_ZONE_MAP.M_ZONE_MAP_NAME is 'the name of zone map'
        - comment on column DC_CONFIG_ZONE_MAP.O_ZONE_MAP_CODE is 'the code zone map ,can be null'
        - comment on column DC_CONFIG_ZONE_MAP.M_ZONE_MAP_COMMENT is 'the comment of zone map ,can not be null'
        - comment on column DC_CONFIG_ZONE_MAP.M_MATCH_MODE is  'P:Prefix; E:Exact Match; D:Range Match; S:Split Prefix Match; F:Fuzzy Match'
        - comment on column DC_CONFIG_ZONE_MAP.O_ZONE_MAP_TYPE is  '1:Countries Code; 2:VAS Code; 3:HandSet Code; can be null'
        - comment on column DC_CONFIG_ZONE_MAP.M_ZONE_NAME is  'the name of zone'
        - comment on column DC_CONFIG_ZONE_MAP.O_ZONE_CODE is  'the code of zone'
        - comment on column DC_CONFIG_ZONE_MAP.M_ZONE_VALUE is  'the value of zone'
        - comment on column DC_CONFIG_ZONE_MAP.O_ZONE_COMMENT is  'the remark of zone value'

    DC_INSERT_ZONE_MAP:
        - |
          CREATE OR REPLACE PROCEDURE DC_INSERT_ZONE_MAP is
            v_zone_map_id number(10);
            v_zone_map_name varchar2(120);
            v_zone_map_code varchar2(120);
            v_zone_map_comment varchar2(1000);
            v_match_mode CHAR(1);
            v_zone_map_type NUMBER(3);
            v_zone_id number(10);
            v_seq number(10);
            v_zone_name varchar2(200);
            v_zone_code varchar2(200);
            v_zone_value_id number(10);
            v_zone_value varchar2(20);
            v_zone_value_comment varchar2(1000);
            v_flag number(2);

          begin
            for cur_zone_map in (select distinct m_zone_map_name,o_zone_map_code,m_zone_map_comment,m_match_mode,o_zone_map_type from DC_CONFIG_ZONE_MAP) loop
              select cur_zone_map.m_zone_map_name,cur_zone_map.o_zone_map_code,cur_zone_map.m_zone_map_comment,cur_zone_map.m_match_mode,cur_zone_map.o_zone_map_type
              into v_zone_map_name,v_zone_map_code,v_zone_map_comment,v_match_mode,v_zone_map_type from dual;
              select count(1) into v_flag from zone_map where zone_map_name=v_zone_map_name;
              if v_flag=0 then
                select COALESCE(max(zone_map_id) + 1, 1) into v_zone_map_id from zone_map;
                insert into zone_map (zone_map_id,zone_map_name,match_mode,zone_map_type,std_code,state,state_date,comments)
                values(v_zone_map_id,v_zone_map_name,v_match_mode,v_zone_map_type,v_zone_map_code,'A', to_date('2000-01-01 00:00:00','yyyy-mm-dd hh24:mi:ss'),v_zone_map_comment);
              else
                select zone_map_id into v_zone_map_id from zone_map where zone_map_name=v_zone_map_name;
              end if;
              for cur_zone in (select distinct m_zone_name,o_zone_code from DC_CONFIG_ZONE_MAP where m_zone_map_name=v_zone_map_name) loop
                select cur_zone.m_zone_name,cur_zone.o_zone_code into v_zone_name,v_zone_code from dual;
                select count(1) into v_flag from zone where zone_name=v_zone_name and zone_map_id=v_zone_map_id;
                if v_flag=0 then
                  select COALESCE(max(zone_id)+1,1) into v_zone_id from zone;
                  insert into ZONE(ZONE_ID,ZONE_MAP_ID,PARENT_ZONE_ID,ZONE_NAME,ZONE_CODE,COMMENTS, SP_ID)
                  values(v_zone_id, v_zone_map_id, null,v_zone_name, v_zone_code, null, null);
                else
                  select zone_id into v_zone_id from zone where zone_name=v_zone_name and zone_map_id=v_zone_map_id;
                end if;
                for cur_zone_value in (select distinct m_zone_value,o_zone_comment from DC_CONFIG_ZONE_MAP where m_zone_name=v_zone_name and m_zone_map_name=v_zone_map_name) loop
                  select cur_zone_value.m_zone_value,cur_zone_value.o_zone_comment into v_zone_value,v_zone_value_comment from dual;
                  select count(1) into v_flag from zone_value where zone_id=v_zone_id and value=v_zone_value;
                  if v_flag=0 then
                    select COALESCE(max(ZONE_VALUE_ID) + 1, 1) into v_zone_value_id from zone_value;
                    select COALESCE(max(SEQ) + 1, 1) into v_seq from ZONE_VALUE where ZONE_ID = v_zone_id;
                    insert into ZONE_VALUE (ZONE_VALUE_ID,ZONE_ID,SEQ,VALUE,EXP_VALUE,EFF_DATE,EXP_DATE,COMMENTS,SP_ID)
                    values (v_zone_value_id, v_zone_id, v_seq,v_zone_value,null, to_date('2000-01-01 00:00:00','yyyy-mm-dd hh24:mi:ss'), null,v_zone_value_comment, null);
                  end if;
                end loop;
              end loop;
            end loop;
          end;

create_list:
    DC_CONFIG_ZONE_MAP:
        - PP_ZONE_MAP
        - V20190509
        - TABLE
        - VALUE_LIST:
            M_MATCH_MODE:
              TYPE: list
              SOURCE: P,E,D,S,F
            O_ZONE_MAP_TYPE:
              TYPE: list
              SOURCE: 1,2,3

    DC_INSERT_ZONE_MAP:
        - PP_ZONE_MAP
        - V20190510
        - procedure