create:
    DC_CONFIG_TAX_CODE:
        - |
            CREATE TABLE DC_CONFIG_TAX_CODE
            (
                TAX_CODE          VARCHAR2(20),
                TAX_CODE_NAME     VARCHAR2(60),
                TAX_STD_CODE      VARCHAR2(20) ,
                TAX_RATE          NUMBER(9),
                TAX_ACCT_ITEM_NAME   VARCHAR2(255),
                NET_FLAG          VARCHAR2(1),
                FLOOR_AMOUNT      NUMBER(18),
                TAX_ON_TAX_FLAG   CHAR(1),
                TAX_CODE_DESC     VARCHAR2(200)
            )
        - comment on table DC_CONFIG_TAX_CODE is  'Billing Tax Code'
        - comment on column DC_CONFIG_TAX_CODE.TAX_CODE is 'Tax Code'
        - comment on column DC_CONFIG_TAX_CODE.TAX_CODE_NAME is 'Tax Code NAME'
        - comment on column DC_CONFIG_TAX_CODE.TAX_RATE is 'TAX RATE permillage'
        - comment on column DC_CONFIG_TAX_CODE.TAX_ACCT_ITEM_NAME is 'Tax Account Item Type'
        - comment on column DC_CONFIG_TAX_CODE.NET_FLAG is 'The default value Y indicates net tax calculation'
        - comment on column DC_CONFIG_TAX_CODE.FLOOR_AMOUNT is 'Since the amount of price'
        - comment on column DC_CONFIG_TAX_CODE.TAX_ON_TAX_FLAG is 'Tax on tax sign'

    DC_CONFIG_TAX_FACTOR_GRP:
        - |
            CREATE  TABLE DC_CONFIG_TAX_FACTOR_GRP
            (   TAX_FACTOR_GRP_NAME  VARCHAR2(255),
                TAX_FACTOR           VARCHAR2(60),
                TAX_FACT_VALUE_NAME  VARCHAR2(255),
                COMMENTS VARCHAR2(255)
            )
        - comment on table DC_CONFIG_TAX_FACTOR_GRP is  'Billing Tax FACTOR information'


    DC_CONFIG_BILLING_TAX:
        - |
            CREATE TABLE DC_CONFIG_BILLING_TAX
            (
                TAX_MAP_NAME        VARCHAR2(255),
                TAX_RULE_NAME       VARCHAR2(255),
                RULE_SEQ            NUMBER(10),
                TAX_CODE            VARCHAR2(20) ,
                TAX_FLAG            VARCHAR2(60) ,
                CONNECT_TYPE        VARCHAR2(60) ,
                PROVINCE            VARCHAR2(60) ,
                ACCT_ITEM_GRP_NAME  VARCHAR2(60) ,
                COMMENTS            VARCHAR2(255)
            )
        - comment on table DC_CONFIG_BILLING_TAX is  'Billing Tax Information'
        - comment on column DC_CONFIG_BILLING_TAX.TAX_MAP_NAME is 'TAX VERSION NAME'
        - comment on column DC_CONFIG_BILLING_TAX.TAX_RULE_NAME is 'TAX RULE List'
        - comment on column DC_CONFIG_BILLING_TAX.TAX_CODE is 'Used from CBEC_TAX_STD_CODE'
        - comment on column DC_CONFIG_BILLING_TAX.TAX_FLAG is 'Codition1:subs_attr=WCT_TAX_FLAG,should use Group'
        - comment on column DC_CONFIG_BILLING_TAX.CONNECT_TYPE is 'Codition2:subs_attr=WCT_CONNECT_TYPE_ID,should use Group'
        - comment on column DC_CONFIG_BILLING_TAX.PROVINCE is 'Codition3:subs_attr=WCT_PROVINCE,should use Group'
        - comment on column DC_CONFIG_BILLING_TAX.ACCT_ITEM_GRP_NAME is 'Codition4:Account item Group'


create_list:
    DC_CONFIG_TAX_CODE:
        - PP_BILL_TAX
        - V20220108
        - table
        - VALUE_LIST:
            NET_FLAG:
                TYPE: list
                SOURCE: Y,N
            TAX_STD_CODE:
                TYPE: sql
                SOURCE: select TAX_STD_CODE from  CBEC_TAX_STD_CODE
            TAX_ON_TAX_FLAG:
                TYPE: list
                SOURCE: Y,N

    DC_CONFIG_TAX_FACTOR_GRP:
        - PP_BILL_TAX
        - V20211108
        - table
        - VALUE_LIST:
            TAX_FACTOR:
                TYPE: list
                SOURCE: Acct Item Type,Province,Connect Type,Tax Flag

    DC_CONFIG_BILLING_TAX:
        - PP_BILL_TAX
        - V20211108
        - table




