create:
   DC_CONFIG_EVENT_U:
        - |
            CREATE TABLE DC_CONFIG_EVENT_U
              (
                  M_RE_ID NUMBER(10) NOT NULL,
                  O_SERV_TYPE VARCHAR2(10),
                  M_RE_NAME VARCHAR2(200) NOT NULL,
                  O_RE_CODE VARCHAR2(100),
                  O_PARENT_RE_NAME VARCHAR2(200),
                  O_RESERVE_LIMIT NUMBER(10),
                  O_RESERVE_MAX NUMBER(10),
                  O_RESERVE_UNIT VARCHAR2(10),
                  O_COMMENT VARCHAR2(1000)
              )
        - comment on table DC_CONFIG_EVENT_U is  'EVENT TABLE'
        - comment on column DC_CONFIG_EVENT_U.M_RE_ID is 'the seq of usage re_id is greater than 9999'
        - comment on column DC_CONFIG_EVENT_U.M_RE_NAME is  'the re_name'
        - comment on column DC_CONFIG_EVENT_U.O_RE_CODE is  'the re_code'
        - comment on column DC_CONFIG_EVENT_U.O_RE_CODE is  'the re_code'
        - comment on column DC_CONFIG_EVENT_U.O_PARENT_RE_NAME is  'the parent re name'
        - comment on column DC_CONFIG_EVENT_U.O_RESERVE_LIMIT is  'the minimum reservation'
        - comment on column DC_CONFIG_EVENT_U.O_RESERVE_MAX is  'the maximum reservation'
        - comment on column DC_CONFIG_EVENT_U.O_RESERVE_UNIT is  'the reservation unit:S(second);B(bytes);O(occurence)'
        - comment on column DC_CONFIG_EVENT_U.O_COMMENT is  'the COMMENT'


create_list:
    DC_CONFIG_EVENT_U:
        - PP_USAGE_EVENT
        - V20190508
        - TABLE
        - VALUE_LIST:
            O_SERV_TYPE:
                TYPE: list
                SOURCE: SMS,VOICE,MMS,DATA,CRBT
            O_RESERVE_UNIT:
                TYPE: list
                SOURCE: S,B,O