create:
    DC_CONFIG_CONSUME_TYPE_BENEFIT:
        - |
            CREATE TABLE DC_CONFIG_CONSUME_TYPE_BENEFIT
              (
                  M_CON_RES_NAME VARCHAR2(100) NOT NULL,
                  O_CON_RES_CODE VARCHAR2(100),
                  M_UNIT VARCHAR2(10) NOT NULL,
                  O_ACCT_RES_ID NUMBER(10),
                  M_ACCT_RES_NAME VARCHAR2(100) NOT NULL ,
                  O_ACCT_ITEM_TYPE_ID NUMBER(10),
                  M_ACCT_ITEM_TYPE_NAME VARCHAR2(100) NOT NULL ,
                  O_PRIORITY NUMBER(10),
                  O_COMMENT  varchar2(1000)
              )
        - comment on table DC_CONFIG_CONSUME_TYPE_BENEFIT is  'BENEFIT CONSUME TYPE TABLE'
        - comment on column DC_CONFIG_CONSUME_TYPE_BENEFIT.M_CON_RES_NAME is 'CONSUME TYPE NAME'
        - comment on column DC_CONFIG_CONSUME_TYPE_BENEFIT.O_CON_RES_CODE is 'CONSUME TYPE CODE,can be null'
        - comment on column DC_CONFIG_CONSUME_TYPE_BENEFIT.M_UNIT is 'the unit of benefit type :occ(occurrence),sec(second),byte(byte),only display the unit of consume type'
        - comment on column DC_CONFIG_CONSUME_TYPE_BENEFIT.O_ACCT_RES_ID is  'the acct res id ,can be null'
        - comment on column DC_CONFIG_CONSUME_TYPE_BENEFIT.M_ACCT_RES_NAME is  'the acct res name'
        - comment on column DC_CONFIG_CONSUME_TYPE_BENEFIT.O_ACCT_ITEM_TYPE_ID is  'the acct item type id,can be null'
        - comment on column DC_CONFIG_CONSUME_TYPE_BENEFIT.M_ACCT_ITEM_TYPE_NAME is  'the acct item typ name'
        - comment on column DC_CONFIG_CONSUME_TYPE_BENEFIT.O_PRIORITY is  'priority of this acct res, can be null,default:0'

create_list:
    DC_CONFIG_CONSUME_TYPE_BENEFIT:
        - PP_CONSUME_TYPE_BENEFIT
        - V20190927
        - TABLE
        - VALUE_LIST:
            M_UNIT:
                TYPE: list
                SOURCE: occ,sec,byte