create:
    DC_CONFIG_PP_RENT_TARIFF:
        - |
            CREATE  TABLE DC_CONFIG_PP_RENT_TARIFF
            (
                OLD_OFFER_ID  NUMBER(15),
                PRICE_PLAN_ID  NUMBER(15),
                PRICE_PLAN_NAME VARCHAR2(255),
                RECURRING_RE_TYPE VARCHAR2(50),
                RATING_TYPE  VARCHAR2(50),
                CON_FUNCTION  VARCHAR2(60),
                L_RE_ATTR  VARCHAR2(120),
                CON_L_PARAM1  VARCHAR2(255),
                CON_L_PARAM2  VARCHAR2(255),
                CON_SORT_OPERATOR  varchar(60),
                CON_R_VALUE_TYPE varchar(60),
                CON_R_VALUE varchar(120),
                R_ZONE_MAP  VARCHAR2(255),
                R_ZONE_NAME  VARCHAR2(255),
                RECURRING_PRICE    NUMBER(15,6),
                CON_RES_NAME VARCHAR2(255),
                SEQ  NUMBER(10),
                BENEFIT_ACCT_RES_NAME VARCHAR2(120),
                BENEFIT_VALUE    NUMBER(15),
                BENEFIT_DURATION  NUMBER(6),
                BENEFIT_DURATION_UNIT VARCHAR2(10),
                COMMENTS VARCHAR2(120)
            )
        - comment on table DC_CONFIG_PP_RENT_TARIFF is  'Price Plan rent/recurring fee(auto renew)'
        - comment on column DC_CONFIG_PP_RENT_TARIFF.RATING_TYPE is 'choose Single/Mapping/Condition rating Type'
        - comment on column DC_CONFIG_PP_RENT_TARIFF.SEQ is 'when SEQ=1 insert into recurring RE/RATE_PLAN'
        - comment on column DC_CONFIG_PP_RENT_TARIFF.CON_RES_NAME is 'Consume Name'
        - comment on column DC_CONFIG_PP_RENT_TARIFF.BENEFIT_DURATION_UNIT is 'mandatory when have benefit,BENEFIT_DURATION_UNIT in(C,D,S,M) or NULL)'
        - comment on column DC_CONFIG_PP_RENT_TARIFF.PRICE_PLAN_ID is 'COULD BE UPDATED BEFORE INSERT INTO BUSI TABLE'
        - comment on column DC_CONFIG_PP_RENT_TARIFF.CON_L_PARAM1 is 'Left Condtion,left paramter1 '
        - comment on column DC_CONFIG_PP_RENT_TARIFF.CON_L_PARAM2 is 'Left Condtion,left paramter2 '
        - comment on column DC_CONFIG_PP_RENT_TARIFF.CON_Function is 'Condtion function,data from table SORT_FUNCTION '
        - comment on column DC_CONFIG_PP_RENT_TARIFF.CON_SORT_OPERATOR is 'Condtion function operator,data from table SORT_OPERATOR '
        - comment on column DC_CONFIG_PP_RENT_TARIFF.L_RE_ATTR is 'Left Condtion/Mapping Left ,data from table RE_ATTR '
        - comment on column DC_CONFIG_PP_RENT_TARIFF.R_ZONE_MAP is 'Rating Mapping zone map'
        - comment on column DC_CONFIG_PP_RENT_TARIFF.R_ZONE_NAME is 'condition function zone/ Rating Mapping zone name'


create_list:
    DC_CONFIG_PP_RENT_TARIFF:
        - PP_RENT_TARIFF
        - V20211022
        - table
        - VALUE_LIST:
            RECURRING_RE_TYPE:
                TYPE: sql
                SOURCE: SELECT RECURRING_RE_TYPE_NAME from CPC.RECURRING_RE_TYPE
            BENEFIT_DURATION_UNIT:
                TYPE: list
                SOURCE: S,D,C,M
            CON_FUNCTION:
                TYPE: sql
                SOURCE: SELECT FUNCTION from SORT_FUNCTION
            CON_SORT_OPERATOR:
                TYPE: sql
                SOURCE: SELECT SORT_OPERATOR_NAME from SORT_OPERATOR
            CON_R_RE_ATTR:
                TYPE: sql
                SOURCE: SELECT RE_ATTR_NAME from RE_ATTR
            RATING_TYPE:
                TYPE: list
                SOURCE: Single,Mapping,Condition
