Mysql:
  table_exists: select table_name from information_schema.TABLES where table_name = upper(%(table_name)s)
Oracle:
  table_exists: select table_name from user_tables where table_name = upper(%(table_name)s)
