BadData:
  LIFECYCLE_PROCESS_PRIOIRY_DUPLICATED:
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name, T1.PRIORITY
    FROM DC_CONFIG_LIFECYCLE_PROCESS T1
    GROUP BY T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name, T1.PRIORITY
    HAVING COUNT(1)>1
ErrorData:
  LIFECYCLE_DIAGRAM_NAME_IS_NULL:
    SELECT LIFECYCLE_NAME,src_prod_state,obj_prod_state,subs_event_name
    FROM DC_CONFIG_LIFECYCLE_DIAGRAM
    WHERE LIFECYCLE_NAME IS NULL
  LIFECYCLE_DIAGRAM_STATE_NOT_EXISTS:
    SELECT LIFECYCLE_NAME,src_prod_state,obj_prod_state,subs_event_name
    FROM DC_CONFIG_LIFECYCLE_DIAGRAM
    WHERE src_prod_state NOT IN ('G','H','A','D','E','B')
    or obj_prod_state NOT IN ('G','H','A','D','E','B')
  LIFECYCLE_DIAGRAM_SUBS_EVENT_NOT_EXISTS:
    SELECT t1.LIFECYCLE_NAME,t1.src_prod_state,t1.obj_prod_state,t1.subs_event_name
    FROM DC_CONFIG_LIFECYCLE_DIAGRAM T1
    LEFT JOIN cc.SUBS_EVENT t2
    on t1.subs_event_name = t2.EVENT_NAME
    WHERE T2.SUBS_EVENT_ID IS NULL
  LIFECYCLE_DIAGRAM_SERVICE_NAME_NOT_EXISTS:
    SELECT t1.LIFECYCLE_NAME,t1.src_prod_state,t1.obj_prod_state,t1.subs_event_name
    FROM DC_CONFIG_LIFECYCLE_DIAGRAM T1
    LEFT JOIN cc.SUBS_EVENT t2
    on t1.subs_event_name = t2.EVENT_NAME
    WHERE T2.SUBS_EVENT_ID IS NULL
  LIFECYCLE_DIAGRAM_TIMER_NUMBER_ONLY:
    SELECT LIFECYCLE_NAME,src_prod_state,obj_prod_state,subs_event_name
    FROM DC_CONFIG_LIFECYCLE_DIAGRAM
    WHERE TRANSLATE(TIMER,'A0123456789','A') IS NOT NULL
  LIFECYCLE_DIAGRAM_DUPLICATED:
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name
    FROM DC_CONFIG_LIFECYCLE_DIAGRAM T1
    GROUP BY T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name
    HAVING COUNT(1)>1
  LIFECYCLE_PROCESS_DIAGRAM_NODE_NOT_EXISTS: |
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name
      FROM DC_CONFIG_LIFECYCLE_PROCESS T1
      LEFT JOIN DC_CONFIG_LIFECYCLE_DIAGRAM T2
        ON T1.LIFECYCLE_NAME = T2.LIFECYCLE_NAME
       AND T1.src_prod_state = T2.src_prod_state
       AND T1.obj_prod_state = T2.obj_prod_state
       AND T1.subs_event_name = T2.subs_event_name
      LEFT JOIN (SELECT t1.lifecycle_type_name LIFECYCLE_NAME,
                        t2.src_prod_state,
                        t2.obj_prod_state,
                        t3.event_name          subs_event_name
                   FROM CC.lifecycle_type t1
                  INNER JOIN cc.prod_event_diagram t2
                     on t1.lifecycle_type = t2.lifecycle_type
                  inner join cc.SUBS_EVENT t3
                     on t2.subs_event_id = t3.subs_event_id) T3
        on T1.LIFECYCLE_NAME = T3.LIFECYCLE_NAME
       AND T1.src_prod_state = T3.src_prod_state
       AND T1.obj_prod_state = T3.obj_prod_state
       AND T1.subs_event_name = T3.subs_event_name
     WHERE T2.LIFECYCLE_NAME IS NULL
       AND T3.LIFECYCLE_NAME IS NULL
  LIFECYCLE_PROCESS_COMPONENT_NOT_EXISTS:
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name
    FROM DC_CONFIG_LIFECYCLE_PROCESS T1
    LEFT JOIN CC.service_bc t2
    ON T1.business_component_name = t2.bc_name
    and t2.service_rule_type =6
    where t2.bc_id is null
  LIFECYCLE_PROCESS_PRIOIRY_NUMBER_ONLY:
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name
    FROM DC_CONFIG_LIFECYCLE_PROCESS T1
    WHERE TRANSLATE(PRIORITY,'A0123456789','A') IS NOT NULL
  LIFECYCLE_PROCESS_PARAM_FORMAT_ERROR:
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name
    FROM DC_CONFIG_LIFECYCLE_PROCESS T1
    WHERE NOT regexp_like(t1.component_param,'^(\w+=\w+)(\|\w+=\w+)*$')
  LIFECYCLE_PROCESS_DUPLICATED:
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name, T1.business_component_name
    FROM DC_CONFIG_LIFECYCLE_PROCESS T1
    GROUP BY T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name, T1.business_component_name
    HAVING COUNT(1)>1
  LIFECYCLE_ADVICE_DIAGRAM_NODE_NOT_EXISTS: |
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name
      FROM DC_CONFIG_LIFECYCLE_ADVICE T1
      LEFT JOIN DC_CONFIG_LIFECYCLE_DIAGRAM T2
        ON T1.LIFECYCLE_NAME = T2.LIFECYCLE_NAME
       AND T1.src_prod_state = T2.src_prod_state
       AND T1.obj_prod_state = T2.obj_prod_state
       AND T1.subs_event_name = T2.subs_event_name
      LEFT JOIN (SELECT t1.lifecycle_type_name LIFECYCLE_NAME,
                        t2.src_prod_state,
                        t2.obj_prod_state,
                        t3.event_name          subs_event_name
                   FROM CC.lifecycle_type t1
                  INNER JOIN cc.prod_event_diagram t2
                     on t1.lifecycle_type = t2.lifecycle_type
                  inner join cc.SUBS_EVENT t3
                     on t2.subs_event_id = t3.subs_event_id) T3
        on T1.LIFECYCLE_NAME = T3.LIFECYCLE_NAME
       AND T1.src_prod_state = T3.src_prod_state
       AND T1.obj_prod_state = T3.obj_prod_state
       AND T1.subs_event_name = T3.subs_event_name
     WHERE T2.LIFECYCLE_NAME IS NULL
       AND T3.LIFECYCLE_NAME IS NULL
  LIFECYCLE_ADVICE_NAME_NOT_EXISTS:
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.ADVICE_NAME
    FROM DC_CONFIG_LIFECYCLE_ADVICE T1
    LEFT JOIN CC.ADVICE_TYPE T2
    ON T1.ADVICE_NAME = T2.ADVICE_TYPE_NAME
    AND T2.disabled = 'N'
    and T2.advice_catg = 4
    WHERE T2.ADVICE_TYPE IS NULL
  LIFECYCLE_ADVICE_DUPLICATED:
    SELECT T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name, T1.ADVICE_NAME
    FROM DC_CONFIG_LIFECYCLE_ADVICE T1
    GROUP BY T1.LIFECYCLE_NAME, T1.src_prod_state, T1.obj_prod_state, T1.subs_event_name, T1.ADVICE_NAME
    HAVING COUNT(1)>1
  LIFECYCLE_OFFER_REL_LIFECYCLE_NAME_NOT_EXISTS:
    SELECT T1.LIFECYCLE_NAME, T1.OFFER_NAME
    FROM DC_CONFIG_LIFECYCLE_OFFER_REL T1
    LEFT JOIN CC.LIFECYCLE_TYPE T2
    ON T1.LIFECYCLE_NAME = T2.LIFECYCLE_TYPE_NAME
    LEFT JOIN CC.DC_CONFIG_LIFECYCLE_DIAGRAM T3
    ON T1.LIFECYCLE_NAME = T3.LIFECYCLE_NAME
    WHERE T2.LIFECYCLE_TYPE IS NULL
    AND T3.LIFECYCLE_NAME IS NULL
  LIFECYCLE_OFFER_REL_OFFER_NAME_NOT_EXISTS:
    SELECT T1.LIFECYCLE_NAME, T1.OFFER_NAME
    FROM DC_CONFIG_LIFECYCLE_OFFER_REL T1
    LEFT JOIN CC.OFFER T2
    ON T1.OFFER_NAME = T2.OFFER_NAME
    AND T2.OFFER_TYPE IN (1,2,3)
    WHERE T2.OFFER_ID IS NULL
  LIFECYCLE_OFFER_REL_OFFER_NAME_NOT_UNIQUE:
    SELECT T1.OFFER_NAME
    FROM DC_CONFIG_LIFECYCLE_OFFER_REL T1
    GROUP BY OFFER_NAME
    HAVING COUNT(1)>1