create:
    DC_CONFIG_OFFER_OTC_RENT:
        - |
            CREATE  TABLE DC_CONFIG_OFFER_OTC_RENT
            (
                OFFER_NAME VARCHAR2(250),
                OLD_OFFER_ID  NUMBER(15),
                EVENT_TYPE CHAR(20)  default 'OTC' check(EVENT_TYPE in('OTC','RENT')),
                IS_PCRF  varchar2(10),
                ADVANCED_NOTIFICATION varchar2(10),
                RECURRING_RE_TYPE VARCHAR2(50),
                OFFER_INST_VALID_DURATION  NUMBER(10),
                OFFER_INST_VALID_UNIT CHAR(20),
                IS_LIST_PRICE VARCHAR2(10),
                CONDITION  VARCHAR2(50),
                IS_PRORATE VARCHAR2(10),
                SUBSCRIPTION_PRICE    NUMBER(15,8),
                RECURRING_PRICE    NUMBER(15,8),
                ACCT_ITEM_TYPE_NAME VARCHAR2(250),
                OLD_ACCT_ITEM_TYPE_ID NUMBER(10) ,
                SEQ  NUMBER(10),
                OLD_ACCT_RES_NAME VARCHAR2(120),
                OLD_ACCT_RES_ID     NUMBER(6),
                BENEFIT_VALUE    NUMBER(15),
                BENEFIT_DURATION  NUMBER(6),
                BENEFIT_DURATION_UNIT VARCHAR2(10),
                RENT_BENEFIT_EXTENSION_RULE VARCHAR2(20) DEFAULT 'M',
                RENEW_PRIORITY  NUMBER(8),
                COMMENTS VARCHAR2(120),
                NEW_OFFER_ID NUMBER(15),
                PRICE_PLAN_ID  NUMBER(15),
                NEW_ACCT_RES_ID    NUMBER(6),
                NEW_ACCT_ITEM_TYPE_ID NUMBER(6)
            )
        - comment on column DC_CONFIG_OFFER_OTC_RENT.EVENT_TYPE is 'otc-only one time charge,rent-include rent fee(auto renew)'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.OFFER_INST_VALID_UNIT is ' 1 day
                                                                    3 month
                                                                    4 year
                                                                    2 week
                                                                    5 Billing Cycle'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.ADVANCED_NOTIFICATION is 'advanced notification before offer expired or renewal'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.IS_PCRF  is 'IS prcrf related  offer or not'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.CONDITION is 'marked for complex price '
        - comment on column DC_CONFIG_OFFER_OTC_RENT.ACCT_ITEM_TYPE_NAME is 'charge item'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.BENEFIT_DURATION_UNIT is 'mandatory when have benefit,BENEFIT_DURATION_UNIT in(C,D,S,M) or NULL)'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.NEW_OFFER_ID is 'COULD BE UPDATED BEFORE INSERT INTO BUSI TABLE'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.PRICE_PLAN_ID is 'COULD BE UPDATED BEFORE INSERT INTO BUSI TABLE'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.RENEW_PRIORITY is 'In what order do programs renew the offers of subscribers,
                                                            when subscribers dont have enough balance to renew all the rent offers'
        - comment on column DC_CONFIG_OFFER_OTC_RENT.NEW_ACCT_RES_ID    is  'acct_res_id in WhaleCloud system,no need to fill in '
        - comment on column DC_CONFIG_OFFER_OTC_RENT.NEW_ACCT_ITEM_TYPE_ID is 'acct_item_type_id in WhaleCloud system,no need to fill in '

    DC_CONFIG_TMP_MV_TARIFF:
        - |

            create table DC_CONFIG_TMP_MV_TARIFF
            (   ID                   NUMBER,
                TMCODE               NUMBER,
                TMDES                VARCHAR2(200),
                TM_SHDES             VARCHAR2(200),
                MAXRI_VSDATE         VARCHAR2(200),
                RICODE               NUMBER,
                RIDES                VARCHAR2(200),
                INTERVAL_LENGTH      NUMBER,
                UNITS                VARCHAR2(200),
                PRICE               NUMBER(20),
                PRICE_VAT_INCL       NUMBER(20),
                CURRENCY             VARCHAR2(200),
                TTCODE               NUMBER,
                PERIOD_DES           VARCHAR2(200),
                CALL_DETAILS_DES     VARCHAR2(200),
                PARAMETER_ROWNUM     NUMBER,
                SNCODE               NUMBER,
                SPCODE               NUMBER,
                GVCODE               NUMBER,
                ZNCODE               NUMBER,
                ZP_DES               VARCHAR2(200),
                ZN_DES               VARCHAR2(200),
                ZN_SHDES             NUMBER,
                GVZN_SHDES           VARCHAR2(200),
                SRC                  NUMBER,
                CNT                  NUMBER,
                PULSE_INTERVAL       NUMBER,
                RATE_TYPE_ID         NUMBER,
                USAGE_TYPE_ID        NUMBER,
                USAGE_TYPE_DES       VARCHAR2(200),
                CALL_TYPE            NUMBER,
                RATE_PACK_ELEMENT_ID NUMBER
            )

create_list:
    DC_CONFIG_OFFER_OTC_RENT:
        - OTC
        - V20191119
        - table
        - VALUE_LIST:
            EVENT_TYPE:
                TYPE: list
                SOURCE: OTC,RENT
            OFFER_INST_VALID_UNIT:
                TYPE: list
                SOURCE: day,month,year,week,Billing Cycle
            ADVANCED_NOTIFICATION:
                TYPE: list
                SOURCE: Y,N
            IS_PCRF:
                TYPE: list
                SOURCE: Y,N
            RECURRING_RE_TYPE:
                TYPE: sql
                SOURCE: SELECT RECURRING_RE_TYPE_NAME from CPC.RECURRING_RE_TYPE
            IS_LIST_PRICE:
                TYPE: list
                SOURCE: Y,N
            BENEFIT_DURATION_UNIT:
                TYPE: list
                SOURCE: S,D,C,M
            RENT_BENEFIT_EXTENSION_RULE:
                TYPE: list
                SOURCE: M,N

    DC_CONFIG_TMP_MV_TARIFF:
        - OTC
        - V20190815
        - table