create:
  DC_IC_GM_SPU:
    - |
      create table DC_IC_GM_SPU
      (
          VENDER_NAME      VARCHAR2(255),
          BRAND_NAME VARCHAR2(64),
          SPU_NAME VARCHAR2(255),
          SPU_CODE VARCHAR2(60),
          SPU_GROUP_NAME VARCHAR2(255),
          STOCK_TYPE  VARCHAR2(30)
      )
    - comment on table DC_IC_GM_SPU is  'TEMPLATE RELATIONSHIP WITH OFFER'
    - comment on column DC_IC_GM_SPU.VENDER_NAME is  'VENDER_NAME'
    - comment on column DC_IC_GM_SPU.BRAND_NAME is  'BRAND_NAME'
    - comment on column DC_IC_GM_SPU.SPU_NAME is  'SPU_NAME'
    - comment on column DC_IC_GM_SPU.SPU_CODE is  'SPU_CODE'
    - comment on column DC_IC_GM_SPU.SPU_GROUP_NAME is  'SPU_GROUP_NAME'
    - comment on column DC_IC_GM_SPU.STOCK_TYPE is  'I stand for Instanceï¼ŒN stand for Quantity'

  DC_IC_GM_SPU_ATTR_VALUE:
    - |
      create table DC_IC_GM_SPU_ATTR_VALUE
      (
          SPU_NAME  VARCHAR2(255),
          ATTR_NBR  VARCHAR2(2000),
          ATTR_VALUE VARCHAR2(250),
          GROUP_NAME VARCHAR2(255)
      )
    - comment on table DC_IC_GM_SPU_ATTR_VALUE is  'Advince Template'
    - comment on column DC_IC_GM_SPU_ATTR_VALUE.SPU_NAME is  'SPU_NAME'
    - comment on column DC_IC_GM_SPU_ATTR_VALUE.ATTR_NBR is  'ATTR_NBR'
    - comment on column DC_IC_GM_SPU_ATTR_VALUE.ATTR_VALUE is  'ATTR_VALUE'
    - comment on column DC_IC_GM_SPU_ATTR_VALUE.GROUP_NAME is  'GROUP_NAME'

  DC_IC_GM_MODEL:
    - |
      create table DC_IC_GM_MODEL
      (
          SKU_NAME  VARCHAR2(255),
          SKU_CODE  VARCHAR2(60),
          SPU_NAME VARCHAR2(255)
      )
    - comment on table DC_IC_GM_MODEL is  'MSG Parameter Detail Info'
    - comment on column DC_IC_GM_MODEL.SKU_NAME is  'SKU_NAME'
    - comment on column DC_IC_GM_MODEL.SKU_CODE is  'SKU_CODE'
    - comment on column DC_IC_GM_MODEL.SPU_NAME is  'SPU_NAME'

  DC_ATTR_VALUE:
    - |
      create table DC_ATTR_VALUE
      (
          ATTR_VALUE_NAME    VARCHAR2(250),
          ATTR_VALUE         VARCHAR2(4000),
          ATTR_VALUE_SORT    VARCHAR2(3),
          ATTR_NBR  VARCHAR2(50),
          ATTR_VALUE_CODE    VARCHAR2(100)
      )

  DC_IC_GM_CATG_ATTR_GROUP:
    - |
      create table DC_IC_GM_CATG_ATTR_GROUP
      (
          GROUP_ID      NUMBER(6),
          GOODS_CATG_NAME VARCHAR2(255),
          GROUP_NAME    VARCHAR2(255),
          DISPLAY_ORDER NUMBER(3)
      )

  DC_IC_GM_CATG_ATTR:
    - |
      create table DC_IC_GM_CATG_ATTR
      (
          GOODS_CATG_NAME VARCHAR2(255),
          GROUP_NAME    VARCHAR2(255),
          ATTR_NBR  VARCHAR2(50),
          DISPLAY_ORDER NUMBER(3)
      )

  DC_IC_GM_CATG_SPEC:
    - |
      create table DC_IC_GM_CATG_SPEC
      (
          GOODS_CATG_NAME VARCHAR2(255),
          ATTR_NBR  VARCHAR2(50),
          DISPLAY_ORDER NUMBER(3)
      )

  DC_IC_GM_MODEL_ATTR_VALUE:
    - |
      create table DC_IC_GM_MODEL_ATTR_VALUE
      (
          SKU_NAME   VARCHAR2(255),
          ATTR_NBR   VARCHAR2(2000),
          ATTR_VALUE VARCHAR2(250)
      )

  DC_IC_GM_VENDOR:
    - |
      create table DC_IC_GM_VENDOR
      (
          VENDOR_ID   NUMBER(6)     not null,
          VENDOR_NAME VARCHAR2(255) not null,
          VENDOR_CODE VARCHAR2(60)  not null
      )

  DC_IC_GM_BRAND:
    - |
      create table DC_IC_GM_BRAND
      (
          BRAND_ID   NUMBER(9)    not null,
          VENDOR_CODE  VARCHAR2(60) not null,
          BRAND_NAME VARCHAR2(60) not null,
          BRAND_CODE VARCHAR2(60)
      )

create_list:
  DC_IC_GM_SPU:
    - SIC
    - V20200811
    - table

  DC_IC_GM_SPU_ATTR_VALUE:
    - SIC
    - V20200811
    - table

  DC_IC_GM_MODEL:
    - SIC
    - V20200811
    - table

  DC_ATTR_VALUE:
    - CPC
    - V20200811
    - table

  DC_IC_GM_CATG_ATTR_GROUP:
    - SIC
    - V20200812
    - table

  DC_IC_GM_CATG_ATTR:
    - SIC
    - V20200812
    - table

  DC_IC_GM_CATG_SPEC:
    - SIC
    - V20200813
    - table

  DC_IC_GM_MODEL_ATTR_VALUE:
    - SIC
    - V20200814
    - table

  DC_IC_GM_VENDOR:
    - SIC
    - V20200817
    - table


  DC_IC_GM_BRAND:
    - SIC
    - V20200817
    - table