#所有的文本的资源文件
#语言编号: 1 中文，2. 英语
#初步考虑是：A00001， A表示界面使用的，B表示日志使用的，后面有需要就再说
#编号A000 是工具本身的主界面的
#A010-A019 是File/初始化菜单专用的； A011-连接数据库，A012-选择项目/环境，A013-内部检查功能，A014初始化配置环境中间表
#A020-A029 配置中间表； A021-检查所有中间表,A022-中间表生成模板，A023-excel导入中间表
#A030-A039 数据配置；  A032-检查配置好的数据
#A040-A049 数据发布；  A048-查看配置数据包
#A050-A059 其他功能;  A058-Python规范检查
#A080-A089 About菜单； A081-About页面
A000:
  A000_A00000:
    1: '数据配置工具'
    2: 'Data Configuration Tools'

  A000_A00001:
    1: '已经连接上数据库了'
    2: 'Already connected to Database'

  A000_A00002:
    1: '没有连接任何数据库'
    2: 'Not connect DataBase'

  A000_A00003:
    1: '本工具的版本'
    2: 'DCToolsVersion'

  A000_A00004:
    1: '工具的运行模式'
    2: 'ToolModel'

  A000_A00005:
    1: '配置数据发布模式'
    2: 'Data Dispatch Model'

  A000_A00006:
    1: '工具开发者&数据配置者模式'
    2: 'Tool Developing/Configuration Model'

  A000_A00007:
    1: '有窗口已经打开了。'
    2: 'Already open the Function.'

  A000_M00001:
    1: '初始化'
    2: 'File'

  A000_M00002:
    1: '连接数据库'
    2: 'Connect DB'

  A000_M00003:
    1: '选择项目/环境'
    2: 'Project'

  A000_M00004:
    1: '工具配置文件内部检查'
    2: 'Internal Check'

  A000_M00005:
    1: '初始化配置环境中间表'
    2: 'InitConfigure Table'

  A000_M00006:
    1: '清空日志文件'
    2: 'Logs Clear'

  A000_M00007:
    1: '日志文件另存为'
    2: 'Logs Save As'

  A000_M00008:
    1: '退出软件'
    2: 'Close APP'

  A000_M00010:
    1: '配置中间表'
    2: 'MiddleTable'

  A000_M00011:
    1: '检查所有中间表数据'
    2: 'AllMiddleTableCheck'

  A000_M00012:
    1: '用中间表生成配置模板'
    2: 'Export Template'

  A000_M00013:
    1: '从Excel模板导入数据到中间表'
    2: 'Input from Excel'

  A000_M00020:
    1: '数据配置'
    2: 'Configure'

  A000_M00021:
    1: '具体的数据配置动作'
    2: 'Data Configure'

  A000_M00022:
    1: '检查配置好的数据'
    2: 'AfterConfigureDataCheck'

  A000_M00023:
    1: '从数据库中导出数据为Excel'
    2: 'ExportToExcelFile'

  A000_M00024:
    1: '回滚配置数据'
    2: 'Rollback Data'

  A000_M00030:
    1: '数据发布'
    2: 'Data Sync'

  A000_M00031:
    1: '导出数据'
    2: 'Export Data'

  A000_M00032:
    1: '导入数据'
    2: 'Import Data'

  A000_M00033:
    1: '导出表结构'
    2: 'Export Tables Structure'

  A000_M00034:
    1: '比较表结构'
    2: 'Compare Tables Structure'

  A000_M00035:
    1: '增量数据发布'
    2: 'Increment Release'

  A000_M00036:
    1: '查询配置数据导入历史'
    2: 'Query Import His'

  A000_M00037:
    1: '查看配置数据包中的数据'
    2: 'Check DC Package'

  A000_M00038:
    1: '生成增量包'
    2: 'Export Incremental Package'

  A000_M00039:
    1: '导入增量包'
    2: 'Import Incremental Data'

  A000_M00040:
    1: '其他功能'
    2: 'Other Function'

  A000_M00041:
    1: 'Python脚本优化分析'
    2: 'Optimization Python'

  A000_M00042:
    1: '导出分拣'
    2: 'Export Workflow'

  A000_M00043:
    1: '导入分拣'
    2: 'Input Workflow'

  A000_M00044:
    1: '静态数据量比较'
    2: 'Static DataCompare'

  A000_M00045:
    1: '序列管理'
    2: 'Sequence Manage'

  A000_M00046:
    1: 'DCC/CCR/CCA解析'
    2: 'DCC Decoder'

  A000_M00047:
    1: '话单解析'
    2: 'CDR Decoder'

  A000_M00048:
    1: '系统内的Python脚本规范检查'
    2: 'Python Check'

  A000_M00050:
    1: '数据配置菜单'
    2: 'Data Configure'

  A000_M00060:
    1: '关于'
    2: 'About'

  A000_M00061:
    1: '系统关于'
    2: 'SystemAbout1'

A013:
  A013_A00001:
    1: '检查配置文件主界面'
    2: 'Internal Check configuration File'

  A013_A00002:
    1: '开始内部检查'
    2: 'Check'

  A013_A00003:
    1: '检查整个工具'
    2: 'Check All the Tools Script'

A032:
  A032_A00001:
    1: '检查系统中的配置数据'
    2: 'User Script Check Configured Data'

  A032_A00002:
    1: '检查条件'
    2: 'Condition'

  A032_A00003:
    1: '检查方式'
    2: 'Check Type'

  A032_A00004:
    1: '按顺序检查所有内容'
    2: 'Check All'

  A032_A00005:
    1: '按照Topic检查'
    2: 'Base on Topic'

  A032_A00006:
    1: '按照文件检查'
    2: 'Base on File'

  A032_A00007:
    1: '按照用户检查'
    2: 'Base on DBUser'

  A032_A00008:
    1: '数据库用户名'
    2: 'DB User'

  A032_A00009:
    1: '文件名列表'
    2: 'File List'

  A032_A00010:
    1: 'Topic列表'
    2: 'Topic List'

  A032_A00011:
    1: 'Title列表'
    2: 'Title List'

  A032_A00012:
    1: '清空选项'
    2: 'Clear Condition'

  A032_A00013:
    1: '开始检查'
    2: 'Check'

  A032_A00014:
    1: '导出检查结果'
    2: 'Export Result'

  A032_A00015:
    1: '上一步'
    2: 'PreActionGUI'

  A032_A00016:
    1: '获取所有条目'
    2: 'Get All Title'

  A032_A00017:
    1: '关闭'
    2: 'Close'

  A032_A00018:
    1: '检查结果不插入数据库'
    2: 'Check Result do not insert To DB'

  A032_A01001:
    1: '获取所有的检查条目'
    2: 'Get all check item'

  A032_A01002:
    1: '筛选条件'
    2: 'Filter'

  A032_A01003:
    1: '按照数据库类型过滤'
    2: 'DataBase Type'

  A032_A01004:
    1: '按照系统的版本过滤'
    2: 'System Version'

  A032_A01005:
    1: '按照Topic过滤'
    2: 'Topic'

  A032_A01006:
    1: '清空选项'
    2: 'Clear condition'

  A032_A01007:
    1: '显示全部'
    2: 'Show All'

  A032_A01008:
    1: '同步到本版本'
    2: 'Sync to current version'

  A032_A01009:
    1: '关闭'
    2: 'Close'

  A032_A01010:
    1: '没有选择任何DataBase'
    2: 'All DataBase'

  A032_A01011:
    1: '没有选择任何Version'
    2: 'All Version'

  A032_A01012:
    1: '没有选择任何Topic'
    2: 'All Topic'

  A032_A01013:
    1: '总共：%s 条'
    2: 'Total: %s. '

  A032_A01014:
    1: '选中: %s 行'
    2: 'Select: %s. '

A048:
  A048_A00001:
    1: '查看配置数据包中的数据'
    2: 'Read Configuration Data Package Data'

  A048_A00002:
    1: '配置数据包'
    2: 'Configuration Data'

  A048_A00003:
    1: 数据库用户
    2: UserList

  A048_A00004:
    1: 数据库表
    2: TableList

  A048_A00005:
    1: 查找
    2: Search

  A048_A00006:
    1: 打开
    2: Open

A058:
  A058_A00001:
    1: '检查系统中的Python脚本是否符合规范'
    2: 'Check cvBS System Python'

  A058_A00002:
    1: '检查的表'
    2: 'Check Table'

  A058_A00003:
    1: '检查的规则'
    2: 'Check Rule'

  A058_A00004:
    1: '开始检查'
    2: 'Start Check'

  A058_A00005:
    1: '导出成excel'
    2: 'Export'

  A058_A00006:
    1: '本次总共发现: '
    2: 'Total find Number: '

A081:
  A081_A00001:
    1: '关于'
    2: 'About'

  A081_A00002:
    1: '这是在线帮助网址: <a href="https://www.yuque.com/glcwxi/sg5uil/gniqvo?singleDoc" > 网址1 </a>'
    2: 'This is online help: <a href="https://www.yuque.com/glcwxi/sg5uil/gniqvo?singleDoc" > WebUrl'

  A081_A00003:
    1: '有相关问题，请加钉钉群联系帮助：35345739'
    2: 'If have any concern, DingTalk Group Get help: 35345739'

  A081_A00004:
    1: "Copyright (C)2020-2023 Whale Cloud Technology Co.,Ltd, All rights reserved 数据管理/配置团队"
    2: 'Copyright (C)2020-2023 Whale Cloud Technology Co.,Ltd, All rights reserved DC Team'

  A081_A00005:
    1: '工具的更新历史: <a href="https://www.yuque.com/glcwxi/sg5uil/mgrtz2?singleDoc" > 网址2 </a>'
    2: 'Tools Version: <a href="https://www.yuque.com/glcwxi/sg5uil/mgrtz2?singleDoc" > List </a>'
