UserList:
  cc

Data:
  1.offer_mapping:
    "select distinct t1.productkey,
    t1.productcode as productid,
    t1.cbs_productname as productname,
    t2.offer_id,
    t2.offer_code,
    t2.offer_type,
    t3.subs_plan_id,
    t3.indep_prod_spec_id,
    case
    when t4.rental_cycle != '25_OneOffCycle' and
    t4.max_rentcycle_times != 1 and t2.offer_type = 4 then
    'Y'
    else
    ''
    end as is_recurring_offer,
    case
    when t1.servicedetails = 'FN' then
    'Y'
    else
    ''
    end as IS_FELLOW_NBR_OFFER,
    decode(t1.servicedetails, 'FN', t1.productcode, '') as FELLOW_NBR_ID
    from mid_ncell_productlist    t1,
    offer                    t2,
    subs_plan                t3,
    mid_ncell_rental_product t4
    where t1.productcode = t2.offer_code
    and t2.offer_id = t3.subs_plan_id(+)
    and t2.state = 'A'
    and t2.offer_id = t4.productkey(+)
    order by t1.productkey"
  7.Mainoffer_IPP:
    "select t1.offer_id,
            t1.offer_name       as vas_offer_name,
            t1.offer_code,
            t1.offer_type,
            t3.offer_group_name,
            t6.offer_name       as subs_plan_name,
            t8.paid_flag,
            t9.offer_name       as main_product,
            t11.offer_catg_name
       from offer                  t1,
            offer_group_mem        t2,
            offer_group            t3,
            subs_plan_offer_select t4,
            offer_ver              t5,
            offer                  t6,
            subs_plan              t7,
            indep_prod_spec        t8,
            offer                  t9,
            offer_catg_mem         t10,
            offer_catg             t11
      where t1.offer_id = t2.offer_id
        and t1.state = 'A'
        and t2.offer_group_id = t3.offer_group_id
        and t3.offer_group_id = t4.offer_group_id
        and t4.offer_ver_id = t5.offer_ver_id
        and t5.offer_id = t6.offer_id
        and t6.offer_type = '7'
        and t6.state = 'A'
        and t6.offer_id = t7.subs_plan_id
        and t7.indep_prod_spec_id = t8.indep_prod_spec_id
        and t8.indep_prod_spec_id = t9.offer_id
        and t9.offer_type = '2'
        and t9.state = 'A'
           /*and t6.offer_code='R59069'*/
        and t9.offer_id = t10.offer_id
        and t10.offer_catg_id = t11.offer_catg_id
      order by t8.paid_flag"
  8.MainOffer_rel:
    "select t1.offer_id   as ori_subsplan_id,
    t1.offer_name as ori_subsplan_name,
    t3.offer_id   as dest_subsplan_id,
    t3.offer_name as dest_subsplan_name
    from offer t1, offer_rela t2, offer t3
    where t1.offer_type = 7
    and t1.state = 'A'
    and t1.offer_id = t2.ori_offer_id
    and t2.rela_type = '3'
    and t3.offer_id = t2.dest_offer_id
    and t3.offer_type = '7'
    and t3.state = 'A'"
  10.Usage_tarrif:
    "select o.offer_id,
    o.offer_name,
    o.eff_date,
    o.exp_date,
    o.offer_code,
    ov.state,
    ov.eff_date ov_eff_date,
    ov.exp_date ov_exp_date,
    rpp.offer_ver_id,
    ppt.comments price_plan_type,
    pp.priority,
    re.re_id,
    re.re_name,
    rp.rate_plan_id,
    rp.mapping_exit,
    pv.price_ver_id,
    pv.mapping_id,
    substr(mapp.zone_info, 0, instr(zone_info, ',', 1, 1) - 1) as feature_name1,
    substr(mapp.zone_info,
    instr(mapp.zone_info, ',', 1, 1) + 1,
    instr(mapp.zone_info, ',', 1, 2) -
    instr(mapp.zone_info, ',', 1, 1) - 1) as zone_map1,
    substr(mapp.zone_info,
    instr(mapp.zone_info, ',', 1, 2) + 1,
    decode(instr(mapp.zone_info, ',', 1, 3),
    0,
    LENGTH(mapp.zone_info) + 1,
    instr(mapp.zone_info, ',', 1, 3)) -
    instr(mapp.zone_info, ',', 1, 2) - 1) as zone1,
    SUBSTR(mapp.zone_info,
    instr(mapp.zone_info, ',', 1, 3) + 1,
    instr(mapp.zone_info, ',', 1, 4) -
    instr(mapp.zone_info, ',', 1, 3) - 1) AS feature_name2,
    SUBSTR(mapp.zone_info,
    instr(mapp.zone_info, ',', 1, 4) + 1,
    instr(mapp.zone_info, ',', 1, 5) -
    instr(mapp.zone_info, ',', 1, 4) - 1) AS zone_map2,
    substr(mapp.zone_info,
    decode(instr(mapp.zone_info, ',', 1, 5),
    0,
    1000,
    instr(mapp.zone_info, ',', 1, 5) + 1),
    decode(instr(mapp.zone_info, ',', 1, 6),
    0,
    LENGTH(mapp.zone_info) + 1)) as zone2,
    p.price_id,
    p.price_name,
    rvp.ref_value_id ref_value_price,
    to_char(rvp.value_string * 0.00000001) tariffprice,
    p.rum,
    ra.re_attr_name,
    rva.ref_value_id ref_value_acct_item_id,
    ait.acct_item_type_id,
    ait.acct_item_type_name,
    tp.time_span_up_id,
    tp.time_span_id,
    tp.time_span_name,
    tp.priority time_priority,
    tp.tariffprice time_tariffprice,
    tp.rum time_rum,
    upr.python_rule,
    tpd.param_name paramter_name,
    rt.re_attr_name paramter_re_attr,
    tpc.col_name parameter_col_name,
    acm_sum.resource_name,
    acm_sum.eff_value,
    acm_sum.exp_value,
    acm_sum.acm_price,
    acm_sum.rum acm_rum
    from offer o,
    price_plan pp,
    SUBS_PRICE_PLAN spp,
    OFFER_VER ov,
    price_plan_type ppt,
    RE_PRICE_PLAN rpp,
    re re,
    rate_plan rp,
    rate_plan_mapping rpm,
    price_ver pv,
    price p,
    ref_value rvp,
    ref_value rva,
    re_attr ra,
    acct_item_type ait,
    TABLE_PARAM_DEFINE tpd,
    TABLE_PARAM_COLUMN tpc,
    re_attr rt,
    (select mapp.mapping_id, to_char(wm_concat(mapp.zone_info)) zone_info
    from (select mu.mapping_id,
    ra.re_attr_name || ',' || zm.zone_map_name || ',' ||
    z.zone_name zone_info
    from rate_plan_zone rpz,
    MAPPING        m,
    MAPPING_UNIT   mu,
    re_attr        ra,
    zone_map       zm,
    zone           z
    where rpz.rate_plan_id = m.rate_plan_id
    and mu.mapping_id = m.mapping_id
    and mu.rate_plan_zone_id = rpz.rate_plan_zone_id
    and rpz.mapping_src_value = ra.re_attr
    and rpz.mapping_des_value = zm.zone_map_id
    and rpz.mapping_src_type = 1
    and mu.mapping_value = z.zone_id
    order by rpz.priority) mapp
    group by mapp.mapping_id) mapp,
    (select tsp.time_span_up_id,
    ts.time_span_id,
    tsp.up_id,
    tsp.priority,
    ts.time_span_name,
    to_char(rvt.value_string * 0.00000001) tariffprice,
    tsp.rum
    from time_span_up tsp, time_span ts, ref_value rvt
    where tsp.time_span_id = ts.time_span_id
    and tsp.rate = rvt.ref_value_id) tp,
    (select up.up_id, to_char(ur.rule_script) python_rule
    from up up, up_rule ur
    where up.up_id = ur.up_id) upr,
    (select a.up_id,
    d.resource_name,
    a.eff_value,
    a.exp_value,
    b.value_string * 0.00000001 acm_price,
    a.rum
    from acm_up a, ref_value b, ref_value c, ratable_resource d
    where a.rate = b.ref_value_id
    and b.ref_value_type = '1'
    and a.ref_value_id = c.ref_value_id
    and c.ref_value_type = '5'
    and c.value_string = d.resource_id
    order by up_id, resource_name, eff_value) acm_sum
    where o.offer_id = pp.price_plan_id
    and spp.price_plan_id = pp.price_plan_id
    and ov.offer_id = o.offer_id
    and spp.price_plan_type = ppt.price_plan_type
    and rpp.offer_ver_id = ov.offer_ver_id
    and rpp.re_id = re.re_id
    and re.re_type = '1'
    and rpm.re_id = rpp.re_id
    and rpm.offer_ver_id = ov.offer_ver_id
    and rp.rate_plan_id = rpm.rate_plan_id
    and pv.rate_plan_id = rp.rate_plan_id
    and pv.mapping_id = mapp.mapping_id(+)
    and p.price_ver_id = pv.price_ver_id
    and p.value = rvp.ref_value_id
    and rvp.ref_value_type in ('1', '3')
    and p.ACCT_ITEM_TYPE_ID_PARAM = rva.ref_value_id
    and rva.ref_value_type = '8'
    and p.re_attr = ra.re_attr
    and rva.value_string = ait.acct_item_type_id(+)
    and p.price_id = tp.up_id(+)
    and p.price_id = upr.up_id(+)
    and rvp.table_param_id = tpd.table_param_id(+)
    and tpd.table_param_id = tpc.table_param_id(+)
    and rvp.col_id = tpc.col_id(+)
    and rvp.re_attr = rt.re_attr(+)
    and p.price_id = acm_sum.up_id(+)
    order by o.offer_name, re.re_name,pv.mapping_id,acm_sum.resource_name,acm_sum.eff_value"