UserList:
  drm

BoBNeed:
  51_DRM.ORGANIZATION:
    "select * from ORGANIZATION"
  52_DRM.STAFF:
    "select * from STAFF"
  53_DRM.DRM_ORGANIZATION_EXT:
    "select * from DRM_ORGANIZATION_EXT"
  54_DRM.DRM_ORG_ATTR_VAL:
    "select * from DRM_ORG_ATTR_VAL"
  55_DRM.DRM_ATTR_VAL:
    "select * from DRM_ATTR_VAL"
  56_DRM.DRM_ATTR:
    "select * from DRM_ATTR"
  57_DRM.DRM_ORG_CHNL_MGR:
    "select * from DRM_ORG_CHNL_MGR"
  58_DRM.DRM_ORG_SUBTYPE_RELA:
    "select * from DRM_ORG_SUBTYPE_RELA"
  59_DRM.DRM_ORGANIZATION_THIRD:
    "select * from DRM_ORGANIZATION_THIRD"
  60_DRM.DRM_PROPERTY_CONFIG:
    "select * from DRM_PROPERTY_CONFIG"
  61_DRM.DRM_PROPERTY_CONFIG_VALUE:
    "select * from DRM_PROPERTY_CONFIG_VALUE"













