A002:
  exportcpc:
    UserList:
      cpc
    BoBNeed:
      99_CPC.CBEC_ACCT_ITEM_TYPE:
        "select * from cbec_ACCT_ITEM_TYPE"

      98_CPC.313123123:
        "select * from cbec_ACCT_ITEM_TYPE"

    ABNeed:
      97_CPC.CBEC_ACCT_ITEM_TYPE:
        "select * from cbec_ACCT_ITEM_TYPE"

      96_CPC.313123123:
        "select * from cbec_ACCT_ITEM_TYPE"

  cicexport:
    UserList:
      cic

    CICExport:
      200. CIC ALL:
        "SELECT
             ctc.content_id,
             ctc.LANG_ID,
             ce.EVENT_CODE,
             cef.FLOW_NAME,
             cmt.TEMPLATE_NAME,
             ctc.subject,
             ctc.MSG_TEMPLATE,
             ctc.html_template
         FROM
             cic_process cp,
             cic_action_process cap,
             cic_msg_template cmt,
             cic_template_content ctc,
             cic_flow_version cfv,
             cic_event_flow cef,
             cic_event ce,
             cic_template_label ctl
         WHERE
             cap.process_id = cp.process_id
                 AND cmt.template_id = cap.template_id
                 AND ctc.template_id = cap.template_id
                 AND cfv.flow_version_id = cp.flow_version_id
                 AND cef.event_flow_id = cfv.event_flow_id
                 AND ce.event_id = cef.inter_event_id
                 AND ctl.template_id = cmt.template_id
                 AND cfv.STATE = 'P'"
