UserList:
  ftf

FTFTopic:
  01. UserList:
    "select
      a.org_code ,
      b.staff_id,
      b.staff_name,
      b.email,
      b.phone,
      b.staff_code,
      c.user_name,
      c.user_Code
    from
      bfm_org a,
      bfm_staff b,
      bfm_user c,
      bfm_staff_org d
    where
      a.org_id=d.org_id
      and b.staff_id=d.staff_id
      and c.user_id=d.staff_id
      and a.org_id !=1
      and c.user_id>3000 "
  02. orglist:
    "select
      org_id,org_code
    from
      bfm_org where org_id >1000"

  001.ORG_STAFF:
    "select a.org_id, a.org_name, a.org_code, c.staff_id, c.staff_name, c.email, c.phone
          from bfm_org a, bfm_staff_org b, bfm_staff c
          where a.org_id = b.org_id
          and b.staff_id = c.staff_id
          and a.org_id>1000
          order by org_id"

  002.ORG_JOB:
    "select a.org_id, a.org_name, a.org_code, c.job_id,c.job_name
          from bfm_org a, BFM_ORG_JOB b, bfm_job c
          where a.org_id = b.org_id
          and b.job_id = c.job_id
          order by org_id"

  003.USER_ROLE:
    "select a.user_id, a.user_name, a.user_code,c.role_id,c.role_name, c.role_code
     from bfm_user a, bfm_user_role b, bfm_role c
     where a.user_id=b.user_id
     and b.role_id = c.role_id"

  004.ROLE_PORTAL:
    "select c.portal_id, c.portal_name, a.role_id, a.role_name, a.role_code
     from bfm_role a, bfm_role_portal b, bfm_portal c
     where a.role_id=b.role_id
     and b.portal_id = c.portal_id
     order by portal_id"

  005.MENU_PORTAL:
    "select a.menu_id,d.PRIV_NAME,d.PRIV_CODE, c.portal_id, c.PORTAL_NAME
     from bfm_menu a, bfm_portal_menu b, bfm_portal c, bfm_priv d
     where a.MENU_ID = b.PARTY_ID
     and b.STATE <> 'X'
     and b.PORTAL_ID = c.PORTAL_ID
     and a.menu_id= d.PRIV_ID
     order by c.PORTAL_ID"


Guogeng:
  01.BFM_ORG:
    "select * from BFM_ORG"
  02.BFM_STAFF:
    "select * from BFM_STAFF"
  03.BFM_USER:
    "select * from BFM_USER"
  04.BFM_USER_SP:
    "select * from BFM_USER_SP"
  05.BFM_ROLE:
    "select * from BFM_ROLE"
  06.BFM_JOB:
    "select * from BFM_JOB"
  07.BFM_STAFF_JOB:
    "select * from BFM_STAFF_JOB"
  08.BFM_STAFF_ORG:
    "select * from BFM_STAFF_ORG"
  09.BFM_ORG_JOB:
    "select * from BFM_ORG_JOB"
  10.BFM_JOB_ROLE:
    "select * from BFM_JOB_ROLE"
  11.BFM_USER_ROLE:
    "select * from BFM_USER_ROLE"
  12.BFM_PRIV:
    "select * from BFM_PRIV"
  13.BFM_PORTAL_MENU:
    "select * from BFM_PORTAL_MENU"
  14.BFM_USER_PORTAL:
    "select * from BFM_USER_PORTAL"
  15.BFM_ROLE_DATA_PRIV:
    "select * from BFM_ROLE_DATA_PRIV"
  16.BFM_PORTLETS:
    "select * from BFM_PORTLETS"
  17.BFM_COMPPNENT_PRIV:
    "select * from bfm_component_priv"
  18.BFM_USER_DATA_PRIV:
    "select * from BFM_USER_DATA_PRIV"
  21.BFM_ORG_TYPE:
    "select * from BFM_ORG_TYPE"
  22.BFM_LAYOUT_DEF:
    "select * from BFM_LAYOUT_DEF"
  23.BFM_USER_LAYOUT:
    "select * from BFM_USER_LAYOUT"
  24.BFM_ORGTYPE_JOB:
    "select * from BFM_ORGTYPE_JOB"

