UserList:
    cpc

CPC:
    1. gl and acct_item:
        "SELECT DISTINCT g.GL_ID, g.GL_CODE, g.GL_NAME, gt.GL_TYPE_NAME, ait.ACCT_ITEM_TYPE_ID, ait.ACCT_ITEM_TYPE_CODE, ait.ACCT_ITEM_TYPE_NAME
           FROM cbec_gl g, cbec_gl_acct_item_type gait, cbec_acct_item_type ait, cbec_gl_type gt
          WHERE g.GL_ID = gait.GL_ID
            AND gait.ACCT_ITEM_TYPE_ID = ait.ACCT_ITEM_TYPE_ID
            AND g.GL_TYPE_ID = gt.GL_TYPE_ID"

    2. offer and OTC acct_item:
        "SELECT DISTINCT t.*
           FROM (
         SELECT DISTINCT op.OFFER_ID, o.key_str2 offer_name, op.OFFER_ID offer_code, ait.ACCT_ITEM_TYPE_CODE, ait.ACCT_ITEM_TYPE_NAME,
                'OTC' fee_type, CASE o.key_str3 WHEN 'GSM_POST' THEN 'GSM postpaid' WHEN 'Postpaid' THEN 'GSM postpaid' WHEN 'Prepaid' THEN 'GSM Prepaid' ELSE o.key_str3 END BUSI_TYPE,
                REPLACE(REPLACE(REPLACE(o.key_str1, ' 1 Year', ''), ' 2 Year', ''), ' 3 Year', '') lagcy_offer_code
           FROM cpc_otc_offer_price op, cpc_otc_price_plan pp, cpc_otc_price_plan_ver ppv,
                cpc_otc_price p, cpc_otc_price_rate pr, cbec_acct_item_type ait, dc_tariff_id_mapping o
          WHERE op.PRICE_PLAN_ID = pp.PRICE_PLAN_ID
            AND pp.PRICE_PLAN_ID = ppv.PRICE_PLAN_ID
            AND ppv.PRICE_PLAN_VER_ID = p.PRICE_PLAN_VER_ID
            AND p.PRICE_ID = pr.PRICE_ID
            AND (ppv.EXP_DATE IS NULL OR ppv.EXP_DATE > NOW())
            AND pr.ACCT_ITEM_TYPE_ID = ait.ACCT_ITEM_TYPE_ID
            AND op.OFFER_ID = o.target_id
            AND o.map_type = 'DPP_OFFER_ID'
         UNION ALL
         SELECT DISTINCT op.OFFER_ID, o.key_str2 offer_name, op.OFFER_ID offer_code, ait.ACCT_ITEM_TYPE_CODE, ait.ACCT_ITEM_TYPE_NAME,
                'OTC', 'GSM postpaid', o.key_str1 lagcy_offer_code
           FROM cpc_otc_offer_price op, cpc_otc_price_plan pp, cpc_otc_price_plan_ver ppv,
                cpc_otc_price p, cpc_otc_price_rate pr, cbec_acct_item_type ait, dc_tariff_id_mapping o
          WHERE op.PRICE_PLAN_ID = pp.PRICE_PLAN_ID
            AND pp.PRICE_PLAN_ID = ppv.PRICE_PLAN_ID
            AND ppv.PRICE_PLAN_VER_ID = p.PRICE_PLAN_VER_ID
            AND p.PRICE_ID = pr.PRICE_ID
            AND (ppv.EXP_DATE IS NULL OR ppv.EXP_DATE > NOW())
            AND pr.ACCT_ITEM_TYPE_ID = ait.ACCT_ITEM_TYPE_ID
            AND op.OFFER_ID = o.target_id
            AND o.map_type = 'IPP_OFFER_ID_POST'
         UNION ALL
         SELECT DISTINCT op.OFFER_ID, o.key_str1 offer_name, op.OFFER_ID offer_code, ait.ACCT_ITEM_TYPE_CODE, ait.ACCT_ITEM_TYPE_NAME,
                'OTC', 'GSM Prepaid', o.target_val lagcy_offer_code
           FROM cpc_otc_offer_price op, cpc_otc_price_plan pp, cpc_otc_price_plan_ver ppv,
                cpc_otc_price p, cpc_otc_price_rate pr, cbec_acct_item_type ait, dc_tariff_id_mapping o
          WHERE op.PRICE_PLAN_ID = pp.PRICE_PLAN_ID
            AND pp.PRICE_PLAN_ID = ppv.PRICE_PLAN_ID
            AND ppv.PRICE_PLAN_VER_ID = p.PRICE_PLAN_VER_ID
            AND p.PRICE_ID = pr.PRICE_ID
            AND (ppv.EXP_DATE IS NULL OR ppv.EXP_DATE > NOW())
            AND pr.ACCT_ITEM_TYPE_ID = ait.ACCT_ITEM_TYPE_ID
            AND op.OFFER_ID = o.target_id
            AND o.map_type = 'IPP_OFFER_ID'
         UNION ALL
         SELECT DISTINCT op.OFFER_ID, o.key_str2 offer_name, op.OFFER_ID offer_code, ait.ACCT_ITEM_TYPE_CODE, ait.ACCT_ITEM_TYPE_NAME,
                'OTC', 'WMX', o.key_str1 lagcy_offer_code
           FROM cpc_otc_offer_price op, cpc_otc_price_plan pp, cpc_otc_price_plan_ver ppv,
                cpc_otc_price p, cpc_otc_price_rate pr, cbec_acct_item_type ait, dc_tariff_id_mapping o
          WHERE op.PRICE_PLAN_ID = pp.PRICE_PLAN_ID
            AND pp.PRICE_PLAN_ID = ppv.PRICE_PLAN_ID
            AND ppv.PRICE_PLAN_VER_ID = p.PRICE_PLAN_VER_ID
            AND p.PRICE_ID = pr.PRICE_ID
            AND (ppv.EXP_DATE IS NULL OR ppv.EXP_DATE > NOW())
            AND pr.ACCT_ITEM_TYPE_ID = ait.ACCT_ITEM_TYPE_ID
            AND op.OFFER_ID = o.target_id
            AND o.map_type = 'IPP_OFFER_ID_WMX'
         UNION ALL
         SELECT DISTINCT op.OFFER_ID, o.target_val offer_name, op.OFFER_ID offer_code, ait.ACCT_ITEM_TYPE_CODE, ait.ACCT_ITEM_TYPE_NAME,
                'OTC', 'SERVICE', o.key_str1 lagcy_offer_code
           FROM cpc_otc_offer_price op, cpc_otc_price_plan pp, cpc_otc_price_plan_ver ppv,
                cpc_otc_price p, cpc_otc_price_rate pr, cbec_acct_item_type ait, dc_tariff_id_mapping o
          WHERE op.PRICE_PLAN_ID = pp.PRICE_PLAN_ID
            AND pp.PRICE_PLAN_ID = ppv.PRICE_PLAN_ID
            AND ppv.PRICE_PLAN_VER_ID = p.PRICE_PLAN_VER_ID
            AND p.PRICE_ID = pr.PRICE_ID
            AND (ppv.EXP_DATE IS NULL OR ppv.EXP_DATE > NOW())
            AND pr.ACCT_ITEM_TYPE_ID = ait.ACCT_ITEM_TYPE_ID
            AND op.OFFER_ID = o.target_id
            AND o.map_type = 'IPP_OFFER_ID_OTHERS') t"

    3. offer and RC acct_item:
        "SELECT op.OFFER_ID, tim.key_str2 offer_name, op.OFFER_ID offer_code, ait.ACCT_ITEM_TYPE_CODE, ait.ACCT_ITEM_TYPE_NAME, 'RC' Fee_Type,
                CASE WHEN tim.map_type = 'DPP_OFFER_ID' AND tim.key_str3 = 'Postpaid' THEN 'GSM postpaid'
                     WHEN tim.map_type = 'DPP_OFFER_ID' AND tim.key_str3 = 'WMX' THEN 'WMX'
                     WHEN tim.map_type = 'DPP_OFFER_ID' AND tim.key_str3 = 'WMX' THEN 'WMX'
                     WHEN tim.map_type = 'IPP_OFFER_ID_POST' THEN 'GSM postpaid'
                     WHEN tim.map_type = 'IPP_OFFER_ID_WMX' THEN 'WMX'
                     WHEN tim.map_type = 'IPP_OFFER_ID_OTHERS' THEN 'SERVICE' END BUSI_TYPE,
                     REPLACE(REPLACE(REPLACE(tim.key_str1, ' 1 Year', ''), ' 2 Year', ''), ' 3 Year', '') lagcy_offer_code
           FROM offer_price op, tariff_plan_rela tp, price_plan_ver ppv,
                price_plan_member ppm, re_price_set rps, rate_plan rp,
                mapping m, price_ver pv, price p, ref_value rv, con_res_detail crd,
                cbec_acct_item_type ait, dc_tariff_id_mapping tim
          WHERE op.TARIFF_PLAN_ID = tp.TARIFF_PLAN_ID
            AND tp.PRICE_PLAN_ID = ppv.PRICE_PLAN_ID
            AND ppv.PRICE_PLAN_VER_ID = ppm.PRICE_PLAN_VER_ID
            AND ppm.PRICE_SET_ID = rps.PRICE_SET_ID
            AND rps.RE_PRICE_SET_ID = rp.RE_PRICE_SET_ID
            AND rp.RATE_PLAN_ID = m.RATE_PLAN_ID
            AND m.MAPPING_ID = pv.MAPPING_ID
            AND pv.PRICE_VER_ID = p.PRICE_VER_ID
            AND p.CON_RES_ID = rv.REF_VALUE_ID
            AND rv.REF_VALUE_TYPE = 9
            AND rv.VALUE_STRING = crd.CON_RES_ID
            AND crd.ACCT_ITEM_TYPE_ID = ait.ACCT_ITEM_TYPE_ID
            AND op.OFFER_ID = tim.target_id
            AND op.OFFER_ID > 240000
            AND tim.map_type IN ('IPP_OFFER_ID_OTHERS', 'IPP_OFFER_ID_POST', 'DPP_OFFER_ID')"