#按配置顺序逐表导出导入,大于配置在前面有利于提高效率
TableList:
    - ZONE_VALUE
    - REF_VALUE_TO_OFFER_VER
    - REF_VALUE
    - EVENT_BENEFIT
    - PRICE
    - ACCT_ITEM_TYPE
    - ACCT_ITEM_GROUP
    - ACCT_ITEM_TYPE_BIND
    - ACCT_ITEM_TYPE_BIND_TYPE
    - ACCT_PRICE_PLAN
    - ACCT_RES
    - ACCT_RES_FREE
    - ACCT_RES_RESTRICT
    - ACM
    - ACM_ADVICE
    - ACM_BENEFIT
    - ACM_CALC
    - ACM_CYCLE_TYPE
    - ACM_PCRF
    - ACM_REF
    - ACM_RULE
    - ACM_SUBS_EVENT
    - ACM_THRESHOLD
    - ACM_TIME_SPAN
    - ACM_TRIGGER
    - ACM_TYPE
    - ACM_UP
    - ADJUST_METHOD
    - ADVICE_CHANNEL
    - ADVICE_MACRO
    - ADVICE_MACRO_SCRIPT
    - ADVICE_TYPE
    - ADVICE_TYPE_LANG
    - ADVICE_TYPE_PARAM
    - APPLY_LEVEL
    #- ATTR
    #- ATTR_VALUE
    - BAL_ADVICE
    - BAL_BENEFIT
    - BAL_SUBS_EVENT
    - BAL_THRESHOLD
    - BAL_TRIGGER
    - BAL_TYPE
    #- BASE_ATTR
    #- BILLING_CYCLE
    #- BILLING_CYCLE_TYPE
    - BILLING_PLAN_TYPE
    - BILL_SHOCK_RULE_RE
    - BILL_SHOCK_SET_ATTRS
    - BWF_ACTION
    - BWF_COND
    - BWF_COND_GROUP
    - BWF_NODE
    - BWF_STEP
    - BWF_SYS_ACTION
    - BWF_WORKFLOW
    - sort_function
    - CALC_TYPE
    - CARRIER_CODE
    - CARRIER_COUNTRY_RELA
    - CHANNEL_UNIT_TYPE
    - COLUMN_EDIT_MODE
    - COUNTRY_CODE
    - CUST_CATG
    - DEF_RE_ATTR
    - DEPOSIT_PRICE
    - DEPOSIT_TYPE
    - DIY_BENEFIT_MRC
    - DP
    - DP_RULE
    - DP_TYPE
    - DS_TAG
    - DYN_RE_ATTR
    - DYN_TABLE
    - EVENT_FORMAT
    - EXCHANGE_RATE
    - GPR
    - GPR_ACTION
    - GPR_AE
    - GPR_BE
    - GPR_ELEMENT
    - GPR_ELEMENT_TYPE
    - GPR_FUNCTION
    - GPR_INST
    - GPR_NODE
    - GPR_SERVICE
    - GST_TYPE
    - GST_TYPE_TAX_RATE
    - HOME_ZONE
    - MAPPING
    - MAPPING_ACTION
    - MAPPING_UNIT
    - MATCH_MODE
    - MEASURE_UNIT_LIST
    - MORE_UP
    #- NOTIFY_PARAMS
    #- NOTIFY_PARAM_DEF
    - OFFER
    - OFFER_ATTR
    - OFFER_REAL_BENEFIT
    - OFFER_REAL_DISCOUNT
    - OFFER_REAL_MORE_RES
    - PARAM_CODE
    - PARAM_VALUE_LIST
    - PARAM_VALUE_TYPE
    - PCRF_TRIGGER_COUNTER_RELA
    - PERIOD
    - PRICE_CATALOG_ELEMENT
    - PRICE_PARAM
    - PRICE_PARAM_VALUE_TYPE
    - PRICE_PLAN_PARAM
    - PRICE_PLAN_PARAM_VER
    - PRICE_PLAN_PARAM_VER_GROUP
    - PRICE_PLAN_TYPE
    - PRICE_TEMPLATE_MAPPING_RE
    - PRICE_VER
    - PYTHON_SELECT_TABLE
    - QUOTED_PRICE_TYPE
    - RANK_UP
    - RATABLE_RESOURCE
    - RATE_PLAN
    - RATE_PLAN_CATALOG_ELEMENT
    - RATE_PLAN_MAPPING
    - RATE_PLAN_PARAM
    - RATE_PLAN_RELA
    - RATE_PLAN_TYPE
    - RATE_PLAN_ZONE
    - RATING_FLOW
    - RE
    - RECURRING_RE_TYPE
    - REF_ACCT_ITEM_TYPE
    - RESERVE_LIMIT
    - RESERVE_LIMIT_PROD_SPEC
    - RESERVE_POLICY
    - RESERVE_POLICY_PROD_SPEC
    - RE_ATTR
    - RE_ATTR_TAG
    - RE_PP_RECURRING
    - RE_PRICE_PLAN
    - RE_RECURRING
    - RE_TYPE
    - RE_USAGE
    - RP
    - RP_EB_MAPPING_PRICE
    - RP_MAPPING_BRANCH
    - RP_MAPPING_BRANCH_COND_GRP
    - RP_MAPPING_COND_GRP
    - RP_MAPPING_COND_GRP_DT
    - RP_MAPPING_PRICE
    - RP_PRICE_TYPE
    - RP_PRICE_UNIT
    - RP_REF_COND
    - RULE_REFRESH
    - RULE_REFRESH_DETAIL
    - SCRIPT_FUNCTION_CATALOG_ELEMEN
    - SCRIPT_TEMPLET
    - SCRIPT_TEMPLET_CATALOG_ELEMENT
    - SCRIPT_TEMPLET_GROUP
    - SCRIPT_TEMPLET_PARAM
    - SIMPLE_PARAM_DEFINE
    - SIMPLE_PARAM_DEFINE_HIS
    - SORT_RECURRING
    - SP_RES
    - SUBS_EVENT
    - SUBS_PRICE_PLAN
    - SUBS_RELA_EXCLUSIVE
    - SUBS_RE_EVENT
    - SUB_BAL_TYPE
    - SUB_BAL_TYPE_LIMIT
    - TARIFF_TEMPLATE_CATALOG_TYPE
    #- TEXT_ATTR
    - TIME_SPAN
    - TIME_SPAN_DETAIL
    - TIME_SPAN_UP
    - TRIGGER_RULE
    - TRIGGER_TYPE
    - UNIT_TYPE
    - UP_RULE
    - UP
    - WF_INSTANCE
    - WF_MAP
    - ZONE
    - ZONE_MAP
    - ZONE_MAP_TYPE

    - DEPEND_PROD_SPEC
    - DEPEND_PROD_PACKAGE
    - INDEP_PROD_SPEC
    - OFFER_APPLY_AREA
    - OFFER_APPLY_CATG
    - OFFER_APPLY_ORG
    - OFFER_CATG
    #- OFFER_CATG_APPLY_CHANNEL
    - OFFER_CATG_MEM
    - OFFER_GROUP
    - OFFER_GROUP_MEM
    - OFFER_PUBLISH_LOG
    - OFFER_RELA
    - OFFER_VER
    - OP
    - PRICE_PLAN
    - SUBS_PLAN
    - SUBS_PLAN_OFFER_ATTR
    - SUBS_PLAN_OFFER_ATTR_VALUE
    - SUBS_PLAN_OFFER_SELECT
    - SUBS_PLAN_PRICE
    - OFFER_FAVORITE
    - OFFER_FAV_CATG
    - OFFER_GUIDE
    - OFFER_GUIDE_ELE
    - OFFER_REBATE
    - OFFER_TMPL
    - OFFER_TMPL_CATG
    - CC_RULE_GROUP
    - CC_RULE
    - CC_ELEMENT
    - CC_AE
    - CC_BE
    - CC_NOTIF
    - CC_SEP_TYPE
    - CC_ACTION
    - TARIFF_TEMPLATE_CATALOG
    - CHANNEL_TYPE
    - RE_ACTION_PRICE_PLAN
    - RE_ACTION
    - LIFECYCLE_APPLY
    - GEO_NET_ZONE
    - GEO_HOME_ZONE
    - TAX_TYPE
    - TAX_TYPE_RATE
    - ACCT_ITEM_TYPE_TAX
    - GL_ACCT_ITEM_TYPE
    - GL_MERGE_TABLE
    #- GL_RE
    - GL_TYPE
    - GL_UNIV_MERGE_RELA
    - GL
    - DISCT_OBJ
    - DISCT_OBJ_AITID
    - TAB_DP
    - TAB_DP_DT
    - BS_TEMPLATE
    - BS_TEMPLATE_ITEM
    - BS_TEMPLATE_GROUP
    - BS_TEMPLATE_GROUP_MEM
    - GOODS_PROD_SPEC
    - MID_TABLE_SEQ
    - OFFER_APPLY_CHANNEL
    - DP_REF_COND
    - TAB_DP_COND_GRP_DT
    - TAB_DP_COND_GRP
    - goods_prod_package
    - price_plan_package

TableSql:
    GL_TYPE:
        select gl_type_id, rep_merge_type, gl_type_name, mask, sp_id  from gl_type where gl_type_id = 12
    GL:
        select * from gl where gl_type_id = 1
    GL_ACCT_ITEM_TYPE:
        select * from gl_acct_item_type where gl_id < 3000
    ADVICE_TYPE:
        select * from ADVICE_TYPE where advice_type < 100000
    ADVICE_TYPE_PARAM:
        select * from ADVICE_TYPE_PARAM where advice_type < 100000
    ADVICE_TYPE_LANG:
        select * from ADVICE_TYPE_LANG where advice_type < 100000
    SCRIPT_TEMPLET:
        select * from SCRIPT_TEMPLET where script_templet_id <= 2101

AfterImportSql:
    - "update gl set comments = 'gl' where 1=1"
#不要超过8个
ThreadNumber: 8

SequenceList:
    - offer_id_seq
    - offer_seq
