A001:
    create:
        DC_TEST003:
                create table DC_Test003 (
                    check_item varchar(200),
                    check_sql varchar(4000),
                    check_result varchar(20)
                    )

A002:
    create:
        DC_CPC:
            CREATE DATABASE LINK "DC_CPC"
            CONNECT TO "CPC" IDENTIFIED BY "1jian8Shu)"
            USING '(DESCRIPTION =
            (ADDRESS_LIST =
            (ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.25.84)(PORT = 11521))
            )
            (CONNECT_DATA =
            (SERVICE_NAME = dcpdb)
            )
            )'

    create_list:
        DC_CPC:
            - LINK
            - V20191126
            - database link

A003:
    create:
        DC_TEST004:
                create table DC_Test004 (
                    check_item varchar(200),
                    check_sql varchar(4000),
                    check_result varchar(20)
                    )

    create_list:
        DC_TEST004:
            - A003
            - V20190401
            - table
            - VALUE_LIST:
                CHECK_ITEM:
                    TYPE: list
                    SOURCE: 1,2,3,4
                CHECK_SQL:
                    TYPE: list
                    SOURCE: a,b,c
            - COMMENTS:
                - CHECK_ITEM: 12312312