Tablelist:
  OP: OP_ID,RULE_SCRIPT
  RP: RP_ID,RULE_SCRIPT
  TRIGGER_RUlE: TRIGGER_ID,RULE_SCRIPT
  DEPOSIT_PRICE: PRICE_ID,RULE_SCRIPT
  RE_PRICE_PLAN: RE_ID,RULE_SCRIPT
  ACM_RULE: ACM_RULE_ID,RULE_SCRIPT
  DP_RULE: DP_ID,RULE_SCRIPT
  UP_RULE: UP_RULE_ID,RULE_SCRIPT
  bwf_sys_action: SYS_ACTION_ID,EXT_SCRIPT
  EVENT_BENEFIT: PRICE_ID,RULE_SCRIPT
  NBR_CLASS_JUDGE: NBR_CLASS_JUDGE_ID,RULE_SCRIPT
  RESERVE_POLICY: RE_ID,RULE_SCRIPT