DefaultUser:
    cpc

Offer:
  1.Brand:
      "select brand_id,brand_name from brand"

  3.BasicOffer:
      "select prod_id,prod_name from product where manage_grade=11"

  4.MainOffer:
      "select offer_id,offer_name,offer_desc from offer where offer_type=11
       order by Offer_DESC"

  10.OTC:
      "select a.offer_id,a.offer_name,e.service_offer_name,f.acct_item_type_name,j.con_name condition,
        c.value*0.00000001 price,g.acct_res_name benefit_acct_res_name,d.value benefit_value,
        h.unit_name benefit_unit_type,d.rel_exp_offset EXP_DATE,decode(d.rel_exp_unit,'D','Day','C','Billing Cycle') EXP_TYPE
         from offer a,CPC_OTC_PRICE b,CPC_OTC_PRICE_RATE c,CPC_OTC_PRICE_BENEFIT d,
        service_offer e,cbec_acct_item_type f,cbec_acct_res g,cbec_unit h,CPC_OTC_CON_GROUP i,CPC_OTC_CON j
        where a.offer_id=b.offer_id
        and b.price_id=c.price_id
        and c.price_id=d.price_id(+)
        and b.service_offer_id=e.service_offer_id
        and c.acct_item_type_id=f.acct_item_type_id
        and d.acct_res_id=g.acct_res_id(+)
        and g.unit_id=h.unit_id(+)
        and b.con_group_id=i.con_group_id(+)
        and i.con_group_id=j.con_group_id(+)
        --and offer_name='Lai-Lai standard'
        and c.price_id not in (select cop.price_id  from cpc_otc_price cop where is_list_price='Y')
        order by a.offer_name,e.service_offer_name,j.con_name"

  13.Offer Single Exclusive:
      "select a_offer_id,a_offer_name,z_offer_id,z_offer_name
        from
        (
        select a_offer_id a_offer_id,z_offer_id z_offer_id,t2.offer_name a_offer_name,t3.offer_name z_offer_name
        from offer_rel t1
        left join offer t2
        on t1.a_offer_id=t2.offer_id
        left join offer t3
        on t1.z_offer_id=t3.offer_id
        where rel_type=210000
        union
        select t2.offer_id,t3.offer_id,t4.offer_name,t5.offer_name
        from offer_grp t1
        inner join offer_grp_member t2
        on t1.offer_grp_id=t2.offer_grp_id
        inner join offer_grp_member t3
        on t1.offer_grp_id=t3.offer_grp_id
        left join offer t4
        on t2.offer_id=t4.offer_id
        left join offer t5
        on t3.offer_id=t5.offer_id
        where t1.grp_rel_type=1000
        and t1.status_cd=1000
        )"

  19.MainOffer&OptionalOffer:
      "SELECT a.offer_id, a.offer_name,b.offer_id,b.offer_name, o.rel_type,o.*
        FROM offer_rel o,offer a,offer b  WHERE  a.offer_id=o.a_offer_id AND b.offer_id=o.z_offer_id AND
        a.offer_type ='11'
        ORDER BY  a.offer_id"

  23.Offer and Product Relation:
      "select t1.offer_id,offer_name ,t1.prod_id,prod_name,t5.attr_value_name from cpc.offer_prod_rel t1
        left join cpc.offer_prod_rel_rstr_cfg t2
        on t1.offer_prod_rel_id = t2.offer_prod_rel_id
        left join offer t3
        on t1.offer_id =t3.offer_id
        left join product t4
        on t1.prod_id =t4.prod_id
        left join attr_value t5
        on t2.rstr_type = t5.attr_value
        and t5.attr_id = 800052231
        where t1.par_offer_prod_rel_id <>-1
        order by t1.offer_id"
