create:
    DC_MAIN_PROD_DEF:
        - |
            create table DC_MAIN_PROD_DEF
            (
                main_prod_id        number(16),
            	main_prod_name      VARCHAR2(255),
            	main_prod_code      VARCHAR2(100),
            	EFF_TYPE            VARCHAR2(64),
            	service_type        varchar2(128),
            	EFF_DATE            VARCHAR2(64),
            	EXP_DATE            VARCHAR2(64),
            	remark              VARCHAR2(64)
            )

    DC_SUBS_PLAN_DEF:
        - |
            create table DC_SUBS_PLAN_DEF
            (
                subs_plan_id        number(16),
            	subs_plan_name      VARCHAR2(255),
            	subs_plan_code      VARCHAR2(100),
            	main_prod_id        number(16),
            	EFF_TYPE            VARCHAR2(64),
            	agreement_period    number(16),
            	agreement_period_unit VARCHAR2(16),
            	EFF_DATE            VARCHAR2(64),
            	EXP_DATE            VARCHAR2(64),
            	paid_flag           VARCHAR2(1),
            	agreement_eff_type  VARCHAR2(64),
            	lifecycle_type      VARCHAR2(64),
            	remark              VARCHAR2(64)
            )
        - comment on column DC_SUBS_PLAN_DEF.main_prod_id is 'the main prod id of subs plan, the id should reference DC_MAIN_PROD_DEF.main_prod_id'

    DC_RELATE_PROD_DEF:
        - |
            create table DC_RELATE_PROD_DEF
            (
                relate_prod_id        number(16),
            	relate_prod_name      VARCHAR2(255),
            	relate_prod_code      VARCHAR2(100),
            	EFF_TYPE              VARCHAR2(64),
            	auto_renew_flag       VARCHAR2(1),
            	agreement_period      number(16),
            	agreement_period_unit VARCHAR2(16),
            	duplicate_order       VARCHAR2(64),
            	validity_period       number(16),
            	validity_period_unit  VARCHAR2(16),
            	EFF_DATE              VARCHAR2(64),
            	EXP_DATE              VARCHAR2(64),
            	agreement_eff_type    VARCHAR2(64),
            	package_mode          varchar2(16),
            	service_type          varchar2(128),
            	remark                VARCHAR2(64)
            )

    DC_GOODS_PROD_DEF:
        - |
            create table DC_GOODS_PROD_DEF
            (
                goods_prod_id        number(16),
            	goods_prod_name      VARCHAR2(255),
            	goods_prod_code      VARCHAR2(128),
            	goods_model_code     VARCHAR2(128),
            	EFF_DATE             VARCHAR2(64),
            	EXP_DATE             VARCHAR2(64),
            	agreement_period      number(16),
            	agreement_period_unit VARCHAR2(16),
            	sale_price           number(16),
            	package_mode         varchar2(16),
            	remark               VARCHAR2(64)
            )

    DC_PRICE_PLAN_DEF:
        - |
            create table DC_PRICE_PLAN_DEF
            (
                price_plan_id         number(16),
                price_plan_name       VARCHAR2(255),
            	price_plan_code       VARCHAR2(100),
            	price_plan_type_name  VARCHAR2(64),
            	EFF_TYPE              VARCHAR2(64),
            	auto_renew_flag       VARCHAR2(1),
            	agreement_period      number(16),
            	agreement_period_unit VARCHAR2(16),
            	duplicate_order       VARCHAR2(64),
            	validity_period       number(16),
            	validity_period_unit  VARCHAR2(16),
            	EFF_DATE              VARCHAR2(64),
            	EXP_DATE              VARCHAR2(64),
            	agreement_eff_type    VARCHAR2(64),
            	package_mode          varchar2(16),
            	apply_level           VARCHAR2(64),
            	priority              number(8),
            	policy_flag           VARCHAR2(4),
            	remark                VARCHAR2(64)
            )

    DC_OFFER_GROUP_DEF:
        - |
            create table DC_OFFER_GROUP_DEF
            (
                offer_group_name       VARCHAR2(255),
            	offer_group_code       VARCHAR2(30),
            	group_type             VARCHAR2(64),
            	group_mode             VARCHAR2(64),
            	lower_limit            number(16),
            	upper_limit            number(16),
            	EFF_DATE               VARCHAR2(64),
            	EXP_DATE               VARCHAR2(64),
            	remark                 VARCHAR2(64)
            )

    DC_OFFER_CATALOG_DEF:
        - |
            create table DC_OFFER_CATALOG_DEF
            (
                offer_catg_name        VARCHAR2(60),
                offer_group_code       VARCHAR2(30),
            	offer_catg_type        VARCHAR2(64),
            	offer_catg_class       VARCHAR2(64),
            	parent_offer_catg_name varchar2(60),
            	EFF_DATE               VARCHAR2(64),
            	EXP_DATE               VARCHAR2(64),
            	remark                 VARCHAR2(64)
            )

    DC_PERIOD_DEF:
        - |
            create table DC_PERIOD_DEF
            (
              period_id      NUMBER(9) not null,
              abs_eff_date   DATE,
              abs_exp_date   DATE,
              rel_eff_offset NUMBER(9),
              rel_eff_unit   CHAR(1),
              rel_exp_offset NUMBER(9),
              rel_exp_unit   CHAR(1),
              rel_eff_time   DATE,
              rel_exp_time   DATE,
              remark   VARCHAR2(64)
            )

create_list:
    DC_MAIN_PROD_DEF:
        - OBJECT
        - V0001
        - table
        - VALUE_LIST:
            EFF_TYPE:
                TYPE: list
                SOURCE: Special Day,Instant,Next Day,Next Week,Next Month,Next Billing Cycle,The Cycle After Next Cycle,Special Day|Instant,Special Day|Instant|Next Billing Cycle
            SERVICE_TYPE:
                TYPE: sql
                SOURCE: select serv_type||'_'||serv_type_name||'('||network_type||')' from all_serv_type

    DC_SUBS_PLAN_DEF:
        - OBJECT
        - V0001
        - table
        - VALUE_LIST:
            EFF_TYPE:
                TYPE: list
                SOURCE: Special Day,Instant,Next Day,Next Week,Next Month,Next Billing Cycle,The Cycle After Next Cycle,Special Day|Instant,Special Day|Instant|Next Billing Cycle
            PAID_FLAG:
                TYPE: list
                SOURCE: Y,N
            AGREEMENT_EFF_TYPE:
                TYPE: list
                SOURCE: NEXT DAY,NEXT MONTH,NEXT BILLING CYCLE,IN THE MORNING
            LIFECYCLE_TYPE:
                TYPE: sql
                SOURCE: select lifecycle_type_name from lifecycle_type
            AGREEMENT_PERIOD_UNIT:
                TYPE: sql
                SOURCE: select time_unit_name from time_unit

    DC_RELATE_PROD_DEF:
        - OBJECT
        - V0001
        - table
        - VALUE_LIST:
            EFF_TYPE:
                TYPE: list
                SOURCE: Special Day,Instant,Next Day,Next Week,Next Month,Next Billing Cycle,The Cycle After Next Cycle,Special Day|Instant,Special Day|Instant|Next Billing Cycle
            AUTO_RENEW_FLAG:
                TYPE: list
                SOURCE: Y,N
            DUPLICATE_ORDER:
                TYPE: list
                SOURCE: Don't Allow to Duplicate Order,Extend Effective Of Old Instance From Sysdate,Add A Instance,Add A Instance And Cancel Old One,Extend Effective Of Old Instance From ExpDate,Add A Instance EffDate Equal Old ExpDate
            AGREEMENT_EFF_TYPE:
                TYPE: list
                SOURCE: NEXT DAY,NEXT MONTH,NEXT BILLING CYCLE,IN THE MORNING
            PACKAGE_MODE:
                TYPE: list
                SOURCE: Select All,Single Choice,Muti-Choice
            SERVICE_TYPE:
                TYPE: sql
                SOURCE: select serv_type||'_'||serv_type_name||'('||network_type||')' from all_serv_type
            AGREEMENT_PERIOD_UNIT:
                TYPE: sql
                SOURCE: select time_unit_name from time_unit
            VALIDITY_PERIOD_UNIT:
                TYPE: sql
                SOURCE: select time_unit_name from time_unit

    DC_GOODS_PROD_DEF:
        - OBJECT
        - V0001
        - table
        - VALUE_LIST:
            PACKAGE_MODE:
                TYPE: list
                SOURCE: Select All,Single Choice,Muti-Choice
            AGREEMENT_PERIOD_UNIT:
                TYPE: sql
                SOURCE: select time_unit_name from time_unit

    DC_PRICE_PLAN_DEF:
        - OBJECT
        - V0001
        - table
        - VALUE_LIST:
            EFF_TYPE:
                TYPE: list
                SOURCE: Special Day,Instant,Next Day,Next Week,Next Month,Next Billing Cycle,The Cycle After Next Cycle,Special Day|Instant,Special Day|Instant|Next Billing Cycle
            AUTO_RENEW_FLAG:
                TYPE: list
                SOURCE: Y,N
            DUPLICATE_ORDER:
                TYPE: list
                SOURCE: Don't Allow to Duplicate Order,Extend Effective Of Old Instance From Sysdate,Add A Instance,Add A Instance And Cancel Old One,Extend Effective Of Old Instance From ExpDate,Add A Instance EffDate Equal Old ExpDate
            AGREEMENT_EFF_TYPE:
                TYPE: list
                SOURCE: NEXT DAY,NEXT MONTH,NEXT BILLING CYCLE,IN THE MORNING
            PACKAGE_MODE:
                TYPE: list
                SOURCE: Select All,Single Choice,Muti-Choice
            PRICE_PLAN_TYPE_NAME:
                TYPE: sql
                SOURCE: select price_plan_type_name from price_plan_type
            APPLY_LEVEL:
                TYPE: sql
                SOURCE: select apply_level_name from apply_level
            POLICY_FLAG:
                TYPE: list
                SOURCE: Y,N
            AGREEMENT_PERIOD_UNIT:
                TYPE: sql
                SOURCE: select time_unit_name from time_unit
            VALIDITY_PERIOD_UNIT:
                TYPE: sql
                SOURCE: select time_unit_name from time_unit

    DC_OFFER_GROUP_DEF:
        - OBJECT
        - V0001
        - table
        - VALUE_LIST:
            GROUP_TYPE:
                TYPE: list
                SOURCE: Default Price Plan Group,Goods Product Group,Price Plan Group,Related Product Group
            GROUP_MODE:
                TYPE: list
                SOURCE: Select All,Single Choice,Muti-Choice

    DC_OFFER_CATALOG_DEF:
        - OBJECT
        - V0001
        - table
        - VALUE_LIST:
            OFFER_CATG_TYPE:
                TYPE: list
                SOURCE: Main Product,Related Product,Price Plan,Goods Product,Bundle
            OFFER_CATG_CLASS:
                TYPE: list
                SOURCE: Sales Catalog,Management Catalog

    DC_PERIOD_DEF:
        - OBJECT
        - V0001
        - table
        - VALUE_LIST:
            REL_EFF_UNIT:
                TYPE: sql
                SOURCE: select time_unit_name from time_unit
            REL_EXP_UNIT:
                TYPE: sql
                SOURCE: select time_unit_name from time_unit