create:
    DC_ADVICE_TYPE_BASIC:
        - |
          create table DC_ADVICE_TYPE_BASIC
                       (
                         ADVICE_CHANNEL_NAME   VARCHAR2(100),
                         ADVICE_TYPE_NAME      VARCHAR2(60),
                         COMMENTS              VARCHAR2(120),
                         SUBJECT_DEFINE        VARCHAR2(4000),
                         DISABLED              CHAR(1),
                         EFF_TIME              VARCHAR2(64),
                         EXP_TIME              VARCHAR2(64),
                         STD_CODE              VARCHAR2(60),
                         ADVICE_CATG_NAME      VARCHAR2(100),
                         RETAIN_HIS            CHAR(1),
                         DELAY_TIME            NUMBER(6),
                         SRC_NBR               VARCHAR2(1000),
                         SENDER_PARAM          VARCHAR2(1000),
                         TIMES                 NUMBER(4),
                         TIME_INTERVAL         NUMBER(6),
                         ADVICE_MESSAGE        clob
                       )

        - comment on table DC_ADVICE_TYPE_BASIC is 'advice baisc information and message templet'
        - comment on column DC_ADVICE_TYPE_BASIC.SUBJECT_DEFINE is 'Message Title for Mail Advice'
        - comment on column DC_ADVICE_TYPE_BASIC.RETAIN_HIS is 'IF Retain In Advice_his'
        - comment on column DC_ADVICE_TYPE_BASIC.DELAY_TIME is 'Delay Time Once In Batch Job Send Mode'
        - comment on column DC_ADVICE_TYPE_BASIC.ADVICE_MESSAGE is 'Complete Advice Templet'
    DC_ADVICE_TYPE_PARAM:
        - |
          create table DC_ADVICE_TYPE_PARAM
          (
          advice_type_code      VARCHAR2(60),
          advice_param_name     VARCHAR2(255),
          advice_param_code     VARCHAR2(255),
          comments              VARCHAR2(255),
          rule_flag             CHAR(1),
          is_macro              CHAR(1),
          is_string             CHAR(1)
          )
        - comment on column DC_ADVICE_TYPE_PARAM.is_macro is 'if this is a macro param'
        - comment on column DC_ADVICE_TYPE_PARAM.is_string is 'convert list to string'
    DC_ADVICE_TYPE_TEMPLET:
        - |
          create table DC_ADVICE_TYPE_TEMPLET
          (
          advice_type_code       VARCHAR2(60),
          if_condidtion1         VARCHAR2(60),
          if_action1             VARCHAR2(60),
          if_condidtion2         VARCHAR2(60),
          if_action2             VARCHAR2(60),
          if_condidtion3         VARCHAR2(60),
          if_action3             VARCHAR2(60),
          advice_string1         VARCHAR2(2000),
          advice_string2         VARCHAR2(2000),
          advice_string3         VARCHAR2(2000),
          advice_string4         VARCHAR2(2000),
          advice_string5         VARCHAR2(2000)
          )

    DC_ADVICE_TYPE_MULTI_LANG:
        - |
          create table DC_ADVICE_TYPE_MULTI_LANG
          (
            advice_type_code      VARCHAR2(60),
            def_lang_name         varchar2(60),
            subject_define        VARCHAR2(4000),
            advice_message        CLOB,
            sender_param          VARCHAR2(1000)
          )

create_list:
    DC_ADVICE_TYPE_BASIC:
        - ADVICE
        - V0001
        - table
        - VALUE_LIST:
            ADVICE_CHANNEL_NAME:
                TYPE: sql
                SOURCE: select ADVICE_CHANNEL_NAME from ADVICE_CHANNEL
            ADVICE_CATG_NAME:
                TYPE: sql
                SOURCE: SELECT lookup_name FROM domain where column_name='ADVICE_CATG'

    DC_ADVICE_TYPE_PARAM:
        - ADVICE
        - V0001
        - table

    DC_ADVICE_TYPE_TEMPLET:
        - ADVICE
        - V0001
        - table

    DC_ADVICE_TYPE_MULTI_LANG:
        - ADVICE
        - V0001
        - table
        - VALUE_LIST:
            DEF_LANG_NAME:
                TYPE: sql
                SOURCE: SELECT def_lang_name FROM def_lang