DefaultUser:
    cpc


delete:
    DC_PRICE_CHECK_RESULT_SELFTAB: delete from DC_PRICE_CHECK_RESULT_SELFTAB where check_topic='after_check'

#insert into result table
insert_result_tab:
    insert into DC_PRICE_CHECK_RESULT_SELFTAB (check_file_name,check_group,check_item,check_sql,check_result,check_topic)
    values (%s,%s,%s,%s,%s,%s)


export_result:
    DC_PRICE_CHECK_RESULT_SELFTAB:
        select check_file_name as file_name,
        check_group as topic_name,
        check_item as title_name,
        check_sql as sql_content,
        case when check_result = 0 then 'success' else 'fail' end as result,
        check_result as error_count,
        to_char(create_date,'yyyy/mm/dd hh24:mi:ss') as check_time
        from DC_PRICE_CHECK_RESULT_SELFTAB
        where check_topic = %(check_type)s
        and check_file_name = %(file_name)s
        and check_group = %(topic)s
        and check_item = %(title)s
        and check_result <> %(only_failed)s

check_title_all_list:
    Account Item not in GL:
        des: 只要有合帐的账目类型，必须有GL所关联
        topic: ErrorData
        area: comm

    Balance Type not related to consume type:
        des: 帐本没有与消费类型关联，说明没有使用到,SQL中帐本的范围可以修改
        topic: BadData
        area: A009

    Charging Workflow use the condition !=:
        des: V9分拣里使用 ！= 不等于时，如果属性值为空，也会满足条件，需要单独拿出来确认
        topic: WarningData
        area: comm

    Event exists in price but not in sort rule:
        des: 资费里面有事件，但是分拣中没有输出对应的事件
        topic: BadData
        area: comm

    Event exists in sort rule but not in price:
        des: 分拣输出事件，但是资费里面没有配置这个事件
        topic: ErrorData
        area: comm

    Individual price plan do not relate to tariff plan:
        des: 个性化资费计划没有关联tariff plan（马少华，资费计划不使用，暂时没有删除，准备挪到Project Level)
        topic: BadData
        area: comm

    Offer dont relate to tariff plan:
        des: 检查basic offer,main offer, additional offer没有关联tariff plan
        topic: BadData
        area: comm

    Recurring benefit accout not used in price:
        des: 租费赠送的帐本，未在使用费里使用(少华说太简单了，要提升，需要加状态过滤）
        topic: ErrorData
        area: comm

    Precision not correct:
        des: 精度问题
        topic: ErrorData
        area: comm

    SortRule_OutputRe_No_Reserve:
        des: 分拣分拣出了事件，但是在预留规则中没有配置预留
        topic: BadData
        area: comm

    Tariff plan not relate offer:
        des: tariff plan没有与 OFFER 关联，注意可以更新 tariff plan id 的范围
        topic: BadData
        area: A009

    The re_attr of reservation rule is different with the re_attr configured in price plan:
        des: 事件配置的预留规则与资费里配置的扣费单位不一致，比如预留配置的是秒，但是扣费是按次扣费
        topic: BadData
        area: comm

    UM_Event exists in sort rule but not in price:
        des: 马来检查分拣出来的事件，但是没有批价（增强了父子事件的关系）, 需要考虑上父子事件，需要优化
        topic: ErrorData
        area: A008

    UM_Event exists in sort rule not re Code:
        des: 马来检查分拣出来的事件，但是事件code，主要是账单使用
        topic: ErrorData
        area: A008

    Workflow use Assign error:
        des: 检查分拣里使用Assign函数时，是否存在把一个属性值直接Assign给另外一个属性，或者使用Assign赋予值时，忘记填参数了
        topic: ErrorData
        area: comm

    Zone_same_zone_id_multiple_value:
        des: 一个zone map下，同一个zone里存在多条相同的value值
        topic: BadData
        area: comm

    Zone Same zone value exists in different zone:
        des: 检查一个zone map下一个zone value同时存在不同的zone里
        topic: ErrorData
        area: comm