BadData:
  CATALOG_ITEM_NAME_DUPLICATED:
    SELECT CATALOG_NAME,ROOT_CATALOG_NAME
    FROM DC_CONFIG_CATALOG_ITEM
    GROUP BY CATALOG_NAME,ROOT_CATALOG_NAME
    HAVING COUNT(*) >1
  CATALOG_ITEM_NAME_EXISTS:
    SELECT T1.CATALOG_NAME,T1.ROOT_CATALOG_NAME
    FROM DC_CONFIG_CATALOG_ITEM T1
    INNER JOIN CPC.CATALOG T3
    ON INSTR(T1.ROOT_CATALOG_NAME, T3.CATALOG_NAME) = 1
    LEFT JOIN CPC.CATALOG_ITEM T2
    ON T1.CATALOG_ITEM_ID  <> T2.CATALOG_ITEM_ID
    AND T1.CATALOG_NAME = T2.CATALOG_ITEM_NAME
    AND T3.CATALOG_ID = T2.CATALOG_ID
    WHERE T2.CATALOG_ITEM_ID IS NOT NULL
  PARENT_CATALOG_ITEM_ID_NOT_EXISTS:
    SELECT T1.CATALOG_CODE,T1.CATALOG_NAME,T1.PARENT_CATALOG_ITEM_ID
    FROM DC_CONFIG_CATALOG_ITEM T1
    LEFT JOIN DC_CONFIG_CATALOG_ITEM T2
    ON T1.PARENT_CATALOG_ITEM_ID = T2.CATALOG_ITEM_ID
    LEFT JOIN CPC.CATALOG_ITEM T3
    ON T1.PARENT_CATALOG_ITEM_ID = T3.CATALOG_ITEM_ID
    WHERE T2.CATALOG_ITEM_ID IS NULL
    AND T3.CATALOG_ITEM_ID IS NULL
    AND T1.PARENT_CATALOG_ITEM_ID <> -1
    AND T1.PARENT_CATALOG_ITEM_ID IS NOT NULL
  ROOT_CATALOG_NAME_DIFFERENT_FROM_PARENTS_ROOT_CATALOG:
    SELECT T1.CATALOG_CODE, T1.CATALOG_NAME, T1.PARENT_CATALOG_ITEM_ID,T1.CATALOG_ITEM_ID
    FROM DC_CONFIG_CATALOG_ITEM T1
    LEFT JOIN (SELECT CATALOG_ITEM_ID, ROOT_CATALOG_NAME
    FROM DC_CONFIG_CATALOG_ITEM T2
    UNION ALL
    SELECT CAST(CATALOG_ITEM_ID AS CHAR), T4.CATALOG_NAME
    FROM CPC.CATALOG_ITEM T3
    INNER JOIN CPC.CATALOG T4
    ON T3.CATALOG_ID = T4.CATALOG_ID
    LEFT JOIN CPC.ATTR_VALUE T5
    ON T5.ATTR_ID = 800052286
    AND T5.STATUS_CD = '1000'
    AND T4.CATALOG_TYPE = T5.ATTR_VALUE) TT2
    ON T1.PARENT_CATALOG_ITEM_ID = TT2.CATALOG_ITEM_ID
    AND T1.ROOT_CATALOG_NAME <> TT2.ROOT_CATALOG_NAME
    WHERE T1.PARENT_CATALOG_ITEM_ID <> -1
    AND T1.PARENT_CATALOG_ITEM_ID IS NOT NULL
    AND TT2.CATALOG_ITEM_ID IS NOT NULL
  OFFER_REL_ROLE_CODE_EXISTS:
    SELECT OFFER_REL_ROLE_CODE
    FROM DC_CONFIG_OFFER_REL_ROLE T1
    LEFT JOIN CPC.OFFER_REL_ROLE T2
    ON T1.OFFER_REL_ROLE_ID <> T2.ROLE_ID
    AND T1.OFFER_REL_ROLE_CODE = T2.ROLE_CD
    WHERE T2.ROLE_ID IS NOT NULL



ErrorData:
  BRAND_NAME_IS_NULL:
    SELECT BRAND_NAME,BRAND_ID
    FROM DC_CONFIG_BRAND
    WHERE BRAND_NAME IS NULL
  BRAND_NAME_DUPLICATED:
    SELECT BRAND_NAME
    FROM DC_CONFIG_BRAND
    GROUP BY BRAND_NAME
    HAVING COUNT(*)>1
  BRAND_ID_NUMBER_ONLY:
    SELECT BRAND_NAME,BRAND_ID
    FROM DC_CONFIG_BRAND
    WHERE TRANSLATE(BRAND_ID,'A0123456789','A') IS NOT NULL
    AND BRAND_ID IS NOT NULL
  BRAND_ID_DUPLICATED:
    SELECT BRAND_ID
    FROM DC_CONFIG_BRAND
    GROUP BY BRAND_ID
    HAVING COUNT(*)>1
  BRAND_NAME_EXIST:
    SELECT T1.BRAND_NAME,T1.BRAND_ID
    FROM DC_CONFIG_BRAND T1
    INNER JOIN CPC.BRAND T2
    ON T1.BRAND_NAME = T2.BRAND_NAME
    AND T1.BRAND_ID <> T2.BRAND_ID
  BRAND_CODE_FORMAT_ILLEAGUAL:
    SELECT BRAND_CODE,BRAND_NAME
    FROM DC_CONFIG_BRAND
    WHERE NOT(REGEXP_LIKE(BRAND_CODE,'^[0-9a-zA-Z]+$'))
  BRAND_CODE_DUPLICATED:
    SELECT BRAND_CODE
    FROM DC_CONFIG_BRAND
    GROUP BY BRAND_CODE
    HAVING COUNT(1)>1
  PARAENT_BRAND_NAME_NOT_EXISTS:
    SELECT T1.BRAND_NAME,T1.PARENT_BRAND_NAME
    FROM DC_CONFIG_BRAND T1
    LEFT JOIN DC_CONFIG_BRAND T2
    ON T2.BRAND_NAME = T1.PARENT_BRAND_NAME
    LEFT JOIN CPC.BRAND T3
    ON T3.BRAND_NAME = T1.PARENT_BRAND_NAME
    WHERE T1.PARENT_BRAND_NAME IS NOT NULL
    AND T2.BRAND_NAME IS NULL
    AND T3.BRAND_NAME IS NULL
  BRAND_PRIORITY_NUMBER_ONLY:
    SELECT BRAND_NAME,BRAND_ID,PRIORITY
    FROM DC_CONFIG_BRAND T1
    WHERE TRANSLATE(PRIORITY,'A0123456789','A') IS NOT NULL
  CATALOG_ITEM_ID_DUPLICATED:
    SELECT CATALOG_ITEM_ID
    FROM DC_CONFIG_CATALOG_ITEM
    GROUP BY CATALOG_ITEM_ID
    HAVING COUNT(*) >1
  CATALOG_ITEM_ID_IS_NULL:
    SELECT CATALOG_NAME,CATALOG_ITEM_ID
    FROM DC_CONFIG_CATALOG_ITEM
    WHERE CATALOG_ITEM_ID IS NULL
  CATALOG_ITEM_ID_NUMBER_ONLY:
    SELECT CATALOG_NAME,CATALOG_ITEM_ID
    FROM DC_CONFIG_CATALOG_ITEM
    WHERE TRANSLATE(CATALOG_ITEM_ID,'A0123456789','A') IS NOT NULL
  CATALOG_ITEM_CODE_DUPLICATED:
    SELECT CATALOG_CODE
    FROM DC_CONFIG_CATALOG_ITEM
    GROUP BY CATALOG_CODE
    HAVING COUNT(*) >1
  CATALOG_ITEM_CODE_IS_NULL:
    SELECT CATALOG_CODE,CATALOG_ITEM_ID,CATALOG_NAME
    FROM DC_CONFIG_CATALOG_ITEM
    WHERE CATALOG_CODE IS NULL
  CATALOG_ITEM_CODE_NUMBER_ONLY:
    SELECT CATALOG_NAME
    FROM DC_CONFIG_CATALOG_ITEM
    WHERE TRANSLATE(CATALOG_CODE,'A0123456789','A') IS NOT NULL
  CATALOG_ITEM_NAME_IS_NULL:
    SELECT CATALOG_CODE,CATALOG_ITEM_ID,CATALOG_NAME
    FROM DC_CONFIG_CATALOG_ITEM
    WHERE CATALOG_NAME IS NULL
  PARENT_CATALOG_ITEM_ID_NUMBER_ONLY:
    SELECT CATALOG_NAME,CATALOG_ITEM_ID,PARENT_CATALOG_ITEM_ID
    FROM DC_CONFIG_CATALOG_ITEM
    WHERE TRANSLATE(PARENT_CATALOG_ITEM_ID,'A0123456789','A') IS NOT NULL
  ROOT_CATALOG_NAME_NOT_EXISTS:
    SELECT T1.CATALOG_NAME,T1.CATALOG_ITEM_ID,T1.ROOT_CATALOG_NAME
    FROM DC_CONFIG_CATALOG_ITEM T1
    LEFT JOIN CATALOG T2
    ON INSTR(T1.ROOT_CATALOG_NAME, T2.CATALOG_NAME) = 1
    WHERE T2.CATALOG_ID IS NULL
  CATALOG_DESC_IS_NULL:
    SELECT CATALOG_NAME,CATALOG_ITEM_ID,ROOT_CATALOG_NAME
    FROM DC_CONFIG_CATALOG_ITEM
    WHERE CATALOG_DESC IS NULL
  OFFER_REL_ROLE_ID_IS_NULL:
    SELECT OFFER_REL_ROLE_ID,OFFER_REL_ROLE_NAME
    FROM DC_CONFIG_OFFER_REL_ROLE
    WHERE OFFER_REL_ROLE_ID IS NULL
  OFFER_REL_ROLE_ID_NUMBER_ONLY:
    SELECT OFFER_REL_ROLE_ID,OFFER_REL_ROLE_NAME
    FROM DC_CONFIG_OFFER_REL_ROLE
    WHERE TRANSLATE(OFFER_REL_ROLE_ID,'A0123456789','A') IS NOT NULL
  OFFER_REL_ROLE_ID_DUPLICATED:
    SELECT OFFER_REL_ROLE_ID
    FROM DC_CONFIG_OFFER_REL_ROLE
    GROUP BY OFFER_REL_ROLE_ID HAVING COUNT(*)>1
  OFFER_REL_ROLE_CODE_DUPLICATED:
    SELECT OFFER_REL_ROLE_CODE
    FROM DC_CONFIG_OFFER_REL_ROLE
    GROUP BY OFFER_REL_ROLE_CODE HAVING COUNT(*)>1
  OFFER_REL_ROLE_CODE_IS_NULL:
    SELECT OFFER_REL_ROLE_CODE
    FROM DC_CONFIG_OFFER_REL_ROLE
    WHERE OFFER_REL_ROLE_CODE IS NULL
  PARENT_OFFER_ROLE_ID_NOT_EXISTS:
    SELECT T1.OFFER_REL_ROLE_ID,T1.OFFER_REL_ROLE_NAME
    FROM DC_CONFIG_OFFER_REL_ROLE T1
    LEFT JOIN CPC.OFFER_REL_ROLE T2
    ON T1.PARENT_OFFER_ROLE_ID = T2.ROLE_ID
    LEFT JOIN CPC.DC_CONFIG_OFFER_REL_ROLE T3
    ON T1.PARENT_OFFER_ROLE_ID = T3.OFFER_REL_ROLE_ID
    WHERE T2.ROLE_ID IS NULL
    AND T3.OFFER_REL_ROLE_ID IS NULL
    AND T1.PARENT_OFFER_ROLE_ID IS NOT NULL
  OFFER_REL_ROLE_NAME_IS_NULL:
    SELECT OFFER_REL_ROLE_ID,OFFER_REL_ROLE_NAME
    FROM DC_CONFIG_OFFER_REL_ROLE
    WHERE OFFER_REL_ROLE_NAME IS NULL
  OFFER_REL_ROLE_NAME_DUPLICATED:
    SELECT OFFER_REL_ROLE_NAME
    FROM DC_CONFIG_OFFER_REL_ROLE
    GROUP BY OFFER_REL_ROLE_NAME HAVING COUNT(*)>1
  OFFER_REL_ROLE_NAME_EXISTS:
    SELECT OFFER_REL_ROLE_NAME
    FROM DC_CONFIG_OFFER_REL_ROLE T1
    LEFT JOIN CPC.OFFER_REL_ROLE T2
    ON T1.OFFER_REL_ROLE_ID <> T2.ROLE_ID
    AND T1.OFFER_REL_ROLE_NAME = T2.ROLE_NAME
    WHERE T2.ROLE_ID IS NOT NULL
  OFFER_REL_ROLE_AREA_NOT_EXISTS:
    SELECT OFFER_REL_ROLE_NAME
    FROM DC_CONFIG_OFFER_REL_ROLE T1
    LEFT JOIN FTF.COMMON_REGION T2
    ON T1.APPLICABLE_AREA = T2.REGION_NAME
    WHERE T2.COMMON_REGION_ID IS NOT NULL
    AND T1.APPLICABLE_AREA IS NOT NULL
  OFFER_REL_ROLE_LIMIT_VALUE_NUMBER_ONLY:
    SELECT OFFER_REL_ROLE_ID,OFFER_REL_ROLE_NAME
    FROM DC_CONFIG_OFFER_REL_ROLE
    WHERE TRANSLATE(MAX_NUM,'A0123456789','A') IS NOT NULL
    OR TRANSLATE(MIN_NUM,'A0123456789','A') IS NOT NULL