BadData:
  LIFECYCLE_TRIGGER_EVENT_DUPLICATED:
    select t1.lifecycle_name,t1.convert_type,t1.clear_bal_mode,t1.trigger_event
    from DC_CONFIG_LIFECYCLE_CONVERSION t1
    group by t1.lifecycle_name,t1.convert_type,t1.clear_bal_mode,t1.trigger_event
    having count(distinct t1.elapsed_time) >1
  LIFECYCLE_NOFITY_PRIOR_DAY_NOT_BE_ZERO:
    SELECT LIFECYCLE_NAME,CONVERT_TYPE,TRIGGER_EVENT
    FROM DC_CONFIG_LIFECYCLE_NOFITY
    WHERE TO_NUMBER(prior_day)=0

ErrorData:
  LIFECYCLE_NAME_IS_NULL:
    SELECT LIFECYCLE_NAME,CONVERT_TYPE
    FROM DC_CONFIG_LIFECYCLE_CONVERSION
    WHERE LIFECYCLE_NAME IS NULL
  LIFECYCLE_CONVERT_TYPE_IS_NOT_EXISTS:
    SELECT T1.LIFECYCLE_NAME, T1.CONVERT_TYPE
    FROM DC_CONFIG_LIFECYCLE_CONVERSION T1
    LEFT JOIN (select trim(t2.attr_value_name) || '-' ||
    trim(t3.attr_value_name) convert_type
    from coc.cc_state_convert_type t1
    left join cpc.attr_value t2
    on t2.attr_id = 800052302
    and t2.status_cd = '1000'
    and t1.src_prod_state = t2.attr_value
    left join cpc.attr_value t3
    on t3.attr_id = 800052302
    and t3.status_cd = '1000'
    and t1.obj_prod_state = t3.attr_value) T2
    ON T1.convert_type = t2.convert_type
    where t2.convert_type is null
  LIFECYCLE_TARGET_IS_NOT_EXISTS:
    SELECT T1.LIFECYCLE_NAME, T1.CONVERT_TYPE
    FROM DC_CONFIG_LIFECYCLE_CONVERSION T1
    left join coc.cc_lifecycle_target_subs t2
    on t1.target_subs = t2.target_subs_name
    left join (
    select trim(t3.attr_value_name) block_reason
    from coc.cc_lifecycle_target_subs  t1
    inner join coc.cc_lifecycle_target_input t2
    on t1.target_subs_id = t2.target_subs_id
    and t2.data_type = 'S'
    inner join cpc.attr_value t3
    on t2.default_value = t3.attr_value
    and t3.attr_id = 992001414
    and t3.status_cd = '1000'
    order by t3.attr_value_name
    )t3 on t1.block_reason = t3.block_reason
    LEFT JOIN (select trim(t2.attr_value_name) || '-' ||
    trim(t3.attr_value_name) convert_type_name,
    t1.convert_type
    from coc.cc_state_convert_type t1
    left join cpc.attr_value t2
    on t2.attr_id = 800052302
    and t2.status_cd = '1000'
    and t1.src_prod_state = t2.attr_value
    left join cpc.attr_value t3
    on t3.attr_id = 800052302
    and t3.status_cd = '1000'
    and t1.obj_prod_state = t3.attr_value)t4
    on t1.convert_type = t4.convert_type_name
    where t2.target_subs_id is null
    and t3.block_reason is null
    and t4.convert_type<>1
  LIFECYCLE_TRIGGER_EVENT_NOT_EXISTS:
    SELECT T1.LIFECYCLE_NAME,T1.CONVERT_TYPE,T1.TRIGGER_EVENT
    FROM DC_CONFIG_LIFECYCLE_CONVERSION T1
    LEFT JOIN (
    select T2.SERVICE_OFFER_NAME
    from coc.service_offer_status_change t1
    inner join cpc.service_offer t2
    on t1.service_offer_id = t2.service_offer_id
    order by T2.SERVICE_OFFER_NAME) T2
    ON T1.TRIGGER_EVENT = T2.SERVICE_OFFER_NAME
    LEFT JOIN (select trim(t2.attr_value_name) || '-' ||
    trim(t3.attr_value_name) convert_type_name,
    t1.convert_type
    from coc.cc_state_convert_type t1
    left join cpc.attr_value t2
    on t2.attr_id = 800052302
    and t2.status_cd = '1000'
    and t1.src_prod_state = t2.attr_value
    left join cpc.attr_value t3
    on t3.attr_id = 800052302
    and t3.status_cd = '1000'
    and t1.obj_prod_state = t3.attr_value)t4
    ON T1.CONVERT_TYPE= T4.CONVERT_TYPE_NAME
    WHERE T2.SERVICE_OFFER_NAME IS NULL
    and t4.convert_type<>1
  LIFECYCLE_CLEAR_BAL_MODE_NOT_EXISTS:
    SELECT LIFECYCLE_NAME, CONVERT_TYPE, T1.CLEAR_BAL_MODE
    FROM DC_CONFIG_LIFECYCLE_CONVERSION T1
    LEFT JOIN coc.cc_clear_bal_mode T2
    ON T1.CLEAR_BAL_MODE = T2.MODE_NAME
    WHERE T2.MODE_NAME IS NULL
    AND T1.CLEAR_BAL_MODE IS NOT NULL
  LIFECYCLE_NOFITY_LIFECYCLE_CONVERT_EVENT_NOT_EXISTS: |
    select t1.lifecycle_name,t1.convert_type,t1.trigger_event
      from DC_CONFIG_LIFECYCLE_NOFITY t1
      left join coc.cc_lifecycle t2
        on t1.lifecycle_name = t2.lifecycle_name
      left join (select t1.convert_type,
                        trim(t2.attr_value_name) || '-' ||
                        trim(t3.attr_value_name) convert_type_name
                   from coc.cc_state_convert_type t1
                   left join cpc.attr_value t2
                     on t2.attr_id = 800052302
                    and t2.status_cd = '1000'
                    and t1.src_prod_state = t2.attr_value
                   left join cpc.attr_value t3
                     on t3.attr_id = 800052302
                    and t3.status_cd = '1000'
                    and t1.obj_prod_state = t3.attr_value) t4
        on t4.convert_type_name = t1.convert_type
      left join cpc.service_offer t6
        on t1.trigger_event = t6.service_offer_name
     left join coc.cc_lifecycle_state_convert t7
        on t2.lifecycle_id = t7.lifecycle_id
       and t4.convert_type = t7.convert_type
       and t6.service_offer_id = t7.trigger_event_id
    where t7.convert_id is null
  LIFECYCLE_NOFITY_REMINDER_FLOW_NOT_EXISTS:
    SELECT LIFECYCLE_NAME,CONVERT_TYPE
    FROM DC_CONFIG_LIFECYCLE_NOFITY T1
    LEFT JOIN (select t1.flow_name
    from cic.cic_event_flow t1
    inner join cic.cic_event t2
    on t1.inter_event_id = t2.event_id
    where t2.event_code = 'CC_LIFECYCLE_REMINDER'
    ) T2 ON T1.reminder_flow = T2.flow_name
    WHERE T2.flow_name IS NULL
  LIFECYCLE_NOFITY_PRIOR_DAY_NUMBER_ALLOWED_ONLY:
    SELECT LIFECYCLE_NAME,CONVERT_TYPE,TRIGGER_EVENT
    FROM DC_CONFIG_LIFECYCLE_NOFITY
    WHERE translate(prior_day,'A0123456789','A') IS NOT NULL
  LIFECYCLE_OFFER_REL_OFFER_NAME_NOT_EXISTS:
    SELECT T1.OFFER_NAME, T1.LIFECYCLE_NAME
    FROM DC_CONFIG_LIFECYCLE_OFFER_REL T1
    LEFT JOIN DC_CONFIG_OFFER_BASIC_INFO T2
    ON T1.OFFER_NAME = T2.OFFER_NAME
    LEFT JOIN CPC.OFFER T3
    ON T1.OFFER_NAME = T3.OFFER_NAME
    WHERE T2.OFFER_NAME IS NULL
    AND T3.OFFER_NAME IS NULL
  LIFECYCLE_OFFER_NAME_DUPLICATED:
    SELECT T1.OFFER_NAME
    FROM DC_CONFIG_LIFECYCLE_OFFER_REL T1
    GROUP BY T1.OFFER_NAME
    HAVING COUNT(1)>1
  LIFECYCLE_OFFER_REL_LIFECYCLE_NAME_NOT_EXISTS:
    SELECT T1.OFFER_NAME,T1.LIFECYCLE_NAME
    FROM DC_CONFIG_LIFECYCLE_OFFER_REL T1
    LEFT JOIN DC_CONFIG_LIFECYCLE_CONVERSION T2
    ON T1.LIFECYCLE_NAME = T2.LIFECYCLE_NAME
    LEFT JOIN coc.cc_lifecycle T3
    ON T1.LIFECYCLE_NAME = T3.LIFECYCLE_NAME
    WHERE T2.LIFECYCLE_NAME IS NULL
    AND T3.LIFECYCLE_NAME IS NULL